// Code generated by Kitex v0.15.4. DO NOT EDIT.

package financeservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	finance "group/kitex_gen/car/finance"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetBalanceSheet": kitex.NewMethodInfo(
		getBalanceSheetHandler,
		newFinanceServiceGetBalanceSheetArgs,
		newFinanceServiceGetBalanceSheetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetIncomeSheet": kitex.NewMethodInfo(
		getIncomeSheetHandler,
		newFinanceServiceGetIncomeSheetArgs,
		newFinanceServiceGetIncomeSheetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRouteSettle": kitex.NewMethodInfo(
		getRouteSettleHandler,
		newFinanceServiceGetRouteSettleArgs,
		newFinanceServiceGetRouteSettleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetScheduleSettle": kitex.NewMethodInfo(
		getScheduleSettleHandler,
		newFinanceServiceGetScheduleSettleArgs,
		newFinanceServiceGetScheduleSettleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetStationSettle": kitex.NewMethodInfo(
		getStationSettleHandler,
		newFinanceServiceGetStationSettleArgs,
		newFinanceServiceGetStationSettleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDriverSettle": kitex.NewMethodInfo(
		getDriverSettleHandler,
		newFinanceServiceGetDriverSettleArgs,
		newFinanceServiceGetDriverSettleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTransactions": kitex.NewMethodInfo(
		getTransactionsHandler,
		newFinanceServiceGetTransactionsArgs,
		newFinanceServiceGetTransactionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAbnormalTrans": kitex.NewMethodInfo(
		getAbnormalTransHandler,
		newFinanceServiceGetAbnormalTransArgs,
		newFinanceServiceGetAbnormalTransResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"HandleAbnormal": kitex.NewMethodInfo(
		handleAbnormalHandler,
		newFinanceServiceHandleAbnormalArgs,
		newFinanceServiceHandleAbnormalResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GenerateBill": kitex.NewMethodInfo(
		generateBillHandler,
		newFinanceServiceGenerateBillArgs,
		newFinanceServiceGenerateBillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Export": kitex.NewMethodInfo(
		exportHandler,
		newFinanceServiceExportArgs,
		newFinanceServiceExportResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	financeServiceServiceInfo                = NewServiceInfo()
	financeServiceServiceInfoForClient       = NewServiceInfoForClient()
	financeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return financeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return financeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return financeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FinanceService"
	handlerType := (*finance.FinanceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "finance",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getBalanceSheetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetBalanceSheetArgs)
	realResult := result.(*finance.FinanceServiceGetBalanceSheetResult)
	success, err := handler.(finance.FinanceService).GetBalanceSheet(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetBalanceSheetArgs() interface{} {
	return finance.NewFinanceServiceGetBalanceSheetArgs()
}

func newFinanceServiceGetBalanceSheetResult() interface{} {
	return finance.NewFinanceServiceGetBalanceSheetResult()
}

func getIncomeSheetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetIncomeSheetArgs)
	realResult := result.(*finance.FinanceServiceGetIncomeSheetResult)
	success, err := handler.(finance.FinanceService).GetIncomeSheet(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetIncomeSheetArgs() interface{} {
	return finance.NewFinanceServiceGetIncomeSheetArgs()
}

func newFinanceServiceGetIncomeSheetResult() interface{} {
	return finance.NewFinanceServiceGetIncomeSheetResult()
}

func getRouteSettleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetRouteSettleArgs)
	realResult := result.(*finance.FinanceServiceGetRouteSettleResult)
	success, err := handler.(finance.FinanceService).GetRouteSettle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetRouteSettleArgs() interface{} {
	return finance.NewFinanceServiceGetRouteSettleArgs()
}

func newFinanceServiceGetRouteSettleResult() interface{} {
	return finance.NewFinanceServiceGetRouteSettleResult()
}

func getScheduleSettleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetScheduleSettleArgs)
	realResult := result.(*finance.FinanceServiceGetScheduleSettleResult)
	success, err := handler.(finance.FinanceService).GetScheduleSettle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetScheduleSettleArgs() interface{} {
	return finance.NewFinanceServiceGetScheduleSettleArgs()
}

func newFinanceServiceGetScheduleSettleResult() interface{} {
	return finance.NewFinanceServiceGetScheduleSettleResult()
}

func getStationSettleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetStationSettleArgs)
	realResult := result.(*finance.FinanceServiceGetStationSettleResult)
	success, err := handler.(finance.FinanceService).GetStationSettle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetStationSettleArgs() interface{} {
	return finance.NewFinanceServiceGetStationSettleArgs()
}

func newFinanceServiceGetStationSettleResult() interface{} {
	return finance.NewFinanceServiceGetStationSettleResult()
}

func getDriverSettleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetDriverSettleArgs)
	realResult := result.(*finance.FinanceServiceGetDriverSettleResult)
	success, err := handler.(finance.FinanceService).GetDriverSettle(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetDriverSettleArgs() interface{} {
	return finance.NewFinanceServiceGetDriverSettleArgs()
}

func newFinanceServiceGetDriverSettleResult() interface{} {
	return finance.NewFinanceServiceGetDriverSettleResult()
}

func getTransactionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetTransactionsArgs)
	realResult := result.(*finance.FinanceServiceGetTransactionsResult)
	success, err := handler.(finance.FinanceService).GetTransactions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetTransactionsArgs() interface{} {
	return finance.NewFinanceServiceGetTransactionsArgs()
}

func newFinanceServiceGetTransactionsResult() interface{} {
	return finance.NewFinanceServiceGetTransactionsResult()
}

func getAbnormalTransHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGetAbnormalTransArgs)
	realResult := result.(*finance.FinanceServiceGetAbnormalTransResult)
	success, err := handler.(finance.FinanceService).GetAbnormalTrans(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGetAbnormalTransArgs() interface{} {
	return finance.NewFinanceServiceGetAbnormalTransArgs()
}

func newFinanceServiceGetAbnormalTransResult() interface{} {
	return finance.NewFinanceServiceGetAbnormalTransResult()
}

func handleAbnormalHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceHandleAbnormalArgs)
	realResult := result.(*finance.FinanceServiceHandleAbnormalResult)
	success, err := handler.(finance.FinanceService).HandleAbnormal(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceHandleAbnormalArgs() interface{} {
	return finance.NewFinanceServiceHandleAbnormalArgs()
}

func newFinanceServiceHandleAbnormalResult() interface{} {
	return finance.NewFinanceServiceHandleAbnormalResult()
}

func generateBillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceGenerateBillArgs)
	realResult := result.(*finance.FinanceServiceGenerateBillResult)
	success, err := handler.(finance.FinanceService).GenerateBill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceGenerateBillArgs() interface{} {
	return finance.NewFinanceServiceGenerateBillArgs()
}

func newFinanceServiceGenerateBillResult() interface{} {
	return finance.NewFinanceServiceGenerateBillResult()
}

func exportHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*finance.FinanceServiceExportArgs)
	realResult := result.(*finance.FinanceServiceExportResult)
	success, err := handler.(finance.FinanceService).Export(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFinanceServiceExportArgs() interface{} {
	return finance.NewFinanceServiceExportArgs()
}

func newFinanceServiceExportResult() interface{} {
	return finance.NewFinanceServiceExportResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetBalanceSheet(ctx context.Context, req *finance.BalanceSheetReq) (r *finance.BalanceSheetResp, err error) {
	var _args finance.FinanceServiceGetBalanceSheetArgs
	_args.Req = req
	var _result finance.FinanceServiceGetBalanceSheetResult
	if err = p.c.Call(ctx, "GetBalanceSheet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIncomeSheet(ctx context.Context, req *finance.IncomeSheetReq) (r *finance.IncomeSheetResp, err error) {
	var _args finance.FinanceServiceGetIncomeSheetArgs
	_args.Req = req
	var _result finance.FinanceServiceGetIncomeSheetResult
	if err = p.c.Call(ctx, "GetIncomeSheet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRouteSettle(ctx context.Context, req *finance.RouteSettleReq) (r *finance.RouteSettleResp, err error) {
	var _args finance.FinanceServiceGetRouteSettleArgs
	_args.Req = req
	var _result finance.FinanceServiceGetRouteSettleResult
	if err = p.c.Call(ctx, "GetRouteSettle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetScheduleSettle(ctx context.Context, req *finance.ScheduleSettleReq) (r *finance.ScheduleSettleResp, err error) {
	var _args finance.FinanceServiceGetScheduleSettleArgs
	_args.Req = req
	var _result finance.FinanceServiceGetScheduleSettleResult
	if err = p.c.Call(ctx, "GetScheduleSettle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStationSettle(ctx context.Context, req *finance.StationSettleReq) (r *finance.StationSettleResp, err error) {
	var _args finance.FinanceServiceGetStationSettleArgs
	_args.Req = req
	var _result finance.FinanceServiceGetStationSettleResult
	if err = p.c.Call(ctx, "GetStationSettle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDriverSettle(ctx context.Context, req *finance.DriverSettleReq) (r *finance.DriverSettleResp, err error) {
	var _args finance.FinanceServiceGetDriverSettleArgs
	_args.Req = req
	var _result finance.FinanceServiceGetDriverSettleResult
	if err = p.c.Call(ctx, "GetDriverSettle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTransactions(ctx context.Context, req *finance.TransactionReq) (r *finance.TransactionResp, err error) {
	var _args finance.FinanceServiceGetTransactionsArgs
	_args.Req = req
	var _result finance.FinanceServiceGetTransactionsResult
	if err = p.c.Call(ctx, "GetTransactions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAbnormalTrans(ctx context.Context, req *finance.AbnormalTransReq) (r *finance.AbnormalTransResp, err error) {
	var _args finance.FinanceServiceGetAbnormalTransArgs
	_args.Req = req
	var _result finance.FinanceServiceGetAbnormalTransResult
	if err = p.c.Call(ctx, "GetAbnormalTrans", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HandleAbnormal(ctx context.Context, req *finance.HandleAbnormalReq) (r *finance.HandleAbnormalResp, err error) {
	var _args finance.FinanceServiceHandleAbnormalArgs
	_args.Req = req
	var _result finance.FinanceServiceHandleAbnormalResult
	if err = p.c.Call(ctx, "HandleAbnormal", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateBill(ctx context.Context, req *finance.GenerateBillReq) (r *finance.GenerateBillResp, err error) {
	var _args finance.FinanceServiceGenerateBillArgs
	_args.Req = req
	var _result finance.FinanceServiceGenerateBillResult
	if err = p.c.Call(ctx, "GenerateBill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Export(ctx context.Context, req *finance.ExportReq) (r *finance.ExportResp, err error) {
	var _args finance.FinanceServiceExportArgs
	_args.Req = req
	var _result finance.FinanceServiceExportResult
	if err = p.c.Call(ctx, "Export", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
