// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package refund

import (
	"context"
	"fmt"
)

type RefundApplyReq struct {
	OrderId    int64   `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	UserId     int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	UserType   string  `thrift:"userType,3" frugal:"3,default,string" json:"userType"`
	Reason     string  `thrift:"reason,4" frugal:"4,default,string" json:"reason"`
	ContactWay *string `thrift:"contactWay,5,optional" frugal:"5,optional,string" json:"contactWay,omitempty"`
}

func NewRefundApplyReq() *RefundApplyReq {
	return &RefundApplyReq{}
}

func (p *RefundApplyReq) InitDefault() {
}

func (p *RefundApplyReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *RefundApplyReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *RefundApplyReq) GetUserType() (v string) {
	return p.UserType
}

func (p *RefundApplyReq) GetReason() (v string) {
	return p.Reason
}

var RefundApplyReq_ContactWay_DEFAULT string

func (p *RefundApplyReq) GetContactWay() (v string) {
	if !p.IsSetContactWay() {
		return RefundApplyReq_ContactWay_DEFAULT
	}
	return *p.ContactWay
}
func (p *RefundApplyReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *RefundApplyReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *RefundApplyReq) SetUserType(val string) {
	p.UserType = val
}
func (p *RefundApplyReq) SetReason(val string) {
	p.Reason = val
}
func (p *RefundApplyReq) SetContactWay(val *string) {
	p.ContactWay = val
}

func (p *RefundApplyReq) IsSetContactWay() bool {
	return p.ContactWay != nil
}

func (p *RefundApplyReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundApplyReq(%+v)", *p)
}

var fieldIDToName_RefundApplyReq = map[int16]string{
	1: "orderId",
	2: "userId",
	3: "userType",
	4: "reason",
	5: "contactWay",
}

type RefundApplyResp struct {
	RefundId int64  `thrift:"refundId,1" frugal:"1,default,i64" json:"refundId"`
	Message  string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Success  bool   `thrift:"success,3" frugal:"3,default,bool" json:"success"`
}

func NewRefundApplyResp() *RefundApplyResp {
	return &RefundApplyResp{}
}

func (p *RefundApplyResp) InitDefault() {
}

func (p *RefundApplyResp) GetRefundId() (v int64) {
	return p.RefundId
}

func (p *RefundApplyResp) GetMessage() (v string) {
	return p.Message
}

func (p *RefundApplyResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *RefundApplyResp) SetRefundId(val int64) {
	p.RefundId = val
}
func (p *RefundApplyResp) SetMessage(val string) {
	p.Message = val
}
func (p *RefundApplyResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *RefundApplyResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundApplyResp(%+v)", *p)
}

var fieldIDToName_RefundApplyResp = map[int16]string{
	1: "refundId",
	2: "message",
	3: "success",
}

type RefundAuditReq struct {
	RefundId     int64   `thrift:"refundId,1" frugal:"1,default,i64" json:"refundId"`
	AuditUserId  int64   `thrift:"auditUserId,2" frugal:"2,default,i64" json:"auditUserId"`
	AuditResult_ string  `thrift:"auditResult,3" frugal:"3,default,string" json:"auditResult"`
	AuditReason  *string `thrift:"auditReason,4,optional" frugal:"4,optional,string" json:"auditReason,omitempty"`
}

func NewRefundAuditReq() *RefundAuditReq {
	return &RefundAuditReq{}
}

func (p *RefundAuditReq) InitDefault() {
}

func (p *RefundAuditReq) GetRefundId() (v int64) {
	return p.RefundId
}

func (p *RefundAuditReq) GetAuditUserId() (v int64) {
	return p.AuditUserId
}

func (p *RefundAuditReq) GetAuditResult_() (v string) {
	return p.AuditResult_
}

var RefundAuditReq_AuditReason_DEFAULT string

func (p *RefundAuditReq) GetAuditReason() (v string) {
	if !p.IsSetAuditReason() {
		return RefundAuditReq_AuditReason_DEFAULT
	}
	return *p.AuditReason
}
func (p *RefundAuditReq) SetRefundId(val int64) {
	p.RefundId = val
}
func (p *RefundAuditReq) SetAuditUserId(val int64) {
	p.AuditUserId = val
}
func (p *RefundAuditReq) SetAuditResult_(val string) {
	p.AuditResult_ = val
}
func (p *RefundAuditReq) SetAuditReason(val *string) {
	p.AuditReason = val
}

func (p *RefundAuditReq) IsSetAuditReason() bool {
	return p.AuditReason != nil
}

func (p *RefundAuditReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundAuditReq(%+v)", *p)
}

var fieldIDToName_RefundAuditReq = map[int16]string{
	1: "refundId",
	2: "auditUserId",
	3: "auditResult",
	4: "auditReason",
}

type RefundAuditResp struct {
	Message      string  `thrift:"message,1" frugal:"1,default,string" json:"message"`
	Success      bool    `thrift:"success,2" frugal:"2,default,bool" json:"success"`
	RefundAmount *string `thrift:"refundAmount,3,optional" frugal:"3,optional,string" json:"refundAmount,omitempty"`
}

func NewRefundAuditResp() *RefundAuditResp {
	return &RefundAuditResp{}
}

func (p *RefundAuditResp) InitDefault() {
}

func (p *RefundAuditResp) GetMessage() (v string) {
	return p.Message
}

func (p *RefundAuditResp) GetSuccess() (v bool) {
	return p.Success
}

var RefundAuditResp_RefundAmount_DEFAULT string

func (p *RefundAuditResp) GetRefundAmount() (v string) {
	if !p.IsSetRefundAmount() {
		return RefundAuditResp_RefundAmount_DEFAULT
	}
	return *p.RefundAmount
}
func (p *RefundAuditResp) SetMessage(val string) {
	p.Message = val
}
func (p *RefundAuditResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *RefundAuditResp) SetRefundAmount(val *string) {
	p.RefundAmount = val
}

func (p *RefundAuditResp) IsSetRefundAmount() bool {
	return p.RefundAmount != nil
}

func (p *RefundAuditResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundAuditResp(%+v)", *p)
}

var fieldIDToName_RefundAuditResp = map[int16]string{
	1: "message",
	2: "success",
	3: "refundAmount",
}

type BatchRefundReq struct {
	OrderIds    []int64  `thrift:"orderIds,1" frugal:"1,default,list<i64>" json:"orderIds"`
	OperatorId  int64    `thrift:"operatorId,2" frugal:"2,default,i64" json:"operatorId"`
	RefundType  string   `thrift:"refundType,3" frugal:"3,default,string" json:"refundType"`
	Reason      string   `thrift:"reason,4" frugal:"4,default,string" json:"reason"`
	RefundRatio *float64 `thrift:"refundRatio,5,optional" frugal:"5,optional,double" json:"refundRatio,omitempty"`
}

func NewBatchRefundReq() *BatchRefundReq {
	return &BatchRefundReq{}
}

func (p *BatchRefundReq) InitDefault() {
}

func (p *BatchRefundReq) GetOrderIds() (v []int64) {
	return p.OrderIds
}

func (p *BatchRefundReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *BatchRefundReq) GetRefundType() (v string) {
	return p.RefundType
}

func (p *BatchRefundReq) GetReason() (v string) {
	return p.Reason
}

var BatchRefundReq_RefundRatio_DEFAULT float64

func (p *BatchRefundReq) GetRefundRatio() (v float64) {
	if !p.IsSetRefundRatio() {
		return BatchRefundReq_RefundRatio_DEFAULT
	}
	return *p.RefundRatio
}
func (p *BatchRefundReq) SetOrderIds(val []int64) {
	p.OrderIds = val
}
func (p *BatchRefundReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *BatchRefundReq) SetRefundType(val string) {
	p.RefundType = val
}
func (p *BatchRefundReq) SetReason(val string) {
	p.Reason = val
}
func (p *BatchRefundReq) SetRefundRatio(val *float64) {
	p.RefundRatio = val
}

func (p *BatchRefundReq) IsSetRefundRatio() bool {
	return p.RefundRatio != nil
}

func (p *BatchRefundReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchRefundReq(%+v)", *p)
}

var fieldIDToName_BatchRefundReq = map[int16]string{
	1: "orderIds",
	2: "operatorId",
	3: "refundType",
	4: "reason",
	5: "refundRatio",
}

type BatchRefundResultItem struct {
	OrderId      int64    `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	Success      bool     `thrift:"success,2" frugal:"2,default,bool" json:"success"`
	Message      string   `thrift:"message,3" frugal:"3,default,string" json:"message"`
	RefundAmount *float64 `thrift:"refundAmount,4,optional" frugal:"4,optional,double" json:"refundAmount,omitempty"`
}

func NewBatchRefundResultItem() *BatchRefundResultItem {
	return &BatchRefundResultItem{}
}

func (p *BatchRefundResultItem) InitDefault() {
}

func (p *BatchRefundResultItem) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *BatchRefundResultItem) GetSuccess() (v bool) {
	return p.Success
}

func (p *BatchRefundResultItem) GetMessage() (v string) {
	return p.Message
}

var BatchRefundResultItem_RefundAmount_DEFAULT float64

func (p *BatchRefundResultItem) GetRefundAmount() (v float64) {
	if !p.IsSetRefundAmount() {
		return BatchRefundResultItem_RefundAmount_DEFAULT
	}
	return *p.RefundAmount
}
func (p *BatchRefundResultItem) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *BatchRefundResultItem) SetSuccess(val bool) {
	p.Success = val
}
func (p *BatchRefundResultItem) SetMessage(val string) {
	p.Message = val
}
func (p *BatchRefundResultItem) SetRefundAmount(val *float64) {
	p.RefundAmount = val
}

func (p *BatchRefundResultItem) IsSetRefundAmount() bool {
	return p.RefundAmount != nil
}

func (p *BatchRefundResultItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchRefundResultItem(%+v)", *p)
}

var fieldIDToName_BatchRefundResultItem = map[int16]string{
	1: "orderId",
	2: "success",
	3: "message",
	4: "refundAmount",
}

type BatchRefundResp struct {
	Results      []*BatchRefundResultItem `thrift:"results,1" frugal:"1,default,list<BatchRefundResultItem>" json:"results"`
	SuccessCount int32                    `thrift:"successCount,2" frugal:"2,default,i32" json:"successCount"`
	FailCount    int32                    `thrift:"failCount,3" frugal:"3,default,i32" json:"failCount"`
	Message      string                   `thrift:"message,4" frugal:"4,default,string" json:"message"`
	Success      bool                     `thrift:"success,5" frugal:"5,default,bool" json:"success"`
}

func NewBatchRefundResp() *BatchRefundResp {
	return &BatchRefundResp{}
}

func (p *BatchRefundResp) InitDefault() {
}

func (p *BatchRefundResp) GetResults() (v []*BatchRefundResultItem) {
	return p.Results
}

func (p *BatchRefundResp) GetSuccessCount() (v int32) {
	return p.SuccessCount
}

func (p *BatchRefundResp) GetFailCount() (v int32) {
	return p.FailCount
}

func (p *BatchRefundResp) GetMessage() (v string) {
	return p.Message
}

func (p *BatchRefundResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *BatchRefundResp) SetResults(val []*BatchRefundResultItem) {
	p.Results = val
}
func (p *BatchRefundResp) SetSuccessCount(val int32) {
	p.SuccessCount = val
}
func (p *BatchRefundResp) SetFailCount(val int32) {
	p.FailCount = val
}
func (p *BatchRefundResp) SetMessage(val string) {
	p.Message = val
}
func (p *BatchRefundResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *BatchRefundResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchRefundResp(%+v)", *p)
}

var fieldIDToName_BatchRefundResp = map[int16]string{
	1: "results",
	2: "successCount",
	3: "failCount",
	4: "message",
	5: "success",
}

type RefundStatusQueryReq struct {
	RefundId int64 `thrift:"refundId,1" frugal:"1,default,i64" json:"refundId"`
	UserId   int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewRefundStatusQueryReq() *RefundStatusQueryReq {
	return &RefundStatusQueryReq{}
}

func (p *RefundStatusQueryReq) InitDefault() {
}

func (p *RefundStatusQueryReq) GetRefundId() (v int64) {
	return p.RefundId
}

func (p *RefundStatusQueryReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *RefundStatusQueryReq) SetRefundId(val int64) {
	p.RefundId = val
}
func (p *RefundStatusQueryReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *RefundStatusQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundStatusQueryReq(%+v)", *p)
}

var fieldIDToName_RefundStatusQueryReq = map[int16]string{
	1: "refundId",
	2: "userId",
}

type RefundStatusInfo struct {
	RefundId      int64    `thrift:"refundId,1" frugal:"1,default,i64" json:"refundId"`
	OrderId       int64    `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
	UserId        int64    `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	UserType      string   `thrift:"userType,4" frugal:"4,default,string" json:"userType"`
	Reason        string   `thrift:"reason,5" frugal:"5,default,string" json:"reason"`
	Status        string   `thrift:"status,6" frugal:"6,default,string" json:"status"`
	AuditReason   *string  `thrift:"auditReason,7,optional" frugal:"7,optional,string" json:"auditReason,omitempty"`
	RefundAmount  *float64 `thrift:"refundAmount,8,optional" frugal:"8,optional,double" json:"refundAmount,omitempty"`
	ApplyTime     string   `thrift:"applyTime,9" frugal:"9,default,string" json:"applyTime"`
	AuditTime     *string  `thrift:"auditTime,10,optional" frugal:"10,optional,string" json:"auditTime,omitempty"`
	CompletedTime *string  `thrift:"completedTime,11,optional" frugal:"11,optional,string" json:"completedTime,omitempty"`
}

func NewRefundStatusInfo() *RefundStatusInfo {
	return &RefundStatusInfo{}
}

func (p *RefundStatusInfo) InitDefault() {
}

func (p *RefundStatusInfo) GetRefundId() (v int64) {
	return p.RefundId
}

func (p *RefundStatusInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *RefundStatusInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *RefundStatusInfo) GetUserType() (v string) {
	return p.UserType
}

func (p *RefundStatusInfo) GetReason() (v string) {
	return p.Reason
}

func (p *RefundStatusInfo) GetStatus() (v string) {
	return p.Status
}

var RefundStatusInfo_AuditReason_DEFAULT string

func (p *RefundStatusInfo) GetAuditReason() (v string) {
	if !p.IsSetAuditReason() {
		return RefundStatusInfo_AuditReason_DEFAULT
	}
	return *p.AuditReason
}

var RefundStatusInfo_RefundAmount_DEFAULT float64

func (p *RefundStatusInfo) GetRefundAmount() (v float64) {
	if !p.IsSetRefundAmount() {
		return RefundStatusInfo_RefundAmount_DEFAULT
	}
	return *p.RefundAmount
}

func (p *RefundStatusInfo) GetApplyTime() (v string) {
	return p.ApplyTime
}

var RefundStatusInfo_AuditTime_DEFAULT string

func (p *RefundStatusInfo) GetAuditTime() (v string) {
	if !p.IsSetAuditTime() {
		return RefundStatusInfo_AuditTime_DEFAULT
	}
	return *p.AuditTime
}

var RefundStatusInfo_CompletedTime_DEFAULT string

func (p *RefundStatusInfo) GetCompletedTime() (v string) {
	if !p.IsSetCompletedTime() {
		return RefundStatusInfo_CompletedTime_DEFAULT
	}
	return *p.CompletedTime
}
func (p *RefundStatusInfo) SetRefundId(val int64) {
	p.RefundId = val
}
func (p *RefundStatusInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *RefundStatusInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *RefundStatusInfo) SetUserType(val string) {
	p.UserType = val
}
func (p *RefundStatusInfo) SetReason(val string) {
	p.Reason = val
}
func (p *RefundStatusInfo) SetStatus(val string) {
	p.Status = val
}
func (p *RefundStatusInfo) SetAuditReason(val *string) {
	p.AuditReason = val
}
func (p *RefundStatusInfo) SetRefundAmount(val *float64) {
	p.RefundAmount = val
}
func (p *RefundStatusInfo) SetApplyTime(val string) {
	p.ApplyTime = val
}
func (p *RefundStatusInfo) SetAuditTime(val *string) {
	p.AuditTime = val
}
func (p *RefundStatusInfo) SetCompletedTime(val *string) {
	p.CompletedTime = val
}

func (p *RefundStatusInfo) IsSetAuditReason() bool {
	return p.AuditReason != nil
}

func (p *RefundStatusInfo) IsSetRefundAmount() bool {
	return p.RefundAmount != nil
}

func (p *RefundStatusInfo) IsSetAuditTime() bool {
	return p.AuditTime != nil
}

func (p *RefundStatusInfo) IsSetCompletedTime() bool {
	return p.CompletedTime != nil
}

func (p *RefundStatusInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundStatusInfo(%+v)", *p)
}

var fieldIDToName_RefundStatusInfo = map[int16]string{
	1:  "refundId",
	2:  "orderId",
	3:  "userId",
	4:  "userType",
	5:  "reason",
	6:  "status",
	7:  "auditReason",
	8:  "refundAmount",
	9:  "applyTime",
	10: "auditTime",
	11: "completedTime",
}

type RefundStatusQueryResp struct {
	RefundInfo *RefundStatusInfo `thrift:"refundInfo,1,optional" frugal:"1,optional,RefundStatusInfo" json:"refundInfo,omitempty"`
	Message    string            `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Success    bool              `thrift:"success,3" frugal:"3,default,bool" json:"success"`
}

func NewRefundStatusQueryResp() *RefundStatusQueryResp {
	return &RefundStatusQueryResp{}
}

func (p *RefundStatusQueryResp) InitDefault() {
}

var RefundStatusQueryResp_RefundInfo_DEFAULT *RefundStatusInfo

func (p *RefundStatusQueryResp) GetRefundInfo() (v *RefundStatusInfo) {
	if !p.IsSetRefundInfo() {
		return RefundStatusQueryResp_RefundInfo_DEFAULT
	}
	return p.RefundInfo
}

func (p *RefundStatusQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *RefundStatusQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *RefundStatusQueryResp) SetRefundInfo(val *RefundStatusInfo) {
	p.RefundInfo = val
}
func (p *RefundStatusQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *RefundStatusQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *RefundStatusQueryResp) IsSetRefundInfo() bool {
	return p.RefundInfo != nil
}

func (p *RefundStatusQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundStatusQueryResp(%+v)", *p)
}

var fieldIDToName_RefundStatusQueryResp = map[int16]string{
	1: "refundInfo",
	2: "message",
	3: "success",
}

type RefundRecordQueryReq struct {
	UserId    *int64  `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	UserType  *string `thrift:"userType,2,optional" frugal:"2,optional,string" json:"userType,omitempty"`
	Status    *string `thrift:"status,3,optional" frugal:"3,optional,string" json:"status,omitempty"`
	StartDate *string `thrift:"startDate,4,optional" frugal:"4,optional,string" json:"startDate,omitempty"`
	EndDate   *string `thrift:"endDate,5,optional" frugal:"5,optional,string" json:"endDate,omitempty"`
	Page      *int32  `thrift:"page,6,optional" frugal:"6,optional,i32" json:"page,omitempty"`
	PageSize  *int32  `thrift:"pageSize,7,optional" frugal:"7,optional,i32" json:"pageSize,omitempty"`
}

func NewRefundRecordQueryReq() *RefundRecordQueryReq {
	return &RefundRecordQueryReq{}
}

func (p *RefundRecordQueryReq) InitDefault() {
}

var RefundRecordQueryReq_UserId_DEFAULT int64

func (p *RefundRecordQueryReq) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return RefundRecordQueryReq_UserId_DEFAULT
	}
	return *p.UserId
}

var RefundRecordQueryReq_UserType_DEFAULT string

func (p *RefundRecordQueryReq) GetUserType() (v string) {
	if !p.IsSetUserType() {
		return RefundRecordQueryReq_UserType_DEFAULT
	}
	return *p.UserType
}

var RefundRecordQueryReq_Status_DEFAULT string

func (p *RefundRecordQueryReq) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return RefundRecordQueryReq_Status_DEFAULT
	}
	return *p.Status
}

var RefundRecordQueryReq_StartDate_DEFAULT string

func (p *RefundRecordQueryReq) GetStartDate() (v string) {
	if !p.IsSetStartDate() {
		return RefundRecordQueryReq_StartDate_DEFAULT
	}
	return *p.StartDate
}

var RefundRecordQueryReq_EndDate_DEFAULT string

func (p *RefundRecordQueryReq) GetEndDate() (v string) {
	if !p.IsSetEndDate() {
		return RefundRecordQueryReq_EndDate_DEFAULT
	}
	return *p.EndDate
}

var RefundRecordQueryReq_Page_DEFAULT int32

func (p *RefundRecordQueryReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return RefundRecordQueryReq_Page_DEFAULT
	}
	return *p.Page
}

var RefundRecordQueryReq_PageSize_DEFAULT int32

func (p *RefundRecordQueryReq) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return RefundRecordQueryReq_PageSize_DEFAULT
	}
	return *p.PageSize
}
func (p *RefundRecordQueryReq) SetUserId(val *int64) {
	p.UserId = val
}
func (p *RefundRecordQueryReq) SetUserType(val *string) {
	p.UserType = val
}
func (p *RefundRecordQueryReq) SetStatus(val *string) {
	p.Status = val
}
func (p *RefundRecordQueryReq) SetStartDate(val *string) {
	p.StartDate = val
}
func (p *RefundRecordQueryReq) SetEndDate(val *string) {
	p.EndDate = val
}
func (p *RefundRecordQueryReq) SetPage(val *int32) {
	p.Page = val
}
func (p *RefundRecordQueryReq) SetPageSize(val *int32) {
	p.PageSize = val
}

func (p *RefundRecordQueryReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *RefundRecordQueryReq) IsSetUserType() bool {
	return p.UserType != nil
}

func (p *RefundRecordQueryReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *RefundRecordQueryReq) IsSetStartDate() bool {
	return p.StartDate != nil
}

func (p *RefundRecordQueryReq) IsSetEndDate() bool {
	return p.EndDate != nil
}

func (p *RefundRecordQueryReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *RefundRecordQueryReq) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *RefundRecordQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundRecordQueryReq(%+v)", *p)
}

var fieldIDToName_RefundRecordQueryReq = map[int16]string{
	1: "userId",
	2: "userType",
	3: "status",
	4: "startDate",
	5: "endDate",
	6: "page",
	7: "pageSize",
}

type RefundRecordQueryResp struct {
	Records  []*RefundStatusInfo `thrift:"records,1" frugal:"1,default,list<RefundStatusInfo>" json:"records"`
	Total    int32               `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	Page     int32               `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32               `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Message  string              `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success  bool                `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewRefundRecordQueryResp() *RefundRecordQueryResp {
	return &RefundRecordQueryResp{}
}

func (p *RefundRecordQueryResp) InitDefault() {
}

func (p *RefundRecordQueryResp) GetRecords() (v []*RefundStatusInfo) {
	return p.Records
}

func (p *RefundRecordQueryResp) GetTotal() (v int32) {
	return p.Total
}

func (p *RefundRecordQueryResp) GetPage() (v int32) {
	return p.Page
}

func (p *RefundRecordQueryResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *RefundRecordQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *RefundRecordQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *RefundRecordQueryResp) SetRecords(val []*RefundStatusInfo) {
	p.Records = val
}
func (p *RefundRecordQueryResp) SetTotal(val int32) {
	p.Total = val
}
func (p *RefundRecordQueryResp) SetPage(val int32) {
	p.Page = val
}
func (p *RefundRecordQueryResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *RefundRecordQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *RefundRecordQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *RefundRecordQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundRecordQueryResp(%+v)", *p)
}

var fieldIDToName_RefundRecordQueryResp = map[int16]string{
	1: "records",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "message",
	6: "success",
}

type RefundService interface {
	RefundApply(ctx context.Context, req *RefundApplyReq) (r *RefundApplyResp, err error)

	RefundAudit(ctx context.Context, req *RefundAuditReq) (r *RefundAuditResp, err error)

	BatchRefund(ctx context.Context, req *BatchRefundReq) (r *BatchRefundResp, err error)

	RefundStatusQuery(ctx context.Context, req *RefundStatusQueryReq) (r *RefundStatusQueryResp, err error)

	RefundRecordQuery(ctx context.Context, req *RefundRecordQueryReq) (r *RefundRecordQueryResp, err error)
}

type RefundServiceRefundApplyArgs struct {
	Req *RefundApplyReq `thrift:"req,1" frugal:"1,default,RefundApplyReq" json:"req"`
}

func NewRefundServiceRefundApplyArgs() *RefundServiceRefundApplyArgs {
	return &RefundServiceRefundApplyArgs{}
}

func (p *RefundServiceRefundApplyArgs) InitDefault() {
}

var RefundServiceRefundApplyArgs_Req_DEFAULT *RefundApplyReq

func (p *RefundServiceRefundApplyArgs) GetReq() (v *RefundApplyReq) {
	if !p.IsSetReq() {
		return RefundServiceRefundApplyArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RefundServiceRefundApplyArgs) SetReq(val *RefundApplyReq) {
	p.Req = val
}

func (p *RefundServiceRefundApplyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundServiceRefundApplyArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundApplyArgs(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundApplyArgs = map[int16]string{
	1: "req",
}

type RefundServiceRefundApplyResult struct {
	Success *RefundApplyResp `thrift:"success,0,optional" frugal:"0,optional,RefundApplyResp" json:"success,omitempty"`
}

func NewRefundServiceRefundApplyResult() *RefundServiceRefundApplyResult {
	return &RefundServiceRefundApplyResult{}
}

func (p *RefundServiceRefundApplyResult) InitDefault() {
}

var RefundServiceRefundApplyResult_Success_DEFAULT *RefundApplyResp

func (p *RefundServiceRefundApplyResult) GetSuccess() (v *RefundApplyResp) {
	if !p.IsSetSuccess() {
		return RefundServiceRefundApplyResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RefundServiceRefundApplyResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundApplyResp)
}

func (p *RefundServiceRefundApplyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundServiceRefundApplyResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundApplyResult(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundApplyResult = map[int16]string{
	0: "success",
}

type RefundServiceRefundAuditArgs struct {
	Req *RefundAuditReq `thrift:"req,1" frugal:"1,default,RefundAuditReq" json:"req"`
}

func NewRefundServiceRefundAuditArgs() *RefundServiceRefundAuditArgs {
	return &RefundServiceRefundAuditArgs{}
}

func (p *RefundServiceRefundAuditArgs) InitDefault() {
}

var RefundServiceRefundAuditArgs_Req_DEFAULT *RefundAuditReq

func (p *RefundServiceRefundAuditArgs) GetReq() (v *RefundAuditReq) {
	if !p.IsSetReq() {
		return RefundServiceRefundAuditArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RefundServiceRefundAuditArgs) SetReq(val *RefundAuditReq) {
	p.Req = val
}

func (p *RefundServiceRefundAuditArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundServiceRefundAuditArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundAuditArgs(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundAuditArgs = map[int16]string{
	1: "req",
}

type RefundServiceRefundAuditResult struct {
	Success *RefundAuditResp `thrift:"success,0,optional" frugal:"0,optional,RefundAuditResp" json:"success,omitempty"`
}

func NewRefundServiceRefundAuditResult() *RefundServiceRefundAuditResult {
	return &RefundServiceRefundAuditResult{}
}

func (p *RefundServiceRefundAuditResult) InitDefault() {
}

var RefundServiceRefundAuditResult_Success_DEFAULT *RefundAuditResp

func (p *RefundServiceRefundAuditResult) GetSuccess() (v *RefundAuditResp) {
	if !p.IsSetSuccess() {
		return RefundServiceRefundAuditResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RefundServiceRefundAuditResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundAuditResp)
}

func (p *RefundServiceRefundAuditResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundServiceRefundAuditResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundAuditResult(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundAuditResult = map[int16]string{
	0: "success",
}

type RefundServiceBatchRefundArgs struct {
	Req *BatchRefundReq `thrift:"req,1" frugal:"1,default,BatchRefundReq" json:"req"`
}

func NewRefundServiceBatchRefundArgs() *RefundServiceBatchRefundArgs {
	return &RefundServiceBatchRefundArgs{}
}

func (p *RefundServiceBatchRefundArgs) InitDefault() {
}

var RefundServiceBatchRefundArgs_Req_DEFAULT *BatchRefundReq

func (p *RefundServiceBatchRefundArgs) GetReq() (v *BatchRefundReq) {
	if !p.IsSetReq() {
		return RefundServiceBatchRefundArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RefundServiceBatchRefundArgs) SetReq(val *BatchRefundReq) {
	p.Req = val
}

func (p *RefundServiceBatchRefundArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundServiceBatchRefundArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceBatchRefundArgs(%+v)", *p)
}

var fieldIDToName_RefundServiceBatchRefundArgs = map[int16]string{
	1: "req",
}

type RefundServiceBatchRefundResult struct {
	Success *BatchRefundResp `thrift:"success,0,optional" frugal:"0,optional,BatchRefundResp" json:"success,omitempty"`
}

func NewRefundServiceBatchRefundResult() *RefundServiceBatchRefundResult {
	return &RefundServiceBatchRefundResult{}
}

func (p *RefundServiceBatchRefundResult) InitDefault() {
}

var RefundServiceBatchRefundResult_Success_DEFAULT *BatchRefundResp

func (p *RefundServiceBatchRefundResult) GetSuccess() (v *BatchRefundResp) {
	if !p.IsSetSuccess() {
		return RefundServiceBatchRefundResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RefundServiceBatchRefundResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchRefundResp)
}

func (p *RefundServiceBatchRefundResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundServiceBatchRefundResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceBatchRefundResult(%+v)", *p)
}

var fieldIDToName_RefundServiceBatchRefundResult = map[int16]string{
	0: "success",
}

type RefundServiceRefundStatusQueryArgs struct {
	Req *RefundStatusQueryReq `thrift:"req,1" frugal:"1,default,RefundStatusQueryReq" json:"req"`
}

func NewRefundServiceRefundStatusQueryArgs() *RefundServiceRefundStatusQueryArgs {
	return &RefundServiceRefundStatusQueryArgs{}
}

func (p *RefundServiceRefundStatusQueryArgs) InitDefault() {
}

var RefundServiceRefundStatusQueryArgs_Req_DEFAULT *RefundStatusQueryReq

func (p *RefundServiceRefundStatusQueryArgs) GetReq() (v *RefundStatusQueryReq) {
	if !p.IsSetReq() {
		return RefundServiceRefundStatusQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RefundServiceRefundStatusQueryArgs) SetReq(val *RefundStatusQueryReq) {
	p.Req = val
}

func (p *RefundServiceRefundStatusQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundServiceRefundStatusQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundStatusQueryArgs(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundStatusQueryArgs = map[int16]string{
	1: "req",
}

type RefundServiceRefundStatusQueryResult struct {
	Success *RefundStatusQueryResp `thrift:"success,0,optional" frugal:"0,optional,RefundStatusQueryResp" json:"success,omitempty"`
}

func NewRefundServiceRefundStatusQueryResult() *RefundServiceRefundStatusQueryResult {
	return &RefundServiceRefundStatusQueryResult{}
}

func (p *RefundServiceRefundStatusQueryResult) InitDefault() {
}

var RefundServiceRefundStatusQueryResult_Success_DEFAULT *RefundStatusQueryResp

func (p *RefundServiceRefundStatusQueryResult) GetSuccess() (v *RefundStatusQueryResp) {
	if !p.IsSetSuccess() {
		return RefundServiceRefundStatusQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RefundServiceRefundStatusQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundStatusQueryResp)
}

func (p *RefundServiceRefundStatusQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundServiceRefundStatusQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundStatusQueryResult(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundStatusQueryResult = map[int16]string{
	0: "success",
}

type RefundServiceRefundRecordQueryArgs struct {
	Req *RefundRecordQueryReq `thrift:"req,1" frugal:"1,default,RefundRecordQueryReq" json:"req"`
}

func NewRefundServiceRefundRecordQueryArgs() *RefundServiceRefundRecordQueryArgs {
	return &RefundServiceRefundRecordQueryArgs{}
}

func (p *RefundServiceRefundRecordQueryArgs) InitDefault() {
}

var RefundServiceRefundRecordQueryArgs_Req_DEFAULT *RefundRecordQueryReq

func (p *RefundServiceRefundRecordQueryArgs) GetReq() (v *RefundRecordQueryReq) {
	if !p.IsSetReq() {
		return RefundServiceRefundRecordQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RefundServiceRefundRecordQueryArgs) SetReq(val *RefundRecordQueryReq) {
	p.Req = val
}

func (p *RefundServiceRefundRecordQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundServiceRefundRecordQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundRecordQueryArgs(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundRecordQueryArgs = map[int16]string{
	1: "req",
}

type RefundServiceRefundRecordQueryResult struct {
	Success *RefundRecordQueryResp `thrift:"success,0,optional" frugal:"0,optional,RefundRecordQueryResp" json:"success,omitempty"`
}

func NewRefundServiceRefundRecordQueryResult() *RefundServiceRefundRecordQueryResult {
	return &RefundServiceRefundRecordQueryResult{}
}

func (p *RefundServiceRefundRecordQueryResult) InitDefault() {
}

var RefundServiceRefundRecordQueryResult_Success_DEFAULT *RefundRecordQueryResp

func (p *RefundServiceRefundRecordQueryResult) GetSuccess() (v *RefundRecordQueryResp) {
	if !p.IsSetSuccess() {
		return RefundServiceRefundRecordQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RefundServiceRefundRecordQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefundRecordQueryResp)
}

func (p *RefundServiceRefundRecordQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundServiceRefundRecordQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundServiceRefundRecordQueryResult(%+v)", *p)
}

var fieldIDToName_RefundServiceRefundRecordQueryResult = map[int16]string{
	0: "success",
}
