// Code generated by Kitex v0.16.0. DO NOT EDIT.

package uploadservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	upload "group/kitex_gen/car/upload"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ImageUpload(ctx context.Context, req *upload.ImageUploadReq, callOptions ...callopt.Option) (r *upload.ImageUploadResp, err error)
	ImageDelete(ctx context.Context, req *upload.ImageDeleteReq, callOptions ...callopt.Option) (r *upload.ImageDeleteResp, err error)
	BatchImageUpload(ctx context.Context, req *upload.BatchImageUploadReq, callOptions ...callopt.Option) (r *upload.BatchImageUploadResp, err error)
	ImageInfo(ctx context.Context, req *upload.ImageInfoReq, callOptions ...callopt.Option) (r *upload.ImageInfoResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUploadServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUploadServiceClient struct {
	*kClient
}

func (p *kUploadServiceClient) ImageUpload(ctx context.Context, req *upload.ImageUploadReq, callOptions ...callopt.Option) (r *upload.ImageUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImageUpload(ctx, req)
}

func (p *kUploadServiceClient) ImageDelete(ctx context.Context, req *upload.ImageDeleteReq, callOptions ...callopt.Option) (r *upload.ImageDeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImageDelete(ctx, req)
}

func (p *kUploadServiceClient) BatchImageUpload(ctx context.Context, req *upload.BatchImageUploadReq, callOptions ...callopt.Option) (r *upload.BatchImageUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchImageUpload(ctx, req)
}

func (p *kUploadServiceClient) ImageInfo(ctx context.Context, req *upload.ImageInfoReq, callOptions ...callopt.Option) (r *upload.ImageInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ImageInfo(ctx, req)
}
