// Code generated by Kitex v0.16.0. DO NOT EDIT.
package uploadservice

import (
	server "github.com/cloudwego/kitex/server"
	upload "group/kitex_gen/car/upload"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler upload.UploadService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler upload.UploadService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
