// Code generated by Kitex v0.16.0. DO NOT EDIT.

package uploadservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	upload "group/kitex_gen/car/upload"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ImageUpload": kitex.NewMethodInfo(
		imageUploadHandler,
		newUploadServiceImageUploadArgs,
		newUploadServiceImageUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ImageDelete": kitex.NewMethodInfo(
		imageDeleteHandler,
		newUploadServiceImageDeleteArgs,
		newUploadServiceImageDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchImageUpload": kitex.NewMethodInfo(
		batchImageUploadHandler,
		newUploadServiceBatchImageUploadArgs,
		newUploadServiceBatchImageUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ImageInfo": kitex.NewMethodInfo(
		imageInfoHandler,
		newUploadServiceImageInfoArgs,
		newUploadServiceImageInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	uploadServiceServiceInfo                = NewServiceInfo()
	uploadServiceServiceInfoForClient       = NewServiceInfoForClient()
	uploadServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return uploadServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return uploadServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return uploadServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UploadService"
	handlerType := (*upload.UploadService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "upload",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.0",
		Extra:           extra,
	}
	return svcInfo
}

func imageUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*upload.UploadServiceImageUploadArgs)
	realResult := result.(*upload.UploadServiceImageUploadResult)
	success, err := handler.(upload.UploadService).ImageUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUploadServiceImageUploadArgs() interface{} {
	return upload.NewUploadServiceImageUploadArgs()
}

func newUploadServiceImageUploadResult() interface{} {
	return upload.NewUploadServiceImageUploadResult()
}

func imageDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*upload.UploadServiceImageDeleteArgs)
	realResult := result.(*upload.UploadServiceImageDeleteResult)
	success, err := handler.(upload.UploadService).ImageDelete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUploadServiceImageDeleteArgs() interface{} {
	return upload.NewUploadServiceImageDeleteArgs()
}

func newUploadServiceImageDeleteResult() interface{} {
	return upload.NewUploadServiceImageDeleteResult()
}

func batchImageUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*upload.UploadServiceBatchImageUploadArgs)
	realResult := result.(*upload.UploadServiceBatchImageUploadResult)
	success, err := handler.(upload.UploadService).BatchImageUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUploadServiceBatchImageUploadArgs() interface{} {
	return upload.NewUploadServiceBatchImageUploadArgs()
}

func newUploadServiceBatchImageUploadResult() interface{} {
	return upload.NewUploadServiceBatchImageUploadResult()
}

func imageInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*upload.UploadServiceImageInfoArgs)
	realResult := result.(*upload.UploadServiceImageInfoResult)
	success, err := handler.(upload.UploadService).ImageInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUploadServiceImageInfoArgs() interface{} {
	return upload.NewUploadServiceImageInfoArgs()
}

func newUploadServiceImageInfoResult() interface{} {
	return upload.NewUploadServiceImageInfoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ImageUpload(ctx context.Context, req *upload.ImageUploadReq) (r *upload.ImageUploadResp, err error) {
	var _args upload.UploadServiceImageUploadArgs
	_args.Req = req
	var _result upload.UploadServiceImageUploadResult
	if err = p.c.Call(ctx, "ImageUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ImageDelete(ctx context.Context, req *upload.ImageDeleteReq) (r *upload.ImageDeleteResp, err error) {
	var _args upload.UploadServiceImageDeleteArgs
	_args.Req = req
	var _result upload.UploadServiceImageDeleteResult
	if err = p.c.Call(ctx, "ImageDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchImageUpload(ctx context.Context, req *upload.BatchImageUploadReq) (r *upload.BatchImageUploadResp, err error) {
	var _args upload.UploadServiceBatchImageUploadArgs
	_args.Req = req
	var _result upload.UploadServiceBatchImageUploadResult
	if err = p.c.Call(ctx, "BatchImageUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ImageInfo(ctx context.Context, req *upload.ImageInfoReq) (r *upload.ImageInfoResp, err error) {
	var _args upload.UploadServiceImageInfoArgs
	_args.Req = req
	var _result upload.UploadServiceImageInfoResult
	if err = p.c.Call(ctx, "ImageInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
