// Code generated by Kitex v0.15.4. DO NOT EDIT.

package routeservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	route "group/kitex_gen/car/route"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetRoute": kitex.NewMethodInfo(
		getRouteHandler,
		newRouteServiceGetRouteArgs,
		newRouteServiceGetRouteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RouteCreate": kitex.NewMethodInfo(
		routeCreateHandler,
		newRouteServiceRouteCreateArgs,
		newRouteServiceRouteCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RouteList": kitex.NewMethodInfo(
		routeListHandler,
		newRouteServiceRouteListArgs,
		newRouteServiceRouteListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RouteInfo": kitex.NewMethodInfo(
		routeInfoHandler,
		newRouteServiceRouteInfoArgs,
		newRouteServiceRouteInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RouteUpdate": kitex.NewMethodInfo(
		routeUpdateHandler,
		newRouteServiceRouteUpdateArgs,
		newRouteServiceRouteUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RouteDelete": kitex.NewMethodInfo(
		routeDeleteHandler,
		newRouteServiceRouteDeleteArgs,
		newRouteServiceRouteDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddStation": kitex.NewMethodInfo(
		addStationHandler,
		newRouteServiceAddStationArgs,
		newRouteServiceAddStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveStation": kitex.NewMethodInfo(
		removeStationHandler,
		newRouteServiceRemoveStationArgs,
		newRouteServiceRemoveStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ScheduleCreate": kitex.NewMethodInfo(
		scheduleCreateHandler,
		newRouteServiceScheduleCreateArgs,
		newRouteServiceScheduleCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ScheduleList": kitex.NewMethodInfo(
		scheduleListHandler,
		newRouteServiceScheduleListArgs,
		newRouteServiceScheduleListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ScheduleUpdate": kitex.NewMethodInfo(
		scheduleUpdateHandler,
		newRouteServiceScheduleUpdateArgs,
		newRouteServiceScheduleUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ScheduleDelete": kitex.NewMethodInfo(
		scheduleDeleteHandler,
		newRouteServiceScheduleDeleteArgs,
		newRouteServiceScheduleDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	routeServiceServiceInfo                = NewServiceInfo()
	routeServiceServiceInfoForClient       = NewServiceInfoForClient()
	routeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return routeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return routeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return routeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RouteService"
	handlerType := (*route.RouteService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "route",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getRouteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceGetRouteArgs)
	realResult := result.(*route.RouteServiceGetRouteResult)
	success, err := handler.(route.RouteService).GetRoute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceGetRouteArgs() interface{} {
	return route.NewRouteServiceGetRouteArgs()
}

func newRouteServiceGetRouteResult() interface{} {
	return route.NewRouteServiceGetRouteResult()
}

func routeCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRouteCreateArgs)
	realResult := result.(*route.RouteServiceRouteCreateResult)
	success, err := handler.(route.RouteService).RouteCreate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRouteCreateArgs() interface{} {
	return route.NewRouteServiceRouteCreateArgs()
}

func newRouteServiceRouteCreateResult() interface{} {
	return route.NewRouteServiceRouteCreateResult()
}

func routeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRouteListArgs)
	realResult := result.(*route.RouteServiceRouteListResult)
	success, err := handler.(route.RouteService).RouteList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRouteListArgs() interface{} {
	return route.NewRouteServiceRouteListArgs()
}

func newRouteServiceRouteListResult() interface{} {
	return route.NewRouteServiceRouteListResult()
}

func routeInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRouteInfoArgs)
	realResult := result.(*route.RouteServiceRouteInfoResult)
	success, err := handler.(route.RouteService).RouteInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRouteInfoArgs() interface{} {
	return route.NewRouteServiceRouteInfoArgs()
}

func newRouteServiceRouteInfoResult() interface{} {
	return route.NewRouteServiceRouteInfoResult()
}

func routeUpdateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRouteUpdateArgs)
	realResult := result.(*route.RouteServiceRouteUpdateResult)
	success, err := handler.(route.RouteService).RouteUpdate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRouteUpdateArgs() interface{} {
	return route.NewRouteServiceRouteUpdateArgs()
}

func newRouteServiceRouteUpdateResult() interface{} {
	return route.NewRouteServiceRouteUpdateResult()
}

func routeDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRouteDeleteArgs)
	realResult := result.(*route.RouteServiceRouteDeleteResult)
	success, err := handler.(route.RouteService).RouteDelete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRouteDeleteArgs() interface{} {
	return route.NewRouteServiceRouteDeleteArgs()
}

func newRouteServiceRouteDeleteResult() interface{} {
	return route.NewRouteServiceRouteDeleteResult()
}

func addStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceAddStationArgs)
	realResult := result.(*route.RouteServiceAddStationResult)
	success, err := handler.(route.RouteService).AddStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceAddStationArgs() interface{} {
	return route.NewRouteServiceAddStationArgs()
}

func newRouteServiceAddStationResult() interface{} {
	return route.NewRouteServiceAddStationResult()
}

func removeStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceRemoveStationArgs)
	realResult := result.(*route.RouteServiceRemoveStationResult)
	success, err := handler.(route.RouteService).RemoveStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceRemoveStationArgs() interface{} {
	return route.NewRouteServiceRemoveStationArgs()
}

func newRouteServiceRemoveStationResult() interface{} {
	return route.NewRouteServiceRemoveStationResult()
}

func scheduleCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceScheduleCreateArgs)
	realResult := result.(*route.RouteServiceScheduleCreateResult)
	success, err := handler.(route.RouteService).ScheduleCreate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceScheduleCreateArgs() interface{} {
	return route.NewRouteServiceScheduleCreateArgs()
}

func newRouteServiceScheduleCreateResult() interface{} {
	return route.NewRouteServiceScheduleCreateResult()
}

func scheduleListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceScheduleListArgs)
	realResult := result.(*route.RouteServiceScheduleListResult)
	success, err := handler.(route.RouteService).ScheduleList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceScheduleListArgs() interface{} {
	return route.NewRouteServiceScheduleListArgs()
}

func newRouteServiceScheduleListResult() interface{} {
	return route.NewRouteServiceScheduleListResult()
}

func scheduleUpdateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceScheduleUpdateArgs)
	realResult := result.(*route.RouteServiceScheduleUpdateResult)
	success, err := handler.(route.RouteService).ScheduleUpdate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceScheduleUpdateArgs() interface{} {
	return route.NewRouteServiceScheduleUpdateArgs()
}

func newRouteServiceScheduleUpdateResult() interface{} {
	return route.NewRouteServiceScheduleUpdateResult()
}

func scheduleDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*route.RouteServiceScheduleDeleteArgs)
	realResult := result.(*route.RouteServiceScheduleDeleteResult)
	success, err := handler.(route.RouteService).ScheduleDelete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRouteServiceScheduleDeleteArgs() interface{} {
	return route.NewRouteServiceScheduleDeleteArgs()
}

func newRouteServiceScheduleDeleteResult() interface{} {
	return route.NewRouteServiceScheduleDeleteResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetRoute(ctx context.Context, req *route.RouteReq) (r *route.RouteResp, err error) {
	var _args route.RouteServiceGetRouteArgs
	_args.Req = req
	var _result route.RouteServiceGetRouteResult
	if err = p.c.Call(ctx, "GetRoute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RouteCreate(ctx context.Context, req *route.RouteCreateReq) (r *route.RouteCreateResp, err error) {
	var _args route.RouteServiceRouteCreateArgs
	_args.Req = req
	var _result route.RouteServiceRouteCreateResult
	if err = p.c.Call(ctx, "RouteCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RouteList(ctx context.Context, req *route.RouteListReq) (r *route.RouteListResp, err error) {
	var _args route.RouteServiceRouteListArgs
	_args.Req = req
	var _result route.RouteServiceRouteListResult
	if err = p.c.Call(ctx, "RouteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RouteInfo(ctx context.Context, req *route.RouteInfoReq) (r *route.RouteInfoResp, err error) {
	var _args route.RouteServiceRouteInfoArgs
	_args.Req = req
	var _result route.RouteServiceRouteInfoResult
	if err = p.c.Call(ctx, "RouteInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RouteUpdate(ctx context.Context, req *route.RouteUpdateReq) (r *route.RouteUpdateResp, err error) {
	var _args route.RouteServiceRouteUpdateArgs
	_args.Req = req
	var _result route.RouteServiceRouteUpdateResult
	if err = p.c.Call(ctx, "RouteUpdate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RouteDelete(ctx context.Context, req *route.RouteDeleteReq) (r *route.RouteDeleteResp, err error) {
	var _args route.RouteServiceRouteDeleteArgs
	_args.Req = req
	var _result route.RouteServiceRouteDeleteResult
	if err = p.c.Call(ctx, "RouteDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddStation(ctx context.Context, req *route.AddStationReq) (r *route.AddStationResp, err error) {
	var _args route.RouteServiceAddStationArgs
	_args.Req = req
	var _result route.RouteServiceAddStationResult
	if err = p.c.Call(ctx, "AddStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveStation(ctx context.Context, req *route.RemoveStationReq) (r *route.RemoveStationResp, err error) {
	var _args route.RouteServiceRemoveStationArgs
	_args.Req = req
	var _result route.RouteServiceRemoveStationResult
	if err = p.c.Call(ctx, "RemoveStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ScheduleCreate(ctx context.Context, req *route.ScheduleCreateReq) (r *route.ScheduleCreateResp, err error) {
	var _args route.RouteServiceScheduleCreateArgs
	_args.Req = req
	var _result route.RouteServiceScheduleCreateResult
	if err = p.c.Call(ctx, "ScheduleCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ScheduleList(ctx context.Context, req *route.ScheduleListReq) (r *route.ScheduleListResp, err error) {
	var _args route.RouteServiceScheduleListArgs
	_args.Req = req
	var _result route.RouteServiceScheduleListResult
	if err = p.c.Call(ctx, "ScheduleList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ScheduleUpdate(ctx context.Context, req *route.ScheduleUpdateReq) (r *route.ScheduleUpdateResp, err error) {
	var _args route.RouteServiceScheduleUpdateArgs
	_args.Req = req
	var _result route.RouteServiceScheduleUpdateResult
	if err = p.c.Call(ctx, "ScheduleUpdate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ScheduleDelete(ctx context.Context, req *route.ScheduleDeleteReq) (r *route.ScheduleDeleteResp, err error) {
	var _args route.RouteServiceScheduleDeleteArgs
	_args.Req = req
	var _result route.RouteServiceScheduleDeleteResult
	if err = p.c.Call(ctx, "ScheduleDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
