// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package rating

import (
	"context"
	"fmt"
)

type RatingSubmitReq struct {
	OrderId   int64    `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	UserId    int64    `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Score     float64  `thrift:"score,3" frugal:"3,default,double" json:"score"`
	Tags      []string `thrift:"tags,4" frugal:"4,default,list<string>" json:"tags"`
	Comment   string   `thrift:"comment,5" frugal:"5,default,string" json:"comment"`
	RaterType string   `thrift:"raterType,6" frugal:"6,default,string" json:"raterType"`
}

func NewRatingSubmitReq() *RatingSubmitReq {
	return &RatingSubmitReq{}
}

func (p *RatingSubmitReq) InitDefault() {
}

func (p *RatingSubmitReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *RatingSubmitReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *RatingSubmitReq) GetScore() (v float64) {
	return p.Score
}

func (p *RatingSubmitReq) GetTags() (v []string) {
	return p.Tags
}

func (p *RatingSubmitReq) GetComment() (v string) {
	return p.Comment
}

func (p *RatingSubmitReq) GetRaterType() (v string) {
	return p.RaterType
}
func (p *RatingSubmitReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *RatingSubmitReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *RatingSubmitReq) SetScore(val float64) {
	p.Score = val
}
func (p *RatingSubmitReq) SetTags(val []string) {
	p.Tags = val
}
func (p *RatingSubmitReq) SetComment(val string) {
	p.Comment = val
}
func (p *RatingSubmitReq) SetRaterType(val string) {
	p.RaterType = val
}

func (p *RatingSubmitReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingSubmitReq(%+v)", *p)
}

var fieldIDToName_RatingSubmitReq = map[int16]string{
	1: "orderId",
	2: "userId",
	3: "score",
	4: "tags",
	5: "comment",
	6: "raterType",
}

type RatingSubmitResp struct {
	RatingId int64  `thrift:"ratingId,1" frugal:"1,default,i64" json:"ratingId"`
	Message  string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Success  bool   `thrift:"success,3" frugal:"3,default,bool" json:"success"`
}

func NewRatingSubmitResp() *RatingSubmitResp {
	return &RatingSubmitResp{}
}

func (p *RatingSubmitResp) InitDefault() {
}

func (p *RatingSubmitResp) GetRatingId() (v int64) {
	return p.RatingId
}

func (p *RatingSubmitResp) GetMessage() (v string) {
	return p.Message
}

func (p *RatingSubmitResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *RatingSubmitResp) SetRatingId(val int64) {
	p.RatingId = val
}
func (p *RatingSubmitResp) SetMessage(val string) {
	p.Message = val
}
func (p *RatingSubmitResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *RatingSubmitResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingSubmitResp(%+v)", *p)
}

var fieldIDToName_RatingSubmitResp = map[int16]string{
	1: "ratingId",
	2: "message",
	3: "success",
}

type RatingQueryReq struct {
	TimeRange   *string `thrift:"timeRange,1,optional" frugal:"1,optional,string" json:"timeRange,omitempty"`
	RouteId     *int64  `thrift:"routeId,2,optional" frugal:"2,optional,i64" json:"routeId,omitempty"`
	DriverId    *int64  `thrift:"driverId,3,optional" frugal:"3,optional,i64" json:"driverId,omitempty"`
	DriverPhone *string `thrift:"driverPhone,4,optional" frugal:"4,optional,string" json:"driverPhone,omitempty"`
	Page        *int32  `thrift:"page,5,optional" frugal:"5,optional,i32" json:"page,omitempty"`
	PageSize    *int32  `thrift:"pageSize,6,optional" frugal:"6,optional,i32" json:"pageSize,omitempty"`
}

func NewRatingQueryReq() *RatingQueryReq {
	return &RatingQueryReq{}
}

func (p *RatingQueryReq) InitDefault() {
}

var RatingQueryReq_TimeRange_DEFAULT string

func (p *RatingQueryReq) GetTimeRange() (v string) {
	if !p.IsSetTimeRange() {
		return RatingQueryReq_TimeRange_DEFAULT
	}
	return *p.TimeRange
}

var RatingQueryReq_RouteId_DEFAULT int64

func (p *RatingQueryReq) GetRouteId() (v int64) {
	if !p.IsSetRouteId() {
		return RatingQueryReq_RouteId_DEFAULT
	}
	return *p.RouteId
}

var RatingQueryReq_DriverId_DEFAULT int64

func (p *RatingQueryReq) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return RatingQueryReq_DriverId_DEFAULT
	}
	return *p.DriverId
}

var RatingQueryReq_DriverPhone_DEFAULT string

func (p *RatingQueryReq) GetDriverPhone() (v string) {
	if !p.IsSetDriverPhone() {
		return RatingQueryReq_DriverPhone_DEFAULT
	}
	return *p.DriverPhone
}

var RatingQueryReq_Page_DEFAULT int32

func (p *RatingQueryReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return RatingQueryReq_Page_DEFAULT
	}
	return *p.Page
}

var RatingQueryReq_PageSize_DEFAULT int32

func (p *RatingQueryReq) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return RatingQueryReq_PageSize_DEFAULT
	}
	return *p.PageSize
}
func (p *RatingQueryReq) SetTimeRange(val *string) {
	p.TimeRange = val
}
func (p *RatingQueryReq) SetRouteId(val *int64) {
	p.RouteId = val
}
func (p *RatingQueryReq) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *RatingQueryReq) SetDriverPhone(val *string) {
	p.DriverPhone = val
}
func (p *RatingQueryReq) SetPage(val *int32) {
	p.Page = val
}
func (p *RatingQueryReq) SetPageSize(val *int32) {
	p.PageSize = val
}

func (p *RatingQueryReq) IsSetTimeRange() bool {
	return p.TimeRange != nil
}

func (p *RatingQueryReq) IsSetRouteId() bool {
	return p.RouteId != nil
}

func (p *RatingQueryReq) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *RatingQueryReq) IsSetDriverPhone() bool {
	return p.DriverPhone != nil
}

func (p *RatingQueryReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *RatingQueryReq) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *RatingQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingQueryReq(%+v)", *p)
}

var fieldIDToName_RatingQueryReq = map[int16]string{
	1: "timeRange",
	2: "routeId",
	3: "driverId",
	4: "driverPhone",
	5: "page",
	6: "pageSize",
}

type RatingInfo struct {
	RatingId   int64    `thrift:"ratingId,1" frugal:"1,default,i64" json:"ratingId"`
	OrderId    int64    `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
	UserId     int64    `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	UserName   string   `thrift:"userName,4" frugal:"4,default,string" json:"userName"`
	Score      float64  `thrift:"score,5" frugal:"5,default,double" json:"score"`
	Tags       []string `thrift:"tags,6" frugal:"6,default,list<string>" json:"tags"`
	Comment    string   `thrift:"comment,7" frugal:"7,default,string" json:"comment"`
	RaterType  string   `thrift:"raterType,8" frugal:"8,default,string" json:"raterType"`
	CreatedAt  string   `thrift:"createdAt,9" frugal:"9,default,string" json:"createdAt"`
	DriverId   *int64   `thrift:"driverId,10,optional" frugal:"10,optional,i64" json:"driverId,omitempty"`
	DriverName *string  `thrift:"driverName,11,optional" frugal:"11,optional,string" json:"driverName,omitempty"`
}

func NewRatingInfo() *RatingInfo {
	return &RatingInfo{}
}

func (p *RatingInfo) InitDefault() {
}

func (p *RatingInfo) GetRatingId() (v int64) {
	return p.RatingId
}

func (p *RatingInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *RatingInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *RatingInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *RatingInfo) GetScore() (v float64) {
	return p.Score
}

func (p *RatingInfo) GetTags() (v []string) {
	return p.Tags
}

func (p *RatingInfo) GetComment() (v string) {
	return p.Comment
}

func (p *RatingInfo) GetRaterType() (v string) {
	return p.RaterType
}

func (p *RatingInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

var RatingInfo_DriverId_DEFAULT int64

func (p *RatingInfo) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return RatingInfo_DriverId_DEFAULT
	}
	return *p.DriverId
}

var RatingInfo_DriverName_DEFAULT string

func (p *RatingInfo) GetDriverName() (v string) {
	if !p.IsSetDriverName() {
		return RatingInfo_DriverName_DEFAULT
	}
	return *p.DriverName
}
func (p *RatingInfo) SetRatingId(val int64) {
	p.RatingId = val
}
func (p *RatingInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *RatingInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *RatingInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *RatingInfo) SetScore(val float64) {
	p.Score = val
}
func (p *RatingInfo) SetTags(val []string) {
	p.Tags = val
}
func (p *RatingInfo) SetComment(val string) {
	p.Comment = val
}
func (p *RatingInfo) SetRaterType(val string) {
	p.RaterType = val
}
func (p *RatingInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *RatingInfo) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *RatingInfo) SetDriverName(val *string) {
	p.DriverName = val
}

func (p *RatingInfo) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *RatingInfo) IsSetDriverName() bool {
	return p.DriverName != nil
}

func (p *RatingInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingInfo(%+v)", *p)
}

var fieldIDToName_RatingInfo = map[int16]string{
	1:  "ratingId",
	2:  "orderId",
	3:  "userId",
	4:  "userName",
	5:  "score",
	6:  "tags",
	7:  "comment",
	8:  "raterType",
	9:  "createdAt",
	10: "driverId",
	11: "driverName",
}

type RatingQueryResp struct {
	Ratings  []*RatingInfo `thrift:"ratings,1" frugal:"1,default,list<RatingInfo>" json:"ratings"`
	Total    int32         `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	Page     int32         `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32         `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Message  string        `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success  bool          `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewRatingQueryResp() *RatingQueryResp {
	return &RatingQueryResp{}
}

func (p *RatingQueryResp) InitDefault() {
}

func (p *RatingQueryResp) GetRatings() (v []*RatingInfo) {
	return p.Ratings
}

func (p *RatingQueryResp) GetTotal() (v int32) {
	return p.Total
}

func (p *RatingQueryResp) GetPage() (v int32) {
	return p.Page
}

func (p *RatingQueryResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *RatingQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *RatingQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *RatingQueryResp) SetRatings(val []*RatingInfo) {
	p.Ratings = val
}
func (p *RatingQueryResp) SetTotal(val int32) {
	p.Total = val
}
func (p *RatingQueryResp) SetPage(val int32) {
	p.Page = val
}
func (p *RatingQueryResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *RatingQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *RatingQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *RatingQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingQueryResp(%+v)", *p)
}

var fieldIDToName_RatingQueryResp = map[int16]string{
	1: "ratings",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "message",
	6: "success",
}

type OrderHistoryQueryReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
}

func NewOrderHistoryQueryReq() *OrderHistoryQueryReq {
	return &OrderHistoryQueryReq{}
}

func (p *OrderHistoryQueryReq) InitDefault() {
}

func (p *OrderHistoryQueryReq) GetOrderId() (v int64) {
	return p.OrderId
}
func (p *OrderHistoryQueryReq) SetOrderId(val int64) {
	p.OrderId = val
}

func (p *OrderHistoryQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderHistoryQueryReq(%+v)", *p)
}

var fieldIDToName_OrderHistoryQueryReq = map[int16]string{
	1: "orderId",
}

type OrderHistoryRecord struct {
	HistoryId    int64   `thrift:"historyId,1" frugal:"1,default,i64" json:"historyId"`
	OrderId      int64   `thrift:"orderId,2" frugal:"2,default,i64" json:"orderId"`
	Status       string  `thrift:"status,3" frugal:"3,default,string" json:"status"`
	Reason       string  `thrift:"reason,4" frugal:"4,default,string" json:"reason"`
	ChangedAt    string  `thrift:"changedAt,5" frugal:"5,default,string" json:"changedAt"`
	OperatorId   *int64  `thrift:"operatorId,6,optional" frugal:"6,optional,i64" json:"operatorId,omitempty"`
	OperatorName *string `thrift:"operatorName,7,optional" frugal:"7,optional,string" json:"operatorName,omitempty"`
}

func NewOrderHistoryRecord() *OrderHistoryRecord {
	return &OrderHistoryRecord{}
}

func (p *OrderHistoryRecord) InitDefault() {
}

func (p *OrderHistoryRecord) GetHistoryId() (v int64) {
	return p.HistoryId
}

func (p *OrderHistoryRecord) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderHistoryRecord) GetStatus() (v string) {
	return p.Status
}

func (p *OrderHistoryRecord) GetReason() (v string) {
	return p.Reason
}

func (p *OrderHistoryRecord) GetChangedAt() (v string) {
	return p.ChangedAt
}

var OrderHistoryRecord_OperatorId_DEFAULT int64

func (p *OrderHistoryRecord) GetOperatorId() (v int64) {
	if !p.IsSetOperatorId() {
		return OrderHistoryRecord_OperatorId_DEFAULT
	}
	return *p.OperatorId
}

var OrderHistoryRecord_OperatorName_DEFAULT string

func (p *OrderHistoryRecord) GetOperatorName() (v string) {
	if !p.IsSetOperatorName() {
		return OrderHistoryRecord_OperatorName_DEFAULT
	}
	return *p.OperatorName
}
func (p *OrderHistoryRecord) SetHistoryId(val int64) {
	p.HistoryId = val
}
func (p *OrderHistoryRecord) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderHistoryRecord) SetStatus(val string) {
	p.Status = val
}
func (p *OrderHistoryRecord) SetReason(val string) {
	p.Reason = val
}
func (p *OrderHistoryRecord) SetChangedAt(val string) {
	p.ChangedAt = val
}
func (p *OrderHistoryRecord) SetOperatorId(val *int64) {
	p.OperatorId = val
}
func (p *OrderHistoryRecord) SetOperatorName(val *string) {
	p.OperatorName = val
}

func (p *OrderHistoryRecord) IsSetOperatorId() bool {
	return p.OperatorId != nil
}

func (p *OrderHistoryRecord) IsSetOperatorName() bool {
	return p.OperatorName != nil
}

func (p *OrderHistoryRecord) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderHistoryRecord(%+v)", *p)
}

var fieldIDToName_OrderHistoryRecord = map[int16]string{
	1: "historyId",
	2: "orderId",
	3: "status",
	4: "reason",
	5: "changedAt",
	6: "operatorId",
	7: "operatorName",
}

type OrderHistoryQueryResp struct {
	Records []*OrderHistoryRecord `thrift:"records,1" frugal:"1,default,list<OrderHistoryRecord>" json:"records"`
	Message string                `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Success bool                  `thrift:"success,3" frugal:"3,default,bool" json:"success"`
}

func NewOrderHistoryQueryResp() *OrderHistoryQueryResp {
	return &OrderHistoryQueryResp{}
}

func (p *OrderHistoryQueryResp) InitDefault() {
}

func (p *OrderHistoryQueryResp) GetRecords() (v []*OrderHistoryRecord) {
	return p.Records
}

func (p *OrderHistoryQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *OrderHistoryQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *OrderHistoryQueryResp) SetRecords(val []*OrderHistoryRecord) {
	p.Records = val
}
func (p *OrderHistoryQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *OrderHistoryQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *OrderHistoryQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderHistoryQueryResp(%+v)", *p)
}

var fieldIDToName_OrderHistoryQueryResp = map[int16]string{
	1: "records",
	2: "message",
	3: "success",
}

type TicketRecordQueryReq struct {
	UserId    int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	TimeRange *string `thrift:"timeRange,2,optional" frugal:"2,optional,string" json:"timeRange,omitempty"`
	Page      *int32  `thrift:"page,3,optional" frugal:"3,optional,i32" json:"page,omitempty"`
	PageSize  *int32  `thrift:"pageSize,4,optional" frugal:"4,optional,i32" json:"pageSize,omitempty"`
}

func NewTicketRecordQueryReq() *TicketRecordQueryReq {
	return &TicketRecordQueryReq{}
}

func (p *TicketRecordQueryReq) InitDefault() {
}

func (p *TicketRecordQueryReq) GetUserId() (v int64) {
	return p.UserId
}

var TicketRecordQueryReq_TimeRange_DEFAULT string

func (p *TicketRecordQueryReq) GetTimeRange() (v string) {
	if !p.IsSetTimeRange() {
		return TicketRecordQueryReq_TimeRange_DEFAULT
	}
	return *p.TimeRange
}

var TicketRecordQueryReq_Page_DEFAULT int32

func (p *TicketRecordQueryReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return TicketRecordQueryReq_Page_DEFAULT
	}
	return *p.Page
}

var TicketRecordQueryReq_PageSize_DEFAULT int32

func (p *TicketRecordQueryReq) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return TicketRecordQueryReq_PageSize_DEFAULT
	}
	return *p.PageSize
}
func (p *TicketRecordQueryReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *TicketRecordQueryReq) SetTimeRange(val *string) {
	p.TimeRange = val
}
func (p *TicketRecordQueryReq) SetPage(val *int32) {
	p.Page = val
}
func (p *TicketRecordQueryReq) SetPageSize(val *int32) {
	p.PageSize = val
}

func (p *TicketRecordQueryReq) IsSetTimeRange() bool {
	return p.TimeRange != nil
}

func (p *TicketRecordQueryReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *TicketRecordQueryReq) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *TicketRecordQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TicketRecordQueryReq(%+v)", *p)
}

var fieldIDToName_TicketRecordQueryReq = map[int16]string{
	1: "userId",
	2: "timeRange",
	3: "page",
	4: "pageSize",
}

type TicketRecordInfo struct {
	OrderId       int64   `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OrderNo       string  `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	UserId        int64   `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	UserName      string  `thrift:"userName,4" frugal:"4,default,string" json:"userName"`
	StartPoint    string  `thrift:"startPoint,5" frugal:"5,default,string" json:"startPoint"`
	EndPoint      string  `thrift:"endPoint,6" frugal:"6,default,string" json:"endPoint"`
	DepartureTime string  `thrift:"departureTime,7" frugal:"7,default,string" json:"departureTime"`
	Price         float64 `thrift:"price,8" frugal:"8,default,double" json:"price"`
	Status        string  `thrift:"status,9" frugal:"9,default,string" json:"status"`
	CreatedAt     string  `thrift:"createdAt,10" frugal:"10,default,string" json:"createdAt"`
}

func NewTicketRecordInfo() *TicketRecordInfo {
	return &TicketRecordInfo{}
}

func (p *TicketRecordInfo) InitDefault() {
}

func (p *TicketRecordInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *TicketRecordInfo) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *TicketRecordInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *TicketRecordInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *TicketRecordInfo) GetStartPoint() (v string) {
	return p.StartPoint
}

func (p *TicketRecordInfo) GetEndPoint() (v string) {
	return p.EndPoint
}

func (p *TicketRecordInfo) GetDepartureTime() (v string) {
	return p.DepartureTime
}

func (p *TicketRecordInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *TicketRecordInfo) GetStatus() (v string) {
	return p.Status
}

func (p *TicketRecordInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *TicketRecordInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *TicketRecordInfo) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *TicketRecordInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *TicketRecordInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *TicketRecordInfo) SetStartPoint(val string) {
	p.StartPoint = val
}
func (p *TicketRecordInfo) SetEndPoint(val string) {
	p.EndPoint = val
}
func (p *TicketRecordInfo) SetDepartureTime(val string) {
	p.DepartureTime = val
}
func (p *TicketRecordInfo) SetPrice(val float64) {
	p.Price = val
}
func (p *TicketRecordInfo) SetStatus(val string) {
	p.Status = val
}
func (p *TicketRecordInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *TicketRecordInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TicketRecordInfo(%+v)", *p)
}

var fieldIDToName_TicketRecordInfo = map[int16]string{
	1:  "orderId",
	2:  "orderNo",
	3:  "userId",
	4:  "userName",
	5:  "startPoint",
	6:  "endPoint",
	7:  "departureTime",
	8:  "price",
	9:  "status",
	10: "createdAt",
}

type TicketRecordQueryResp struct {
	Records  []*TicketRecordInfo `thrift:"records,1" frugal:"1,default,list<TicketRecordInfo>" json:"records"`
	Total    int32               `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	Page     int32               `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32               `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Message  string              `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success  bool                `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewTicketRecordQueryResp() *TicketRecordQueryResp {
	return &TicketRecordQueryResp{}
}

func (p *TicketRecordQueryResp) InitDefault() {
}

func (p *TicketRecordQueryResp) GetRecords() (v []*TicketRecordInfo) {
	return p.Records
}

func (p *TicketRecordQueryResp) GetTotal() (v int32) {
	return p.Total
}

func (p *TicketRecordQueryResp) GetPage() (v int32) {
	return p.Page
}

func (p *TicketRecordQueryResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *TicketRecordQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *TicketRecordQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *TicketRecordQueryResp) SetRecords(val []*TicketRecordInfo) {
	p.Records = val
}
func (p *TicketRecordQueryResp) SetTotal(val int32) {
	p.Total = val
}
func (p *TicketRecordQueryResp) SetPage(val int32) {
	p.Page = val
}
func (p *TicketRecordQueryResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *TicketRecordQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *TicketRecordQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *TicketRecordQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TicketRecordQueryResp(%+v)", *p)
}

var fieldIDToName_TicketRecordQueryResp = map[int16]string{
	1: "records",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "message",
	6: "success",
}

type RatingService interface {
	RatingSubmit(ctx context.Context, req *RatingSubmitReq) (r *RatingSubmitResp, err error)

	RatingQuery(ctx context.Context, req *RatingQueryReq) (r *RatingQueryResp, err error)

	OrderHistoryQuery(ctx context.Context, req *OrderHistoryQueryReq) (r *OrderHistoryQueryResp, err error)

	TicketRecordQuery(ctx context.Context, req *TicketRecordQueryReq) (r *TicketRecordQueryResp, err error)
}

type RatingServiceRatingSubmitArgs struct {
	Req *RatingSubmitReq `thrift:"req,1" frugal:"1,default,RatingSubmitReq" json:"req"`
}

func NewRatingServiceRatingSubmitArgs() *RatingServiceRatingSubmitArgs {
	return &RatingServiceRatingSubmitArgs{}
}

func (p *RatingServiceRatingSubmitArgs) InitDefault() {
}

var RatingServiceRatingSubmitArgs_Req_DEFAULT *RatingSubmitReq

func (p *RatingServiceRatingSubmitArgs) GetReq() (v *RatingSubmitReq) {
	if !p.IsSetReq() {
		return RatingServiceRatingSubmitArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RatingServiceRatingSubmitArgs) SetReq(val *RatingSubmitReq) {
	p.Req = val
}

func (p *RatingServiceRatingSubmitArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RatingServiceRatingSubmitArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceRatingSubmitArgs(%+v)", *p)
}

var fieldIDToName_RatingServiceRatingSubmitArgs = map[int16]string{
	1: "req",
}

type RatingServiceRatingSubmitResult struct {
	Success *RatingSubmitResp `thrift:"success,0,optional" frugal:"0,optional,RatingSubmitResp" json:"success,omitempty"`
}

func NewRatingServiceRatingSubmitResult() *RatingServiceRatingSubmitResult {
	return &RatingServiceRatingSubmitResult{}
}

func (p *RatingServiceRatingSubmitResult) InitDefault() {
}

var RatingServiceRatingSubmitResult_Success_DEFAULT *RatingSubmitResp

func (p *RatingServiceRatingSubmitResult) GetSuccess() (v *RatingSubmitResp) {
	if !p.IsSetSuccess() {
		return RatingServiceRatingSubmitResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RatingServiceRatingSubmitResult) SetSuccess(x interface{}) {
	p.Success = x.(*RatingSubmitResp)
}

func (p *RatingServiceRatingSubmitResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RatingServiceRatingSubmitResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceRatingSubmitResult(%+v)", *p)
}

var fieldIDToName_RatingServiceRatingSubmitResult = map[int16]string{
	0: "success",
}

type RatingServiceRatingQueryArgs struct {
	Req *RatingQueryReq `thrift:"req,1" frugal:"1,default,RatingQueryReq" json:"req"`
}

func NewRatingServiceRatingQueryArgs() *RatingServiceRatingQueryArgs {
	return &RatingServiceRatingQueryArgs{}
}

func (p *RatingServiceRatingQueryArgs) InitDefault() {
}

var RatingServiceRatingQueryArgs_Req_DEFAULT *RatingQueryReq

func (p *RatingServiceRatingQueryArgs) GetReq() (v *RatingQueryReq) {
	if !p.IsSetReq() {
		return RatingServiceRatingQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RatingServiceRatingQueryArgs) SetReq(val *RatingQueryReq) {
	p.Req = val
}

func (p *RatingServiceRatingQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RatingServiceRatingQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceRatingQueryArgs(%+v)", *p)
}

var fieldIDToName_RatingServiceRatingQueryArgs = map[int16]string{
	1: "req",
}

type RatingServiceRatingQueryResult struct {
	Success *RatingQueryResp `thrift:"success,0,optional" frugal:"0,optional,RatingQueryResp" json:"success,omitempty"`
}

func NewRatingServiceRatingQueryResult() *RatingServiceRatingQueryResult {
	return &RatingServiceRatingQueryResult{}
}

func (p *RatingServiceRatingQueryResult) InitDefault() {
}

var RatingServiceRatingQueryResult_Success_DEFAULT *RatingQueryResp

func (p *RatingServiceRatingQueryResult) GetSuccess() (v *RatingQueryResp) {
	if !p.IsSetSuccess() {
		return RatingServiceRatingQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RatingServiceRatingQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*RatingQueryResp)
}

func (p *RatingServiceRatingQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RatingServiceRatingQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceRatingQueryResult(%+v)", *p)
}

var fieldIDToName_RatingServiceRatingQueryResult = map[int16]string{
	0: "success",
}

type RatingServiceOrderHistoryQueryArgs struct {
	Req *OrderHistoryQueryReq `thrift:"req,1" frugal:"1,default,OrderHistoryQueryReq" json:"req"`
}

func NewRatingServiceOrderHistoryQueryArgs() *RatingServiceOrderHistoryQueryArgs {
	return &RatingServiceOrderHistoryQueryArgs{}
}

func (p *RatingServiceOrderHistoryQueryArgs) InitDefault() {
}

var RatingServiceOrderHistoryQueryArgs_Req_DEFAULT *OrderHistoryQueryReq

func (p *RatingServiceOrderHistoryQueryArgs) GetReq() (v *OrderHistoryQueryReq) {
	if !p.IsSetReq() {
		return RatingServiceOrderHistoryQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RatingServiceOrderHistoryQueryArgs) SetReq(val *OrderHistoryQueryReq) {
	p.Req = val
}

func (p *RatingServiceOrderHistoryQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RatingServiceOrderHistoryQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceOrderHistoryQueryArgs(%+v)", *p)
}

var fieldIDToName_RatingServiceOrderHistoryQueryArgs = map[int16]string{
	1: "req",
}

type RatingServiceOrderHistoryQueryResult struct {
	Success *OrderHistoryQueryResp `thrift:"success,0,optional" frugal:"0,optional,OrderHistoryQueryResp" json:"success,omitempty"`
}

func NewRatingServiceOrderHistoryQueryResult() *RatingServiceOrderHistoryQueryResult {
	return &RatingServiceOrderHistoryQueryResult{}
}

func (p *RatingServiceOrderHistoryQueryResult) InitDefault() {
}

var RatingServiceOrderHistoryQueryResult_Success_DEFAULT *OrderHistoryQueryResp

func (p *RatingServiceOrderHistoryQueryResult) GetSuccess() (v *OrderHistoryQueryResp) {
	if !p.IsSetSuccess() {
		return RatingServiceOrderHistoryQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RatingServiceOrderHistoryQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderHistoryQueryResp)
}

func (p *RatingServiceOrderHistoryQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RatingServiceOrderHistoryQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceOrderHistoryQueryResult(%+v)", *p)
}

var fieldIDToName_RatingServiceOrderHistoryQueryResult = map[int16]string{
	0: "success",
}

type RatingServiceTicketRecordQueryArgs struct {
	Req *TicketRecordQueryReq `thrift:"req,1" frugal:"1,default,TicketRecordQueryReq" json:"req"`
}

func NewRatingServiceTicketRecordQueryArgs() *RatingServiceTicketRecordQueryArgs {
	return &RatingServiceTicketRecordQueryArgs{}
}

func (p *RatingServiceTicketRecordQueryArgs) InitDefault() {
}

var RatingServiceTicketRecordQueryArgs_Req_DEFAULT *TicketRecordQueryReq

func (p *RatingServiceTicketRecordQueryArgs) GetReq() (v *TicketRecordQueryReq) {
	if !p.IsSetReq() {
		return RatingServiceTicketRecordQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RatingServiceTicketRecordQueryArgs) SetReq(val *TicketRecordQueryReq) {
	p.Req = val
}

func (p *RatingServiceTicketRecordQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RatingServiceTicketRecordQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceTicketRecordQueryArgs(%+v)", *p)
}

var fieldIDToName_RatingServiceTicketRecordQueryArgs = map[int16]string{
	1: "req",
}

type RatingServiceTicketRecordQueryResult struct {
	Success *TicketRecordQueryResp `thrift:"success,0,optional" frugal:"0,optional,TicketRecordQueryResp" json:"success,omitempty"`
}

func NewRatingServiceTicketRecordQueryResult() *RatingServiceTicketRecordQueryResult {
	return &RatingServiceTicketRecordQueryResult{}
}

func (p *RatingServiceTicketRecordQueryResult) InitDefault() {
}

var RatingServiceTicketRecordQueryResult_Success_DEFAULT *TicketRecordQueryResp

func (p *RatingServiceTicketRecordQueryResult) GetSuccess() (v *TicketRecordQueryResp) {
	if !p.IsSetSuccess() {
		return RatingServiceTicketRecordQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RatingServiceTicketRecordQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*TicketRecordQueryResp)
}

func (p *RatingServiceTicketRecordQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RatingServiceTicketRecordQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RatingServiceTicketRecordQueryResult(%+v)", *p)
}

var fieldIDToName_RatingServiceTicketRecordQueryResult = map[int16]string{
	0: "success",
}
