// Code generated by Kitex v0.15.4. DO NOT EDIT.

package ratingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	rating "group/kitex_gen/car/rating"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RatingSubmit": kitex.NewMethodInfo(
		ratingSubmitHandler,
		newRatingServiceRatingSubmitArgs,
		newRatingServiceRatingSubmitResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RatingQuery": kitex.NewMethodInfo(
		ratingQueryHandler,
		newRatingServiceRatingQueryArgs,
		newRatingServiceRatingQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OrderHistoryQuery": kitex.NewMethodInfo(
		orderHistoryQueryHandler,
		newRatingServiceOrderHistoryQueryArgs,
		newRatingServiceOrderHistoryQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TicketRecordQuery": kitex.NewMethodInfo(
		ticketRecordQueryHandler,
		newRatingServiceTicketRecordQueryArgs,
		newRatingServiceTicketRecordQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	ratingServiceServiceInfo                = NewServiceInfo()
	ratingServiceServiceInfoForClient       = NewServiceInfoForClient()
	ratingServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ratingServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ratingServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ratingServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RatingService"
	handlerType := (*rating.RatingService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rating",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func ratingSubmitHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rating.RatingServiceRatingSubmitArgs)
	realResult := result.(*rating.RatingServiceRatingSubmitResult)
	success, err := handler.(rating.RatingService).RatingSubmit(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRatingServiceRatingSubmitArgs() interface{} {
	return rating.NewRatingServiceRatingSubmitArgs()
}

func newRatingServiceRatingSubmitResult() interface{} {
	return rating.NewRatingServiceRatingSubmitResult()
}

func ratingQueryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rating.RatingServiceRatingQueryArgs)
	realResult := result.(*rating.RatingServiceRatingQueryResult)
	success, err := handler.(rating.RatingService).RatingQuery(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRatingServiceRatingQueryArgs() interface{} {
	return rating.NewRatingServiceRatingQueryArgs()
}

func newRatingServiceRatingQueryResult() interface{} {
	return rating.NewRatingServiceRatingQueryResult()
}

func orderHistoryQueryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rating.RatingServiceOrderHistoryQueryArgs)
	realResult := result.(*rating.RatingServiceOrderHistoryQueryResult)
	success, err := handler.(rating.RatingService).OrderHistoryQuery(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRatingServiceOrderHistoryQueryArgs() interface{} {
	return rating.NewRatingServiceOrderHistoryQueryArgs()
}

func newRatingServiceOrderHistoryQueryResult() interface{} {
	return rating.NewRatingServiceOrderHistoryQueryResult()
}

func ticketRecordQueryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rating.RatingServiceTicketRecordQueryArgs)
	realResult := result.(*rating.RatingServiceTicketRecordQueryResult)
	success, err := handler.(rating.RatingService).TicketRecordQuery(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRatingServiceTicketRecordQueryArgs() interface{} {
	return rating.NewRatingServiceTicketRecordQueryArgs()
}

func newRatingServiceTicketRecordQueryResult() interface{} {
	return rating.NewRatingServiceTicketRecordQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RatingSubmit(ctx context.Context, req *rating.RatingSubmitReq) (r *rating.RatingSubmitResp, err error) {
	var _args rating.RatingServiceRatingSubmitArgs
	_args.Req = req
	var _result rating.RatingServiceRatingSubmitResult
	if err = p.c.Call(ctx, "RatingSubmit", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RatingQuery(ctx context.Context, req *rating.RatingQueryReq) (r *rating.RatingQueryResp, err error) {
	var _args rating.RatingServiceRatingQueryArgs
	_args.Req = req
	var _result rating.RatingServiceRatingQueryResult
	if err = p.c.Call(ctx, "RatingQuery", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OrderHistoryQuery(ctx context.Context, req *rating.OrderHistoryQueryReq) (r *rating.OrderHistoryQueryResp, err error) {
	var _args rating.RatingServiceOrderHistoryQueryArgs
	_args.Req = req
	var _result rating.RatingServiceOrderHistoryQueryResult
	if err = p.c.Call(ctx, "OrderHistoryQuery", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TicketRecordQuery(ctx context.Context, req *rating.TicketRecordQueryReq) (r *rating.TicketRecordQueryResp, err error) {
	var _args rating.RatingServiceTicketRecordQueryArgs
	_args.Req = req
	var _result rating.RatingServiceTicketRecordQueryResult
	if err = p.c.Call(ctx, "TicketRecordQuery", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
