// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order_manage

import (
	"context"
	"fmt"
)

type OrderCreateReq struct {
	TripId        int64   `thrift:"tripId,1" frugal:"1,default,i64" json:"tripId"`
	PassengerId   int64   `thrift:"passengerId,2" frugal:"2,default,i64" json:"passengerId"`
	PassengerName string  `thrift:"passengerName,3" frugal:"3,default,string" json:"passengerName"`
	PassengerTel  string  `thrift:"passengerTel,4" frugal:"4,default,string" json:"passengerTel"`
	OrderType     string  `thrift:"orderType,5" frugal:"5,default,string" json:"orderType"`
	StartPoint    string  `thrift:"startPoint,6" frugal:"6,default,string" json:"startPoint"`
	EndPoint      string  `thrift:"endPoint,7" frugal:"7,default,string" json:"endPoint"`
	DepartureTime string  `thrift:"departureTime,8" frugal:"8,default,string" json:"departureTime"`
	Price         float64 `thrift:"price,9" frugal:"9,default,double" json:"price"`
	PaymentMethod string  `thrift:"paymentMethod,10" frugal:"10,default,string" json:"paymentMethod"`
	SeatCount     int32   `thrift:"seatCount,11" frugal:"11,default,i32" json:"seatCount"`
	RouteId       *string `thrift:"routeId,12,optional" frugal:"12,optional,string" json:"routeId,omitempty"`
	SpecialNeeds  *string `thrift:"specialNeeds,13,optional" frugal:"13,optional,string" json:"specialNeeds,omitempty"`
}

func NewOrderCreateReq() *OrderCreateReq {
	return &OrderCreateReq{}
}

func (p *OrderCreateReq) InitDefault() {
}

func (p *OrderCreateReq) GetTripId() (v int64) {
	return p.TripId
}

func (p *OrderCreateReq) GetPassengerId() (v int64) {
	return p.PassengerId
}

func (p *OrderCreateReq) GetPassengerName() (v string) {
	return p.PassengerName
}

func (p *OrderCreateReq) GetPassengerTel() (v string) {
	return p.PassengerTel
}

func (p *OrderCreateReq) GetOrderType() (v string) {
	return p.OrderType
}

func (p *OrderCreateReq) GetStartPoint() (v string) {
	return p.StartPoint
}

func (p *OrderCreateReq) GetEndPoint() (v string) {
	return p.EndPoint
}

func (p *OrderCreateReq) GetDepartureTime() (v string) {
	return p.DepartureTime
}

func (p *OrderCreateReq) GetPrice() (v float64) {
	return p.Price
}

func (p *OrderCreateReq) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}

func (p *OrderCreateReq) GetSeatCount() (v int32) {
	return p.SeatCount
}

var OrderCreateReq_RouteId_DEFAULT string

func (p *OrderCreateReq) GetRouteId() (v string) {
	if !p.IsSetRouteId() {
		return OrderCreateReq_RouteId_DEFAULT
	}
	return *p.RouteId
}

var OrderCreateReq_SpecialNeeds_DEFAULT string

func (p *OrderCreateReq) GetSpecialNeeds() (v string) {
	if !p.IsSetSpecialNeeds() {
		return OrderCreateReq_SpecialNeeds_DEFAULT
	}
	return *p.SpecialNeeds
}
func (p *OrderCreateReq) SetTripId(val int64) {
	p.TripId = val
}
func (p *OrderCreateReq) SetPassengerId(val int64) {
	p.PassengerId = val
}
func (p *OrderCreateReq) SetPassengerName(val string) {
	p.PassengerName = val
}
func (p *OrderCreateReq) SetPassengerTel(val string) {
	p.PassengerTel = val
}
func (p *OrderCreateReq) SetOrderType(val string) {
	p.OrderType = val
}
func (p *OrderCreateReq) SetStartPoint(val string) {
	p.StartPoint = val
}
func (p *OrderCreateReq) SetEndPoint(val string) {
	p.EndPoint = val
}
func (p *OrderCreateReq) SetDepartureTime(val string) {
	p.DepartureTime = val
}
func (p *OrderCreateReq) SetPrice(val float64) {
	p.Price = val
}
func (p *OrderCreateReq) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}
func (p *OrderCreateReq) SetSeatCount(val int32) {
	p.SeatCount = val
}
func (p *OrderCreateReq) SetRouteId(val *string) {
	p.RouteId = val
}
func (p *OrderCreateReq) SetSpecialNeeds(val *string) {
	p.SpecialNeeds = val
}

func (p *OrderCreateReq) IsSetRouteId() bool {
	return p.RouteId != nil
}

func (p *OrderCreateReq) IsSetSpecialNeeds() bool {
	return p.SpecialNeeds != nil
}

func (p *OrderCreateReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderCreateReq(%+v)", *p)
}

var fieldIDToName_OrderCreateReq = map[int16]string{
	1:  "tripId",
	2:  "passengerId",
	3:  "passengerName",
	4:  "passengerTel",
	5:  "orderType",
	6:  "startPoint",
	7:  "endPoint",
	8:  "departureTime",
	9:  "price",
	10: "paymentMethod",
	11: "seatCount",
	12: "routeId",
	13: "specialNeeds",
}

type OrderCreateResp struct {
	OrderId int64  `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OrderNo string `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	Success bool   `thrift:"success,3" frugal:"3,default,bool" json:"success"`
	Message string `thrift:"message,4" frugal:"4,default,string" json:"message"`
}

func NewOrderCreateResp() *OrderCreateResp {
	return &OrderCreateResp{}
}

func (p *OrderCreateResp) InitDefault() {
}

func (p *OrderCreateResp) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderCreateResp) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *OrderCreateResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderCreateResp) GetMessage() (v string) {
	return p.Message
}
func (p *OrderCreateResp) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderCreateResp) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *OrderCreateResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderCreateResp) SetMessage(val string) {
	p.Message = val
}

func (p *OrderCreateResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderCreateResp(%+v)", *p)
}

var fieldIDToName_OrderCreateResp = map[int16]string{
	1: "orderId",
	2: "orderNo",
	3: "success",
	4: "message",
}

type OrderPaymentStatusReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	UserId  int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewOrderPaymentStatusReq() *OrderPaymentStatusReq {
	return &OrderPaymentStatusReq{}
}

func (p *OrderPaymentStatusReq) InitDefault() {
}

func (p *OrderPaymentStatusReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderPaymentStatusReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *OrderPaymentStatusReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderPaymentStatusReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *OrderPaymentStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderPaymentStatusReq(%+v)", *p)
}

var fieldIDToName_OrderPaymentStatusReq = map[int16]string{
	1: "orderId",
	2: "userId",
}

type OrderPaymentStatusResp struct {
	PaymentStatus string  `thrift:"paymentStatus,1" frugal:"1,default,string" json:"paymentStatus"`
	PaymentMethod string  `thrift:"paymentMethod,2" frugal:"2,default,string" json:"paymentMethod"`
	PaymentAmount float64 `thrift:"paymentAmount,3" frugal:"3,default,double" json:"paymentAmount"`
	PaymentTime   string  `thrift:"paymentTime,4" frugal:"4,default,string" json:"paymentTime"`
	Success       bool    `thrift:"success,5" frugal:"5,default,bool" json:"success"`
	Message       string  `thrift:"message,6" frugal:"6,default,string" json:"message"`
}

func NewOrderPaymentStatusResp() *OrderPaymentStatusResp {
	return &OrderPaymentStatusResp{}
}

func (p *OrderPaymentStatusResp) InitDefault() {
}

func (p *OrderPaymentStatusResp) GetPaymentStatus() (v string) {
	return p.PaymentStatus
}

func (p *OrderPaymentStatusResp) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}

func (p *OrderPaymentStatusResp) GetPaymentAmount() (v float64) {
	return p.PaymentAmount
}

func (p *OrderPaymentStatusResp) GetPaymentTime() (v string) {
	return p.PaymentTime
}

func (p *OrderPaymentStatusResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderPaymentStatusResp) GetMessage() (v string) {
	return p.Message
}
func (p *OrderPaymentStatusResp) SetPaymentStatus(val string) {
	p.PaymentStatus = val
}
func (p *OrderPaymentStatusResp) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}
func (p *OrderPaymentStatusResp) SetPaymentAmount(val float64) {
	p.PaymentAmount = val
}
func (p *OrderPaymentStatusResp) SetPaymentTime(val string) {
	p.PaymentTime = val
}
func (p *OrderPaymentStatusResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderPaymentStatusResp) SetMessage(val string) {
	p.Message = val
}

func (p *OrderPaymentStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderPaymentStatusResp(%+v)", *p)
}

var fieldIDToName_OrderPaymentStatusResp = map[int16]string{
	1: "paymentStatus",
	2: "paymentMethod",
	3: "paymentAmount",
	4: "paymentTime",
	5: "success",
	6: "message",
}

type OrderQueryReq struct {
	OrderType    *string `thrift:"orderType,1,optional" frugal:"1,optional,string" json:"orderType,omitempty"`
	Status       *string `thrift:"status,2,optional" frugal:"2,optional,string" json:"status,omitempty"`
	StartTime    *string `thrift:"startTime,3,optional" frugal:"3,optional,string" json:"startTime,omitempty"`
	EndTime      *string `thrift:"endTime,4,optional" frugal:"4,optional,string" json:"endTime,omitempty"`
	RouteId      *string `thrift:"routeId,5,optional" frugal:"5,optional,string" json:"routeId,omitempty"`
	PassengerTel *string `thrift:"passengerTel,6,optional" frugal:"6,optional,string" json:"passengerTel,omitempty"`
	PassengerId  *int64  `thrift:"passengerId,7,optional" frugal:"7,optional,i64" json:"passengerId,omitempty"`
	DriverId     *int64  `thrift:"driverId,8,optional" frugal:"8,optional,i64" json:"driverId,omitempty"`
	Page         *int32  `thrift:"page,9,optional" frugal:"9,optional,i32" json:"page,omitempty"`
	PageSize     *int32  `thrift:"pageSize,10,optional" frugal:"10,optional,i32" json:"pageSize,omitempty"`
}

func NewOrderQueryReq() *OrderQueryReq {
	return &OrderQueryReq{}
}

func (p *OrderQueryReq) InitDefault() {
}

var OrderQueryReq_OrderType_DEFAULT string

func (p *OrderQueryReq) GetOrderType() (v string) {
	if !p.IsSetOrderType() {
		return OrderQueryReq_OrderType_DEFAULT
	}
	return *p.OrderType
}

var OrderQueryReq_Status_DEFAULT string

func (p *OrderQueryReq) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return OrderQueryReq_Status_DEFAULT
	}
	return *p.Status
}

var OrderQueryReq_StartTime_DEFAULT string

func (p *OrderQueryReq) GetStartTime() (v string) {
	if !p.IsSetStartTime() {
		return OrderQueryReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var OrderQueryReq_EndTime_DEFAULT string

func (p *OrderQueryReq) GetEndTime() (v string) {
	if !p.IsSetEndTime() {
		return OrderQueryReq_EndTime_DEFAULT
	}
	return *p.EndTime
}

var OrderQueryReq_RouteId_DEFAULT string

func (p *OrderQueryReq) GetRouteId() (v string) {
	if !p.IsSetRouteId() {
		return OrderQueryReq_RouteId_DEFAULT
	}
	return *p.RouteId
}

var OrderQueryReq_PassengerTel_DEFAULT string

func (p *OrderQueryReq) GetPassengerTel() (v string) {
	if !p.IsSetPassengerTel() {
		return OrderQueryReq_PassengerTel_DEFAULT
	}
	return *p.PassengerTel
}

var OrderQueryReq_PassengerId_DEFAULT int64

func (p *OrderQueryReq) GetPassengerId() (v int64) {
	if !p.IsSetPassengerId() {
		return OrderQueryReq_PassengerId_DEFAULT
	}
	return *p.PassengerId
}

var OrderQueryReq_DriverId_DEFAULT int64

func (p *OrderQueryReq) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return OrderQueryReq_DriverId_DEFAULT
	}
	return *p.DriverId
}

var OrderQueryReq_Page_DEFAULT int32

func (p *OrderQueryReq) GetPage() (v int32) {
	if !p.IsSetPage() {
		return OrderQueryReq_Page_DEFAULT
	}
	return *p.Page
}

var OrderQueryReq_PageSize_DEFAULT int32

func (p *OrderQueryReq) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return OrderQueryReq_PageSize_DEFAULT
	}
	return *p.PageSize
}
func (p *OrderQueryReq) SetOrderType(val *string) {
	p.OrderType = val
}
func (p *OrderQueryReq) SetStatus(val *string) {
	p.Status = val
}
func (p *OrderQueryReq) SetStartTime(val *string) {
	p.StartTime = val
}
func (p *OrderQueryReq) SetEndTime(val *string) {
	p.EndTime = val
}
func (p *OrderQueryReq) SetRouteId(val *string) {
	p.RouteId = val
}
func (p *OrderQueryReq) SetPassengerTel(val *string) {
	p.PassengerTel = val
}
func (p *OrderQueryReq) SetPassengerId(val *int64) {
	p.PassengerId = val
}
func (p *OrderQueryReq) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *OrderQueryReq) SetPage(val *int32) {
	p.Page = val
}
func (p *OrderQueryReq) SetPageSize(val *int32) {
	p.PageSize = val
}

func (p *OrderQueryReq) IsSetOrderType() bool {
	return p.OrderType != nil
}

func (p *OrderQueryReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *OrderQueryReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *OrderQueryReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *OrderQueryReq) IsSetRouteId() bool {
	return p.RouteId != nil
}

func (p *OrderQueryReq) IsSetPassengerTel() bool {
	return p.PassengerTel != nil
}

func (p *OrderQueryReq) IsSetPassengerId() bool {
	return p.PassengerId != nil
}

func (p *OrderQueryReq) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *OrderQueryReq) IsSetPage() bool {
	return p.Page != nil
}

func (p *OrderQueryReq) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *OrderQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderQueryReq(%+v)", *p)
}

var fieldIDToName_OrderQueryReq = map[int16]string{
	1:  "orderType",
	2:  "status",
	3:  "startTime",
	4:  "endTime",
	5:  "routeId",
	6:  "passengerTel",
	7:  "passengerId",
	8:  "driverId",
	9:  "page",
	10: "pageSize",
}

type OrderInfo struct {
	OrderId       int64   `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OrderNo       string  `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	OrderType     string  `thrift:"orderType,3" frugal:"3,default,string" json:"orderType"`
	PassengerId   int64   `thrift:"passengerId,4" frugal:"4,default,i64" json:"passengerId"`
	PassengerName string  `thrift:"passengerName,5" frugal:"5,default,string" json:"passengerName"`
	PassengerTel  string  `thrift:"passengerTel,6" frugal:"6,default,string" json:"passengerTel"`
	StartPoint    string  `thrift:"startPoint,7" frugal:"7,default,string" json:"startPoint"`
	EndPoint      string  `thrift:"endPoint,8" frugal:"8,default,string" json:"endPoint"`
	DepartureTime string  `thrift:"departureTime,9" frugal:"9,default,string" json:"departureTime"`
	Status        string  `thrift:"status,10" frugal:"10,default,string" json:"status"`
	Price         float64 `thrift:"price,11" frugal:"11,default,double" json:"price"`
	PaymentStatus string  `thrift:"paymentStatus,12" frugal:"12,default,string" json:"paymentStatus"`
	PaymentMethod string  `thrift:"paymentMethod,13" frugal:"13,default,string" json:"paymentMethod"`
	CreatedAt     string  `thrift:"createdAt,14" frugal:"14,default,string" json:"createdAt"`
	DriverId      *int64  `thrift:"driverId,15,optional" frugal:"15,optional,i64" json:"driverId,omitempty"`
	DriverName    *string `thrift:"driverName,16,optional" frugal:"16,optional,string" json:"driverName,omitempty"`
	VehicleInfo   *string `thrift:"vehicleInfo,17,optional" frugal:"17,optional,string" json:"vehicleInfo,omitempty"`
	RouteId       *string `thrift:"routeId,18,optional" frugal:"18,optional,string" json:"routeId,omitempty"`
}

func NewOrderInfo() *OrderInfo {
	return &OrderInfo{}
}

func (p *OrderInfo) InitDefault() {
}

func (p *OrderInfo) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderInfo) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *OrderInfo) GetOrderType() (v string) {
	return p.OrderType
}

func (p *OrderInfo) GetPassengerId() (v int64) {
	return p.PassengerId
}

func (p *OrderInfo) GetPassengerName() (v string) {
	return p.PassengerName
}

func (p *OrderInfo) GetPassengerTel() (v string) {
	return p.PassengerTel
}

func (p *OrderInfo) GetStartPoint() (v string) {
	return p.StartPoint
}

func (p *OrderInfo) GetEndPoint() (v string) {
	return p.EndPoint
}

func (p *OrderInfo) GetDepartureTime() (v string) {
	return p.DepartureTime
}

func (p *OrderInfo) GetStatus() (v string) {
	return p.Status
}

func (p *OrderInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *OrderInfo) GetPaymentStatus() (v string) {
	return p.PaymentStatus
}

func (p *OrderInfo) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}

func (p *OrderInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

var OrderInfo_DriverId_DEFAULT int64

func (p *OrderInfo) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return OrderInfo_DriverId_DEFAULT
	}
	return *p.DriverId
}

var OrderInfo_DriverName_DEFAULT string

func (p *OrderInfo) GetDriverName() (v string) {
	if !p.IsSetDriverName() {
		return OrderInfo_DriverName_DEFAULT
	}
	return *p.DriverName
}

var OrderInfo_VehicleInfo_DEFAULT string

func (p *OrderInfo) GetVehicleInfo() (v string) {
	if !p.IsSetVehicleInfo() {
		return OrderInfo_VehicleInfo_DEFAULT
	}
	return *p.VehicleInfo
}

var OrderInfo_RouteId_DEFAULT string

func (p *OrderInfo) GetRouteId() (v string) {
	if !p.IsSetRouteId() {
		return OrderInfo_RouteId_DEFAULT
	}
	return *p.RouteId
}
func (p *OrderInfo) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderInfo) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *OrderInfo) SetOrderType(val string) {
	p.OrderType = val
}
func (p *OrderInfo) SetPassengerId(val int64) {
	p.PassengerId = val
}
func (p *OrderInfo) SetPassengerName(val string) {
	p.PassengerName = val
}
func (p *OrderInfo) SetPassengerTel(val string) {
	p.PassengerTel = val
}
func (p *OrderInfo) SetStartPoint(val string) {
	p.StartPoint = val
}
func (p *OrderInfo) SetEndPoint(val string) {
	p.EndPoint = val
}
func (p *OrderInfo) SetDepartureTime(val string) {
	p.DepartureTime = val
}
func (p *OrderInfo) SetStatus(val string) {
	p.Status = val
}
func (p *OrderInfo) SetPrice(val float64) {
	p.Price = val
}
func (p *OrderInfo) SetPaymentStatus(val string) {
	p.PaymentStatus = val
}
func (p *OrderInfo) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}
func (p *OrderInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *OrderInfo) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *OrderInfo) SetDriverName(val *string) {
	p.DriverName = val
}
func (p *OrderInfo) SetVehicleInfo(val *string) {
	p.VehicleInfo = val
}
func (p *OrderInfo) SetRouteId(val *string) {
	p.RouteId = val
}

func (p *OrderInfo) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *OrderInfo) IsSetDriverName() bool {
	return p.DriverName != nil
}

func (p *OrderInfo) IsSetVehicleInfo() bool {
	return p.VehicleInfo != nil
}

func (p *OrderInfo) IsSetRouteId() bool {
	return p.RouteId != nil
}

func (p *OrderInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderInfo(%+v)", *p)
}

var fieldIDToName_OrderInfo = map[int16]string{
	1:  "orderId",
	2:  "orderNo",
	3:  "orderType",
	4:  "passengerId",
	5:  "passengerName",
	6:  "passengerTel",
	7:  "startPoint",
	8:  "endPoint",
	9:  "departureTime",
	10: "status",
	11: "price",
	12: "paymentStatus",
	13: "paymentMethod",
	14: "createdAt",
	15: "driverId",
	16: "driverName",
	17: "vehicleInfo",
	18: "routeId",
}

type OrderQueryResp struct {
	Orders   []*OrderInfo `thrift:"orders,1" frugal:"1,default,list<OrderInfo>" json:"orders"`
	Total    int32        `thrift:"total,2" frugal:"2,default,i32" json:"total"`
	Page     int32        `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32        `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Success  bool         `thrift:"success,5" frugal:"5,default,bool" json:"success"`
	Message  string       `thrift:"message,6" frugal:"6,default,string" json:"message"`
}

func NewOrderQueryResp() *OrderQueryResp {
	return &OrderQueryResp{}
}

func (p *OrderQueryResp) InitDefault() {
}

func (p *OrderQueryResp) GetOrders() (v []*OrderInfo) {
	return p.Orders
}

func (p *OrderQueryResp) GetTotal() (v int32) {
	return p.Total
}

func (p *OrderQueryResp) GetPage() (v int32) {
	return p.Page
}

func (p *OrderQueryResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *OrderQueryResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderQueryResp) GetMessage() (v string) {
	return p.Message
}
func (p *OrderQueryResp) SetOrders(val []*OrderInfo) {
	p.Orders = val
}
func (p *OrderQueryResp) SetTotal(val int32) {
	p.Total = val
}
func (p *OrderQueryResp) SetPage(val int32) {
	p.Page = val
}
func (p *OrderQueryResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *OrderQueryResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderQueryResp) SetMessage(val string) {
	p.Message = val
}

func (p *OrderQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderQueryResp(%+v)", *p)
}

var fieldIDToName_OrderQueryResp = map[int16]string{
	1: "orders",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "success",
	6: "message",
}

type OrderDetailReq struct {
	OrderId int64 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	UserId  int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewOrderDetailReq() *OrderDetailReq {
	return &OrderDetailReq{}
}

func (p *OrderDetailReq) InitDefault() {
}

func (p *OrderDetailReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderDetailReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *OrderDetailReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderDetailReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *OrderDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderDetailReq(%+v)", *p)
}

var fieldIDToName_OrderDetailReq = map[int16]string{
	1: "orderId",
	2: "userId",
}

type OrderDetail struct {
	OrderId       int64                 `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OrderNo       string                `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	OrderType     string                `thrift:"orderType,3" frugal:"3,default,string" json:"orderType"`
	PassengerId   int64                 `thrift:"passengerId,4" frugal:"4,default,i64" json:"passengerId"`
	PassengerName string                `thrift:"passengerName,5" frugal:"5,default,string" json:"passengerName"`
	PassengerTel  string                `thrift:"passengerTel,6" frugal:"6,default,string" json:"passengerTel"`
	StartPoint    string                `thrift:"startPoint,7" frugal:"7,default,string" json:"startPoint"`
	EndPoint      string                `thrift:"endPoint,8" frugal:"8,default,string" json:"endPoint"`
	DepartureTime string                `thrift:"departureTime,9" frugal:"9,default,string" json:"departureTime"`
	Status        string                `thrift:"status,10" frugal:"10,default,string" json:"status"`
	Price         float64               `thrift:"price,11" frugal:"11,default,double" json:"price"`
	PaymentStatus string                `thrift:"paymentStatus,12" frugal:"12,default,string" json:"paymentStatus"`
	PaymentMethod string                `thrift:"paymentMethod,13" frugal:"13,default,string" json:"paymentMethod"`
	CreatedAt     string                `thrift:"createdAt,14" frugal:"14,default,string" json:"createdAt"`
	DriverId      *int64                `thrift:"driverId,15,optional" frugal:"15,optional,i64" json:"driverId,omitempty"`
	DriverName    *string               `thrift:"driverName,16,optional" frugal:"16,optional,string" json:"driverName,omitempty"`
	DriverTel     *string               `thrift:"driverTel,17,optional" frugal:"17,optional,string" json:"driverTel,omitempty"`
	VehicleInfo   *string               `thrift:"vehicleInfo,18,optional" frugal:"18,optional,string" json:"vehicleInfo,omitempty"`
	RouteId       *string               `thrift:"routeId,19,optional" frugal:"19,optional,string" json:"routeId,omitempty"`
	SpecialNeeds  *string               `thrift:"specialNeeds,20,optional" frugal:"20,optional,string" json:"specialNeeds,omitempty"`
	SeatCount     *int32                `thrift:"seatCount,21,optional" frugal:"21,optional,i32" json:"seatCount,omitempty"`
	AcceptedAt    *string               `thrift:"acceptedAt,22,optional" frugal:"22,optional,string" json:"acceptedAt,omitempty"`
	CompletedAt   *string               `thrift:"completedAt,23,optional" frugal:"23,optional,string" json:"completedAt,omitempty"`
	CancelledAt   *string               `thrift:"cancelledAt,24,optional" frugal:"24,optional,string" json:"cancelledAt,omitempty"`
	StatusHistory []*OrderStatusHistory `thrift:"statusHistory,25" frugal:"25,default,list<OrderStatusHistory>" json:"statusHistory"`
}

func NewOrderDetail() *OrderDetail {
	return &OrderDetail{}
}

func (p *OrderDetail) InitDefault() {
}

func (p *OrderDetail) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderDetail) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *OrderDetail) GetOrderType() (v string) {
	return p.OrderType
}

func (p *OrderDetail) GetPassengerId() (v int64) {
	return p.PassengerId
}

func (p *OrderDetail) GetPassengerName() (v string) {
	return p.PassengerName
}

func (p *OrderDetail) GetPassengerTel() (v string) {
	return p.PassengerTel
}

func (p *OrderDetail) GetStartPoint() (v string) {
	return p.StartPoint
}

func (p *OrderDetail) GetEndPoint() (v string) {
	return p.EndPoint
}

func (p *OrderDetail) GetDepartureTime() (v string) {
	return p.DepartureTime
}

func (p *OrderDetail) GetStatus() (v string) {
	return p.Status
}

func (p *OrderDetail) GetPrice() (v float64) {
	return p.Price
}

func (p *OrderDetail) GetPaymentStatus() (v string) {
	return p.PaymentStatus
}

func (p *OrderDetail) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}

func (p *OrderDetail) GetCreatedAt() (v string) {
	return p.CreatedAt
}

var OrderDetail_DriverId_DEFAULT int64

func (p *OrderDetail) GetDriverId() (v int64) {
	if !p.IsSetDriverId() {
		return OrderDetail_DriverId_DEFAULT
	}
	return *p.DriverId
}

var OrderDetail_DriverName_DEFAULT string

func (p *OrderDetail) GetDriverName() (v string) {
	if !p.IsSetDriverName() {
		return OrderDetail_DriverName_DEFAULT
	}
	return *p.DriverName
}

var OrderDetail_DriverTel_DEFAULT string

func (p *OrderDetail) GetDriverTel() (v string) {
	if !p.IsSetDriverTel() {
		return OrderDetail_DriverTel_DEFAULT
	}
	return *p.DriverTel
}

var OrderDetail_VehicleInfo_DEFAULT string

func (p *OrderDetail) GetVehicleInfo() (v string) {
	if !p.IsSetVehicleInfo() {
		return OrderDetail_VehicleInfo_DEFAULT
	}
	return *p.VehicleInfo
}

var OrderDetail_RouteId_DEFAULT string

func (p *OrderDetail) GetRouteId() (v string) {
	if !p.IsSetRouteId() {
		return OrderDetail_RouteId_DEFAULT
	}
	return *p.RouteId
}

var OrderDetail_SpecialNeeds_DEFAULT string

func (p *OrderDetail) GetSpecialNeeds() (v string) {
	if !p.IsSetSpecialNeeds() {
		return OrderDetail_SpecialNeeds_DEFAULT
	}
	return *p.SpecialNeeds
}

var OrderDetail_SeatCount_DEFAULT int32

func (p *OrderDetail) GetSeatCount() (v int32) {
	if !p.IsSetSeatCount() {
		return OrderDetail_SeatCount_DEFAULT
	}
	return *p.SeatCount
}

var OrderDetail_AcceptedAt_DEFAULT string

func (p *OrderDetail) GetAcceptedAt() (v string) {
	if !p.IsSetAcceptedAt() {
		return OrderDetail_AcceptedAt_DEFAULT
	}
	return *p.AcceptedAt
}

var OrderDetail_CompletedAt_DEFAULT string

func (p *OrderDetail) GetCompletedAt() (v string) {
	if !p.IsSetCompletedAt() {
		return OrderDetail_CompletedAt_DEFAULT
	}
	return *p.CompletedAt
}

var OrderDetail_CancelledAt_DEFAULT string

func (p *OrderDetail) GetCancelledAt() (v string) {
	if !p.IsSetCancelledAt() {
		return OrderDetail_CancelledAt_DEFAULT
	}
	return *p.CancelledAt
}

func (p *OrderDetail) GetStatusHistory() (v []*OrderStatusHistory) {
	return p.StatusHistory
}
func (p *OrderDetail) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderDetail) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *OrderDetail) SetOrderType(val string) {
	p.OrderType = val
}
func (p *OrderDetail) SetPassengerId(val int64) {
	p.PassengerId = val
}
func (p *OrderDetail) SetPassengerName(val string) {
	p.PassengerName = val
}
func (p *OrderDetail) SetPassengerTel(val string) {
	p.PassengerTel = val
}
func (p *OrderDetail) SetStartPoint(val string) {
	p.StartPoint = val
}
func (p *OrderDetail) SetEndPoint(val string) {
	p.EndPoint = val
}
func (p *OrderDetail) SetDepartureTime(val string) {
	p.DepartureTime = val
}
func (p *OrderDetail) SetStatus(val string) {
	p.Status = val
}
func (p *OrderDetail) SetPrice(val float64) {
	p.Price = val
}
func (p *OrderDetail) SetPaymentStatus(val string) {
	p.PaymentStatus = val
}
func (p *OrderDetail) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}
func (p *OrderDetail) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *OrderDetail) SetDriverId(val *int64) {
	p.DriverId = val
}
func (p *OrderDetail) SetDriverName(val *string) {
	p.DriverName = val
}
func (p *OrderDetail) SetDriverTel(val *string) {
	p.DriverTel = val
}
func (p *OrderDetail) SetVehicleInfo(val *string) {
	p.VehicleInfo = val
}
func (p *OrderDetail) SetRouteId(val *string) {
	p.RouteId = val
}
func (p *OrderDetail) SetSpecialNeeds(val *string) {
	p.SpecialNeeds = val
}
func (p *OrderDetail) SetSeatCount(val *int32) {
	p.SeatCount = val
}
func (p *OrderDetail) SetAcceptedAt(val *string) {
	p.AcceptedAt = val
}
func (p *OrderDetail) SetCompletedAt(val *string) {
	p.CompletedAt = val
}
func (p *OrderDetail) SetCancelledAt(val *string) {
	p.CancelledAt = val
}
func (p *OrderDetail) SetStatusHistory(val []*OrderStatusHistory) {
	p.StatusHistory = val
}

func (p *OrderDetail) IsSetDriverId() bool {
	return p.DriverId != nil
}

func (p *OrderDetail) IsSetDriverName() bool {
	return p.DriverName != nil
}

func (p *OrderDetail) IsSetDriverTel() bool {
	return p.DriverTel != nil
}

func (p *OrderDetail) IsSetVehicleInfo() bool {
	return p.VehicleInfo != nil
}

func (p *OrderDetail) IsSetRouteId() bool {
	return p.RouteId != nil
}

func (p *OrderDetail) IsSetSpecialNeeds() bool {
	return p.SpecialNeeds != nil
}

func (p *OrderDetail) IsSetSeatCount() bool {
	return p.SeatCount != nil
}

func (p *OrderDetail) IsSetAcceptedAt() bool {
	return p.AcceptedAt != nil
}

func (p *OrderDetail) IsSetCompletedAt() bool {
	return p.CompletedAt != nil
}

func (p *OrderDetail) IsSetCancelledAt() bool {
	return p.CancelledAt != nil
}

func (p *OrderDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderDetail(%+v)", *p)
}

var fieldIDToName_OrderDetail = map[int16]string{
	1:  "orderId",
	2:  "orderNo",
	3:  "orderType",
	4:  "passengerId",
	5:  "passengerName",
	6:  "passengerTel",
	7:  "startPoint",
	8:  "endPoint",
	9:  "departureTime",
	10: "status",
	11: "price",
	12: "paymentStatus",
	13: "paymentMethod",
	14: "createdAt",
	15: "driverId",
	16: "driverName",
	17: "driverTel",
	18: "vehicleInfo",
	19: "routeId",
	20: "specialNeeds",
	21: "seatCount",
	22: "acceptedAt",
	23: "completedAt",
	24: "cancelledAt",
	25: "statusHistory",
}

type OrderStatusHistory struct {
	Status       string  `thrift:"status,1" frugal:"1,default,string" json:"status"`
	ChangedAt    string  `thrift:"changedAt,2" frugal:"2,default,string" json:"changedAt"`
	Reason       *string `thrift:"reason,3,optional" frugal:"3,optional,string" json:"reason,omitempty"`
	OperatorId   *int64  `thrift:"operatorId,4,optional" frugal:"4,optional,i64" json:"operatorId,omitempty"`
	OperatorName *string `thrift:"operatorName,5,optional" frugal:"5,optional,string" json:"operatorName,omitempty"`
}

func NewOrderStatusHistory() *OrderStatusHistory {
	return &OrderStatusHistory{}
}

func (p *OrderStatusHistory) InitDefault() {
}

func (p *OrderStatusHistory) GetStatus() (v string) {
	return p.Status
}

func (p *OrderStatusHistory) GetChangedAt() (v string) {
	return p.ChangedAt
}

var OrderStatusHistory_Reason_DEFAULT string

func (p *OrderStatusHistory) GetReason() (v string) {
	if !p.IsSetReason() {
		return OrderStatusHistory_Reason_DEFAULT
	}
	return *p.Reason
}

var OrderStatusHistory_OperatorId_DEFAULT int64

func (p *OrderStatusHistory) GetOperatorId() (v int64) {
	if !p.IsSetOperatorId() {
		return OrderStatusHistory_OperatorId_DEFAULT
	}
	return *p.OperatorId
}

var OrderStatusHistory_OperatorName_DEFAULT string

func (p *OrderStatusHistory) GetOperatorName() (v string) {
	if !p.IsSetOperatorName() {
		return OrderStatusHistory_OperatorName_DEFAULT
	}
	return *p.OperatorName
}
func (p *OrderStatusHistory) SetStatus(val string) {
	p.Status = val
}
func (p *OrderStatusHistory) SetChangedAt(val string) {
	p.ChangedAt = val
}
func (p *OrderStatusHistory) SetReason(val *string) {
	p.Reason = val
}
func (p *OrderStatusHistory) SetOperatorId(val *int64) {
	p.OperatorId = val
}
func (p *OrderStatusHistory) SetOperatorName(val *string) {
	p.OperatorName = val
}

func (p *OrderStatusHistory) IsSetReason() bool {
	return p.Reason != nil
}

func (p *OrderStatusHistory) IsSetOperatorId() bool {
	return p.OperatorId != nil
}

func (p *OrderStatusHistory) IsSetOperatorName() bool {
	return p.OperatorName != nil
}

func (p *OrderStatusHistory) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderStatusHistory(%+v)", *p)
}

var fieldIDToName_OrderStatusHistory = map[int16]string{
	1: "status",
	2: "changedAt",
	3: "reason",
	4: "operatorId",
	5: "operatorName",
}

type OrderDetailResp struct {
	OrderDetail *OrderDetail `thrift:"orderDetail,1" frugal:"1,default,OrderDetail" json:"orderDetail"`
	Success     bool         `thrift:"success,2" frugal:"2,default,bool" json:"success"`
	Message     string       `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewOrderDetailResp() *OrderDetailResp {
	return &OrderDetailResp{}
}

func (p *OrderDetailResp) InitDefault() {
}

var OrderDetailResp_OrderDetail_DEFAULT *OrderDetail

func (p *OrderDetailResp) GetOrderDetail() (v *OrderDetail) {
	if !p.IsSetOrderDetail() {
		return OrderDetailResp_OrderDetail_DEFAULT
	}
	return p.OrderDetail
}

func (p *OrderDetailResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderDetailResp) GetMessage() (v string) {
	return p.Message
}
func (p *OrderDetailResp) SetOrderDetail(val *OrderDetail) {
	p.OrderDetail = val
}
func (p *OrderDetailResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderDetailResp) SetMessage(val string) {
	p.Message = val
}

func (p *OrderDetailResp) IsSetOrderDetail() bool {
	return p.OrderDetail != nil
}

func (p *OrderDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderDetailResp(%+v)", *p)
}

var fieldIDToName_OrderDetailResp = map[int16]string{
	1: "orderDetail",
	2: "success",
	3: "message",
}

type OrderStatusUpdateReq struct {
	OrderId      int64   `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OperatorId   int64   `thrift:"operatorId,2" frugal:"2,default,i64" json:"operatorId"`
	OperatorType string  `thrift:"operatorType,3" frugal:"3,default,string" json:"operatorType"`
	NewStatus_   string  `thrift:"newStatus,4" frugal:"4,default,string" json:"newStatus"`
	Reason       *string `thrift:"reason,5,optional" frugal:"5,optional,string" json:"reason,omitempty"`
}

func NewOrderStatusUpdateReq() *OrderStatusUpdateReq {
	return &OrderStatusUpdateReq{}
}

func (p *OrderStatusUpdateReq) InitDefault() {
}

func (p *OrderStatusUpdateReq) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *OrderStatusUpdateReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *OrderStatusUpdateReq) GetOperatorType() (v string) {
	return p.OperatorType
}

func (p *OrderStatusUpdateReq) GetNewStatus_() (v string) {
	return p.NewStatus_
}

var OrderStatusUpdateReq_Reason_DEFAULT string

func (p *OrderStatusUpdateReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return OrderStatusUpdateReq_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *OrderStatusUpdateReq) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *OrderStatusUpdateReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *OrderStatusUpdateReq) SetOperatorType(val string) {
	p.OperatorType = val
}
func (p *OrderStatusUpdateReq) SetNewStatus_(val string) {
	p.NewStatus_ = val
}
func (p *OrderStatusUpdateReq) SetReason(val *string) {
	p.Reason = val
}

func (p *OrderStatusUpdateReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *OrderStatusUpdateReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderStatusUpdateReq(%+v)", *p)
}

var fieldIDToName_OrderStatusUpdateReq = map[int16]string{
	1: "orderId",
	2: "operatorId",
	3: "operatorType",
	4: "newStatus",
	5: "reason",
}

type OrderStatusUpdateResp struct {
	Success       bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Message       string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	CurrentStatus string `thrift:"currentStatus,3" frugal:"3,default,string" json:"currentStatus"`
}

func NewOrderStatusUpdateResp() *OrderStatusUpdateResp {
	return &OrderStatusUpdateResp{}
}

func (p *OrderStatusUpdateResp) InitDefault() {
}

func (p *OrderStatusUpdateResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderStatusUpdateResp) GetMessage() (v string) {
	return p.Message
}

func (p *OrderStatusUpdateResp) GetCurrentStatus() (v string) {
	return p.CurrentStatus
}
func (p *OrderStatusUpdateResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderStatusUpdateResp) SetMessage(val string) {
	p.Message = val
}
func (p *OrderStatusUpdateResp) SetCurrentStatus(val string) {
	p.CurrentStatus = val
}

func (p *OrderStatusUpdateResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderStatusUpdateResp(%+v)", *p)
}

var fieldIDToName_OrderStatusUpdateResp = map[int16]string{
	1: "success",
	2: "message",
	3: "currentStatus",
}

type OrderManageService interface {
	OrderCreate(ctx context.Context, req *OrderCreateReq) (r *OrderCreateResp, err error)

	OrderPaymentStatus(ctx context.Context, req *OrderPaymentStatusReq) (r *OrderPaymentStatusResp, err error)

	OrderQuery(ctx context.Context, req *OrderQueryReq) (r *OrderQueryResp, err error)

	OrderDetail(ctx context.Context, req *OrderDetailReq) (r *OrderDetailResp, err error)

	OrderStatusUpdate(ctx context.Context, req *OrderStatusUpdateReq) (r *OrderStatusUpdateResp, err error)
}

type OrderManageServiceOrderCreateArgs struct {
	Req *OrderCreateReq `thrift:"req,1" frugal:"1,default,OrderCreateReq" json:"req"`
}

func NewOrderManageServiceOrderCreateArgs() *OrderManageServiceOrderCreateArgs {
	return &OrderManageServiceOrderCreateArgs{}
}

func (p *OrderManageServiceOrderCreateArgs) InitDefault() {
}

var OrderManageServiceOrderCreateArgs_Req_DEFAULT *OrderCreateReq

func (p *OrderManageServiceOrderCreateArgs) GetReq() (v *OrderCreateReq) {
	if !p.IsSetReq() {
		return OrderManageServiceOrderCreateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderManageServiceOrderCreateArgs) SetReq(val *OrderCreateReq) {
	p.Req = val
}

func (p *OrderManageServiceOrderCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderManageServiceOrderCreateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderCreateArgs(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderCreateArgs = map[int16]string{
	1: "req",
}

type OrderManageServiceOrderCreateResult struct {
	Success *OrderCreateResp `thrift:"success,0,optional" frugal:"0,optional,OrderCreateResp" json:"success,omitempty"`
}

func NewOrderManageServiceOrderCreateResult() *OrderManageServiceOrderCreateResult {
	return &OrderManageServiceOrderCreateResult{}
}

func (p *OrderManageServiceOrderCreateResult) InitDefault() {
}

var OrderManageServiceOrderCreateResult_Success_DEFAULT *OrderCreateResp

func (p *OrderManageServiceOrderCreateResult) GetSuccess() (v *OrderCreateResp) {
	if !p.IsSetSuccess() {
		return OrderManageServiceOrderCreateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderManageServiceOrderCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderCreateResp)
}

func (p *OrderManageServiceOrderCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderManageServiceOrderCreateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderCreateResult(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderCreateResult = map[int16]string{
	0: "success",
}

type OrderManageServiceOrderPaymentStatusArgs struct {
	Req *OrderPaymentStatusReq `thrift:"req,1" frugal:"1,default,OrderPaymentStatusReq" json:"req"`
}

func NewOrderManageServiceOrderPaymentStatusArgs() *OrderManageServiceOrderPaymentStatusArgs {
	return &OrderManageServiceOrderPaymentStatusArgs{}
}

func (p *OrderManageServiceOrderPaymentStatusArgs) InitDefault() {
}

var OrderManageServiceOrderPaymentStatusArgs_Req_DEFAULT *OrderPaymentStatusReq

func (p *OrderManageServiceOrderPaymentStatusArgs) GetReq() (v *OrderPaymentStatusReq) {
	if !p.IsSetReq() {
		return OrderManageServiceOrderPaymentStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderManageServiceOrderPaymentStatusArgs) SetReq(val *OrderPaymentStatusReq) {
	p.Req = val
}

func (p *OrderManageServiceOrderPaymentStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderManageServiceOrderPaymentStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderPaymentStatusArgs(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderPaymentStatusArgs = map[int16]string{
	1: "req",
}

type OrderManageServiceOrderPaymentStatusResult struct {
	Success *OrderPaymentStatusResp `thrift:"success,0,optional" frugal:"0,optional,OrderPaymentStatusResp" json:"success,omitempty"`
}

func NewOrderManageServiceOrderPaymentStatusResult() *OrderManageServiceOrderPaymentStatusResult {
	return &OrderManageServiceOrderPaymentStatusResult{}
}

func (p *OrderManageServiceOrderPaymentStatusResult) InitDefault() {
}

var OrderManageServiceOrderPaymentStatusResult_Success_DEFAULT *OrderPaymentStatusResp

func (p *OrderManageServiceOrderPaymentStatusResult) GetSuccess() (v *OrderPaymentStatusResp) {
	if !p.IsSetSuccess() {
		return OrderManageServiceOrderPaymentStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderManageServiceOrderPaymentStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderPaymentStatusResp)
}

func (p *OrderManageServiceOrderPaymentStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderManageServiceOrderPaymentStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderPaymentStatusResult(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderPaymentStatusResult = map[int16]string{
	0: "success",
}

type OrderManageServiceOrderQueryArgs struct {
	Req *OrderQueryReq `thrift:"req,1" frugal:"1,default,OrderQueryReq" json:"req"`
}

func NewOrderManageServiceOrderQueryArgs() *OrderManageServiceOrderQueryArgs {
	return &OrderManageServiceOrderQueryArgs{}
}

func (p *OrderManageServiceOrderQueryArgs) InitDefault() {
}

var OrderManageServiceOrderQueryArgs_Req_DEFAULT *OrderQueryReq

func (p *OrderManageServiceOrderQueryArgs) GetReq() (v *OrderQueryReq) {
	if !p.IsSetReq() {
		return OrderManageServiceOrderQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderManageServiceOrderQueryArgs) SetReq(val *OrderQueryReq) {
	p.Req = val
}

func (p *OrderManageServiceOrderQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderManageServiceOrderQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderQueryArgs(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderQueryArgs = map[int16]string{
	1: "req",
}

type OrderManageServiceOrderQueryResult struct {
	Success *OrderQueryResp `thrift:"success,0,optional" frugal:"0,optional,OrderQueryResp" json:"success,omitempty"`
}

func NewOrderManageServiceOrderQueryResult() *OrderManageServiceOrderQueryResult {
	return &OrderManageServiceOrderQueryResult{}
}

func (p *OrderManageServiceOrderQueryResult) InitDefault() {
}

var OrderManageServiceOrderQueryResult_Success_DEFAULT *OrderQueryResp

func (p *OrderManageServiceOrderQueryResult) GetSuccess() (v *OrderQueryResp) {
	if !p.IsSetSuccess() {
		return OrderManageServiceOrderQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderManageServiceOrderQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderQueryResp)
}

func (p *OrderManageServiceOrderQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderManageServiceOrderQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderQueryResult(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderQueryResult = map[int16]string{
	0: "success",
}

type OrderManageServiceOrderDetailArgs struct {
	Req *OrderDetailReq `thrift:"req,1" frugal:"1,default,OrderDetailReq" json:"req"`
}

func NewOrderManageServiceOrderDetailArgs() *OrderManageServiceOrderDetailArgs {
	return &OrderManageServiceOrderDetailArgs{}
}

func (p *OrderManageServiceOrderDetailArgs) InitDefault() {
}

var OrderManageServiceOrderDetailArgs_Req_DEFAULT *OrderDetailReq

func (p *OrderManageServiceOrderDetailArgs) GetReq() (v *OrderDetailReq) {
	if !p.IsSetReq() {
		return OrderManageServiceOrderDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderManageServiceOrderDetailArgs) SetReq(val *OrderDetailReq) {
	p.Req = val
}

func (p *OrderManageServiceOrderDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderManageServiceOrderDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderDetailArgs(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderDetailArgs = map[int16]string{
	1: "req",
}

type OrderManageServiceOrderDetailResult struct {
	Success *OrderDetailResp `thrift:"success,0,optional" frugal:"0,optional,OrderDetailResp" json:"success,omitempty"`
}

func NewOrderManageServiceOrderDetailResult() *OrderManageServiceOrderDetailResult {
	return &OrderManageServiceOrderDetailResult{}
}

func (p *OrderManageServiceOrderDetailResult) InitDefault() {
}

var OrderManageServiceOrderDetailResult_Success_DEFAULT *OrderDetailResp

func (p *OrderManageServiceOrderDetailResult) GetSuccess() (v *OrderDetailResp) {
	if !p.IsSetSuccess() {
		return OrderManageServiceOrderDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderManageServiceOrderDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderDetailResp)
}

func (p *OrderManageServiceOrderDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderManageServiceOrderDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderDetailResult(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderDetailResult = map[int16]string{
	0: "success",
}

type OrderManageServiceOrderStatusUpdateArgs struct {
	Req *OrderStatusUpdateReq `thrift:"req,1" frugal:"1,default,OrderStatusUpdateReq" json:"req"`
}

func NewOrderManageServiceOrderStatusUpdateArgs() *OrderManageServiceOrderStatusUpdateArgs {
	return &OrderManageServiceOrderStatusUpdateArgs{}
}

func (p *OrderManageServiceOrderStatusUpdateArgs) InitDefault() {
}

var OrderManageServiceOrderStatusUpdateArgs_Req_DEFAULT *OrderStatusUpdateReq

func (p *OrderManageServiceOrderStatusUpdateArgs) GetReq() (v *OrderStatusUpdateReq) {
	if !p.IsSetReq() {
		return OrderManageServiceOrderStatusUpdateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderManageServiceOrderStatusUpdateArgs) SetReq(val *OrderStatusUpdateReq) {
	p.Req = val
}

func (p *OrderManageServiceOrderStatusUpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderManageServiceOrderStatusUpdateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderStatusUpdateArgs(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderStatusUpdateArgs = map[int16]string{
	1: "req",
}

type OrderManageServiceOrderStatusUpdateResult struct {
	Success *OrderStatusUpdateResp `thrift:"success,0,optional" frugal:"0,optional,OrderStatusUpdateResp" json:"success,omitempty"`
}

func NewOrderManageServiceOrderStatusUpdateResult() *OrderManageServiceOrderStatusUpdateResult {
	return &OrderManageServiceOrderStatusUpdateResult{}
}

func (p *OrderManageServiceOrderStatusUpdateResult) InitDefault() {
}

var OrderManageServiceOrderStatusUpdateResult_Success_DEFAULT *OrderStatusUpdateResp

func (p *OrderManageServiceOrderStatusUpdateResult) GetSuccess() (v *OrderStatusUpdateResp) {
	if !p.IsSetSuccess() {
		return OrderManageServiceOrderStatusUpdateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderManageServiceOrderStatusUpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderStatusUpdateResp)
}

func (p *OrderManageServiceOrderStatusUpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderManageServiceOrderStatusUpdateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderManageServiceOrderStatusUpdateResult(%+v)", *p)
}

var fieldIDToName_OrderManageServiceOrderStatusUpdateResult = map[int16]string{
	0: "success",
}
