// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order_audit

import (
	"context"
	"fmt"
)

type AuditLogCreateReq struct {
	OrderNo      string  `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	Action       string  `thrift:"action,2" frugal:"2,default,string" json:"action"`
	OperatorId   int64   `thrift:"operatorId,3" frugal:"3,default,i64" json:"operatorId"`
	OperatorType string  `thrift:"operatorType,4" frugal:"4,default,string" json:"operatorType"`
	OperatorName string  `thrift:"operatorName,5" frugal:"5,default,string" json:"operatorName"`
	OperatorIp   string  `thrift:"operatorIp,6" frugal:"6,default,string" json:"operatorIp"`
	BeforeData   *string `thrift:"beforeData,7,optional" frugal:"7,optional,string" json:"beforeData,omitempty"`
	AfterData    *string `thrift:"afterData,8,optional" frugal:"8,optional,string" json:"afterData,omitempty"`
	Reason       *string `thrift:"reason,9,optional" frugal:"9,optional,string" json:"reason,omitempty"`
	Remark       *string `thrift:"remark,10,optional" frugal:"10,optional,string" json:"remark,omitempty"`
	UserAgent    string  `thrift:"userAgent,11" frugal:"11,default,string" json:"userAgent"`
	RequestId    string  `thrift:"requestId,12" frugal:"12,default,string" json:"requestId"`
}

func NewAuditLogCreateReq() *AuditLogCreateReq {
	return &AuditLogCreateReq{}
}

func (p *AuditLogCreateReq) InitDefault() {
}

func (p *AuditLogCreateReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *AuditLogCreateReq) GetAction() (v string) {
	return p.Action
}

func (p *AuditLogCreateReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *AuditLogCreateReq) GetOperatorType() (v string) {
	return p.OperatorType
}

func (p *AuditLogCreateReq) GetOperatorName() (v string) {
	return p.OperatorName
}

func (p *AuditLogCreateReq) GetOperatorIp() (v string) {
	return p.OperatorIp
}

var AuditLogCreateReq_BeforeData_DEFAULT string

func (p *AuditLogCreateReq) GetBeforeData() (v string) {
	if !p.IsSetBeforeData() {
		return AuditLogCreateReq_BeforeData_DEFAULT
	}
	return *p.BeforeData
}

var AuditLogCreateReq_AfterData_DEFAULT string

func (p *AuditLogCreateReq) GetAfterData() (v string) {
	if !p.IsSetAfterData() {
		return AuditLogCreateReq_AfterData_DEFAULT
	}
	return *p.AfterData
}

var AuditLogCreateReq_Reason_DEFAULT string

func (p *AuditLogCreateReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return AuditLogCreateReq_Reason_DEFAULT
	}
	return *p.Reason
}

var AuditLogCreateReq_Remark_DEFAULT string

func (p *AuditLogCreateReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return AuditLogCreateReq_Remark_DEFAULT
	}
	return *p.Remark
}

func (p *AuditLogCreateReq) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *AuditLogCreateReq) GetRequestId() (v string) {
	return p.RequestId
}
func (p *AuditLogCreateReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *AuditLogCreateReq) SetAction(val string) {
	p.Action = val
}
func (p *AuditLogCreateReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *AuditLogCreateReq) SetOperatorType(val string) {
	p.OperatorType = val
}
func (p *AuditLogCreateReq) SetOperatorName(val string) {
	p.OperatorName = val
}
func (p *AuditLogCreateReq) SetOperatorIp(val string) {
	p.OperatorIp = val
}
func (p *AuditLogCreateReq) SetBeforeData(val *string) {
	p.BeforeData = val
}
func (p *AuditLogCreateReq) SetAfterData(val *string) {
	p.AfterData = val
}
func (p *AuditLogCreateReq) SetReason(val *string) {
	p.Reason = val
}
func (p *AuditLogCreateReq) SetRemark(val *string) {
	p.Remark = val
}
func (p *AuditLogCreateReq) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *AuditLogCreateReq) SetRequestId(val string) {
	p.RequestId = val
}

func (p *AuditLogCreateReq) IsSetBeforeData() bool {
	return p.BeforeData != nil
}

func (p *AuditLogCreateReq) IsSetAfterData() bool {
	return p.AfterData != nil
}

func (p *AuditLogCreateReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *AuditLogCreateReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *AuditLogCreateReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogCreateReq(%+v)", *p)
}

var fieldIDToName_AuditLogCreateReq = map[int16]string{
	1:  "orderNo",
	2:  "action",
	3:  "operatorId",
	4:  "operatorType",
	5:  "operatorName",
	6:  "operatorIp",
	7:  "beforeData",
	8:  "afterData",
	9:  "reason",
	10: "remark",
	11: "userAgent",
	12: "requestId",
}

type AuditLogCreateResp struct {
	LogId   int64  `thrift:"logId,1" frugal:"1,default,i64" json:"logId"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Success bool   `thrift:"success,3" frugal:"3,default,bool" json:"success"`
}

func NewAuditLogCreateResp() *AuditLogCreateResp {
	return &AuditLogCreateResp{}
}

func (p *AuditLogCreateResp) InitDefault() {
}

func (p *AuditLogCreateResp) GetLogId() (v int64) {
	return p.LogId
}

func (p *AuditLogCreateResp) GetMessage() (v string) {
	return p.Message
}

func (p *AuditLogCreateResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AuditLogCreateResp) SetLogId(val int64) {
	p.LogId = val
}
func (p *AuditLogCreateResp) SetMessage(val string) {
	p.Message = val
}
func (p *AuditLogCreateResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AuditLogCreateResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogCreateResp(%+v)", *p)
}

var fieldIDToName_AuditLogCreateResp = map[int16]string{
	1: "logId",
	2: "message",
	3: "success",
}

type AuditLogQueryReq struct {
	OrderNo      *string `thrift:"orderNo,1,optional" frugal:"1,optional,string" json:"orderNo,omitempty"`
	Action       *string `thrift:"action,2,optional" frugal:"2,optional,string" json:"action,omitempty"`
	OperatorId   *int64  `thrift:"operatorId,3,optional" frugal:"3,optional,i64" json:"operatorId,omitempty"`
	OperatorType *string `thrift:"operatorType,4,optional" frugal:"4,optional,string" json:"operatorType,omitempty"`
	StartTime    *string `thrift:"startTime,5,optional" frugal:"5,optional,string" json:"startTime,omitempty"`
	EndTime      *string `thrift:"endTime,6,optional" frugal:"6,optional,string" json:"endTime,omitempty"`
	OperatorIp   *string `thrift:"operatorIp,7,optional" frugal:"7,optional,string" json:"operatorIp,omitempty"`
	Page         int32   `thrift:"page,8" frugal:"8,default,i32" json:"page"`
	PageSize     int32   `thrift:"pageSize,9" frugal:"9,default,i32" json:"pageSize"`
}

func NewAuditLogQueryReq() *AuditLogQueryReq {
	return &AuditLogQueryReq{}
}

func (p *AuditLogQueryReq) InitDefault() {
}

var AuditLogQueryReq_OrderNo_DEFAULT string

func (p *AuditLogQueryReq) GetOrderNo() (v string) {
	if !p.IsSetOrderNo() {
		return AuditLogQueryReq_OrderNo_DEFAULT
	}
	return *p.OrderNo
}

var AuditLogQueryReq_Action_DEFAULT string

func (p *AuditLogQueryReq) GetAction() (v string) {
	if !p.IsSetAction() {
		return AuditLogQueryReq_Action_DEFAULT
	}
	return *p.Action
}

var AuditLogQueryReq_OperatorId_DEFAULT int64

func (p *AuditLogQueryReq) GetOperatorId() (v int64) {
	if !p.IsSetOperatorId() {
		return AuditLogQueryReq_OperatorId_DEFAULT
	}
	return *p.OperatorId
}

var AuditLogQueryReq_OperatorType_DEFAULT string

func (p *AuditLogQueryReq) GetOperatorType() (v string) {
	if !p.IsSetOperatorType() {
		return AuditLogQueryReq_OperatorType_DEFAULT
	}
	return *p.OperatorType
}

var AuditLogQueryReq_StartTime_DEFAULT string

func (p *AuditLogQueryReq) GetStartTime() (v string) {
	if !p.IsSetStartTime() {
		return AuditLogQueryReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var AuditLogQueryReq_EndTime_DEFAULT string

func (p *AuditLogQueryReq) GetEndTime() (v string) {
	if !p.IsSetEndTime() {
		return AuditLogQueryReq_EndTime_DEFAULT
	}
	return *p.EndTime
}

var AuditLogQueryReq_OperatorIp_DEFAULT string

func (p *AuditLogQueryReq) GetOperatorIp() (v string) {
	if !p.IsSetOperatorIp() {
		return AuditLogQueryReq_OperatorIp_DEFAULT
	}
	return *p.OperatorIp
}

func (p *AuditLogQueryReq) GetPage() (v int32) {
	return p.Page
}

func (p *AuditLogQueryReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *AuditLogQueryReq) SetOrderNo(val *string) {
	p.OrderNo = val
}
func (p *AuditLogQueryReq) SetAction(val *string) {
	p.Action = val
}
func (p *AuditLogQueryReq) SetOperatorId(val *int64) {
	p.OperatorId = val
}
func (p *AuditLogQueryReq) SetOperatorType(val *string) {
	p.OperatorType = val
}
func (p *AuditLogQueryReq) SetStartTime(val *string) {
	p.StartTime = val
}
func (p *AuditLogQueryReq) SetEndTime(val *string) {
	p.EndTime = val
}
func (p *AuditLogQueryReq) SetOperatorIp(val *string) {
	p.OperatorIp = val
}
func (p *AuditLogQueryReq) SetPage(val int32) {
	p.Page = val
}
func (p *AuditLogQueryReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *AuditLogQueryReq) IsSetOrderNo() bool {
	return p.OrderNo != nil
}

func (p *AuditLogQueryReq) IsSetAction() bool {
	return p.Action != nil
}

func (p *AuditLogQueryReq) IsSetOperatorId() bool {
	return p.OperatorId != nil
}

func (p *AuditLogQueryReq) IsSetOperatorType() bool {
	return p.OperatorType != nil
}

func (p *AuditLogQueryReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *AuditLogQueryReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *AuditLogQueryReq) IsSetOperatorIp() bool {
	return p.OperatorIp != nil
}

func (p *AuditLogQueryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogQueryReq(%+v)", *p)
}

var fieldIDToName_AuditLogQueryReq = map[int16]string{
	1: "orderNo",
	2: "action",
	3: "operatorId",
	4: "operatorType",
	5: "startTime",
	6: "endTime",
	7: "operatorIp",
	8: "page",
	9: "pageSize",
}

type AuditLogInfo struct {
	LogId        int64  `thrift:"logId,1" frugal:"1,default,i64" json:"logId"`
	OrderNo      string `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	Action       string `thrift:"action,3" frugal:"3,default,string" json:"action"`
	OperatorId   int64  `thrift:"operatorId,4" frugal:"4,default,i64" json:"operatorId"`
	OperatorType string `thrift:"operatorType,5" frugal:"5,default,string" json:"operatorType"`
	OperatorName string `thrift:"operatorName,6" frugal:"6,default,string" json:"operatorName"`
	OperatorIp   string `thrift:"operatorIp,7" frugal:"7,default,string" json:"operatorIp"`
	BeforeData   string `thrift:"beforeData,8" frugal:"8,default,string" json:"beforeData"`
	AfterData    string `thrift:"afterData,9" frugal:"9,default,string" json:"afterData"`
	Reason       string `thrift:"reason,10" frugal:"10,default,string" json:"reason"`
	Remark       string `thrift:"remark,11" frugal:"11,default,string" json:"remark"`
	UserAgent    string `thrift:"userAgent,12" frugal:"12,default,string" json:"userAgent"`
	RequestId    string `thrift:"requestId,13" frugal:"13,default,string" json:"requestId"`
	CreatedAt    string `thrift:"createdAt,14" frugal:"14,default,string" json:"createdAt"`
}

func NewAuditLogInfo() *AuditLogInfo {
	return &AuditLogInfo{}
}

func (p *AuditLogInfo) InitDefault() {
}

func (p *AuditLogInfo) GetLogId() (v int64) {
	return p.LogId
}

func (p *AuditLogInfo) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *AuditLogInfo) GetAction() (v string) {
	return p.Action
}

func (p *AuditLogInfo) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *AuditLogInfo) GetOperatorType() (v string) {
	return p.OperatorType
}

func (p *AuditLogInfo) GetOperatorName() (v string) {
	return p.OperatorName
}

func (p *AuditLogInfo) GetOperatorIp() (v string) {
	return p.OperatorIp
}

func (p *AuditLogInfo) GetBeforeData() (v string) {
	return p.BeforeData
}

func (p *AuditLogInfo) GetAfterData() (v string) {
	return p.AfterData
}

func (p *AuditLogInfo) GetReason() (v string) {
	return p.Reason
}

func (p *AuditLogInfo) GetRemark() (v string) {
	return p.Remark
}

func (p *AuditLogInfo) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *AuditLogInfo) GetRequestId() (v string) {
	return p.RequestId
}

func (p *AuditLogInfo) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *AuditLogInfo) SetLogId(val int64) {
	p.LogId = val
}
func (p *AuditLogInfo) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *AuditLogInfo) SetAction(val string) {
	p.Action = val
}
func (p *AuditLogInfo) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *AuditLogInfo) SetOperatorType(val string) {
	p.OperatorType = val
}
func (p *AuditLogInfo) SetOperatorName(val string) {
	p.OperatorName = val
}
func (p *AuditLogInfo) SetOperatorIp(val string) {
	p.OperatorIp = val
}
func (p *AuditLogInfo) SetBeforeData(val string) {
	p.BeforeData = val
}
func (p *AuditLogInfo) SetAfterData(val string) {
	p.AfterData = val
}
func (p *AuditLogInfo) SetReason(val string) {
	p.Reason = val
}
func (p *AuditLogInfo) SetRemark(val string) {
	p.Remark = val
}
func (p *AuditLogInfo) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *AuditLogInfo) SetRequestId(val string) {
	p.RequestId = val
}
func (p *AuditLogInfo) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *AuditLogInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogInfo(%+v)", *p)
}

var fieldIDToName_AuditLogInfo = map[int16]string{
	1:  "logId",
	2:  "orderNo",
	3:  "action",
	4:  "operatorId",
	5:  "operatorType",
	6:  "operatorName",
	7:  "operatorIp",
	8:  "beforeData",
	9:  "afterData",
	10: "reason",
	11: "remark",
	12: "userAgent",
	13: "requestId",
	14: "createdAt",
}

type AuditLogQueryResp struct {
	Logs     []*AuditLogInfo `thrift:"logs,1" frugal:"1,default,list<AuditLogInfo>" json:"logs"`
	Total    int64           `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Page     int32           `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32           `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Message  string          `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success  bool            `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewAuditLogQueryResp() *AuditLogQueryResp {
	return &AuditLogQueryResp{}
}

func (p *AuditLogQueryResp) InitDefault() {
}

func (p *AuditLogQueryResp) GetLogs() (v []*AuditLogInfo) {
	return p.Logs
}

func (p *AuditLogQueryResp) GetTotal() (v int64) {
	return p.Total
}

func (p *AuditLogQueryResp) GetPage() (v int32) {
	return p.Page
}

func (p *AuditLogQueryResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *AuditLogQueryResp) GetMessage() (v string) {
	return p.Message
}

func (p *AuditLogQueryResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AuditLogQueryResp) SetLogs(val []*AuditLogInfo) {
	p.Logs = val
}
func (p *AuditLogQueryResp) SetTotal(val int64) {
	p.Total = val
}
func (p *AuditLogQueryResp) SetPage(val int32) {
	p.Page = val
}
func (p *AuditLogQueryResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *AuditLogQueryResp) SetMessage(val string) {
	p.Message = val
}
func (p *AuditLogQueryResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AuditLogQueryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogQueryResp(%+v)", *p)
}

var fieldIDToName_AuditLogQueryResp = map[int16]string{
	1: "logs",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "message",
	6: "success",
}

type AnomalyDetectionReq struct {
	UserId        *int64  `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	UserType      *string `thrift:"userType,2,optional" frugal:"2,optional,string" json:"userType,omitempty"`
	DetectionType *string `thrift:"detectionType,3,optional" frugal:"3,optional,string" json:"detectionType,omitempty"`
	StartTime     *string `thrift:"startTime,4,optional" frugal:"4,optional,string" json:"startTime,omitempty"`
	EndTime       *string `thrift:"endTime,5,optional" frugal:"5,optional,string" json:"endTime,omitempty"`
	Page          int32   `thrift:"page,6" frugal:"6,default,i32" json:"page"`
	PageSize      int32   `thrift:"pageSize,7" frugal:"7,default,i32" json:"pageSize"`
}

func NewAnomalyDetectionReq() *AnomalyDetectionReq {
	return &AnomalyDetectionReq{}
}

func (p *AnomalyDetectionReq) InitDefault() {
}

var AnomalyDetectionReq_UserId_DEFAULT int64

func (p *AnomalyDetectionReq) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return AnomalyDetectionReq_UserId_DEFAULT
	}
	return *p.UserId
}

var AnomalyDetectionReq_UserType_DEFAULT string

func (p *AnomalyDetectionReq) GetUserType() (v string) {
	if !p.IsSetUserType() {
		return AnomalyDetectionReq_UserType_DEFAULT
	}
	return *p.UserType
}

var AnomalyDetectionReq_DetectionType_DEFAULT string

func (p *AnomalyDetectionReq) GetDetectionType() (v string) {
	if !p.IsSetDetectionType() {
		return AnomalyDetectionReq_DetectionType_DEFAULT
	}
	return *p.DetectionType
}

var AnomalyDetectionReq_StartTime_DEFAULT string

func (p *AnomalyDetectionReq) GetStartTime() (v string) {
	if !p.IsSetStartTime() {
		return AnomalyDetectionReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var AnomalyDetectionReq_EndTime_DEFAULT string

func (p *AnomalyDetectionReq) GetEndTime() (v string) {
	if !p.IsSetEndTime() {
		return AnomalyDetectionReq_EndTime_DEFAULT
	}
	return *p.EndTime
}

func (p *AnomalyDetectionReq) GetPage() (v int32) {
	return p.Page
}

func (p *AnomalyDetectionReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *AnomalyDetectionReq) SetUserId(val *int64) {
	p.UserId = val
}
func (p *AnomalyDetectionReq) SetUserType(val *string) {
	p.UserType = val
}
func (p *AnomalyDetectionReq) SetDetectionType(val *string) {
	p.DetectionType = val
}
func (p *AnomalyDetectionReq) SetStartTime(val *string) {
	p.StartTime = val
}
func (p *AnomalyDetectionReq) SetEndTime(val *string) {
	p.EndTime = val
}
func (p *AnomalyDetectionReq) SetPage(val int32) {
	p.Page = val
}
func (p *AnomalyDetectionReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *AnomalyDetectionReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *AnomalyDetectionReq) IsSetUserType() bool {
	return p.UserType != nil
}

func (p *AnomalyDetectionReq) IsSetDetectionType() bool {
	return p.DetectionType != nil
}

func (p *AnomalyDetectionReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *AnomalyDetectionReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *AnomalyDetectionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnomalyDetectionReq(%+v)", *p)
}

var fieldIDToName_AnomalyDetectionReq = map[int16]string{
	1: "userId",
	2: "userType",
	3: "detectionType",
	4: "startTime",
	5: "endTime",
	6: "page",
	7: "pageSize",
}

type AnomalyInfo struct {
	AnomalyId       int64  `thrift:"anomalyId,1" frugal:"1,default,i64" json:"anomalyId"`
	UserId          int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	UserType        string `thrift:"userType,3" frugal:"3,default,string" json:"userType"`
	UserName        string `thrift:"userName,4" frugal:"4,default,string" json:"userName"`
	AnomalyType     string `thrift:"anomalyType,5" frugal:"5,default,string" json:"anomalyType"`
	Description     string `thrift:"description,6" frugal:"6,default,string" json:"description"`
	RiskLevel       string `thrift:"riskLevel,7" frugal:"7,default,string" json:"riskLevel"`
	OccurrenceCount int32  `thrift:"occurrenceCount,8" frugal:"8,default,i32" json:"occurrenceCount"`
	RelatedOrders   string `thrift:"relatedOrders,9" frugal:"9,default,string" json:"relatedOrders"`
	DetectedAt      string `thrift:"detectedAt,10" frugal:"10,default,string" json:"detectedAt"`
	Status          string `thrift:"status,11" frugal:"11,default,string" json:"status"`
	HandlerName     string `thrift:"handlerName,12" frugal:"12,default,string" json:"handlerName"`
	HandleResult_   string `thrift:"handleResult,13" frugal:"13,default,string" json:"handleResult"`
}

func NewAnomalyInfo() *AnomalyInfo {
	return &AnomalyInfo{}
}

func (p *AnomalyInfo) InitDefault() {
}

func (p *AnomalyInfo) GetAnomalyId() (v int64) {
	return p.AnomalyId
}

func (p *AnomalyInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *AnomalyInfo) GetUserType() (v string) {
	return p.UserType
}

func (p *AnomalyInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *AnomalyInfo) GetAnomalyType() (v string) {
	return p.AnomalyType
}

func (p *AnomalyInfo) GetDescription() (v string) {
	return p.Description
}

func (p *AnomalyInfo) GetRiskLevel() (v string) {
	return p.RiskLevel
}

func (p *AnomalyInfo) GetOccurrenceCount() (v int32) {
	return p.OccurrenceCount
}

func (p *AnomalyInfo) GetRelatedOrders() (v string) {
	return p.RelatedOrders
}

func (p *AnomalyInfo) GetDetectedAt() (v string) {
	return p.DetectedAt
}

func (p *AnomalyInfo) GetStatus() (v string) {
	return p.Status
}

func (p *AnomalyInfo) GetHandlerName() (v string) {
	return p.HandlerName
}

func (p *AnomalyInfo) GetHandleResult_() (v string) {
	return p.HandleResult_
}
func (p *AnomalyInfo) SetAnomalyId(val int64) {
	p.AnomalyId = val
}
func (p *AnomalyInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *AnomalyInfo) SetUserType(val string) {
	p.UserType = val
}
func (p *AnomalyInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *AnomalyInfo) SetAnomalyType(val string) {
	p.AnomalyType = val
}
func (p *AnomalyInfo) SetDescription(val string) {
	p.Description = val
}
func (p *AnomalyInfo) SetRiskLevel(val string) {
	p.RiskLevel = val
}
func (p *AnomalyInfo) SetOccurrenceCount(val int32) {
	p.OccurrenceCount = val
}
func (p *AnomalyInfo) SetRelatedOrders(val string) {
	p.RelatedOrders = val
}
func (p *AnomalyInfo) SetDetectedAt(val string) {
	p.DetectedAt = val
}
func (p *AnomalyInfo) SetStatus(val string) {
	p.Status = val
}
func (p *AnomalyInfo) SetHandlerName(val string) {
	p.HandlerName = val
}
func (p *AnomalyInfo) SetHandleResult_(val string) {
	p.HandleResult_ = val
}

func (p *AnomalyInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnomalyInfo(%+v)", *p)
}

var fieldIDToName_AnomalyInfo = map[int16]string{
	1:  "anomalyId",
	2:  "userId",
	3:  "userType",
	4:  "userName",
	5:  "anomalyType",
	6:  "description",
	7:  "riskLevel",
	8:  "occurrenceCount",
	9:  "relatedOrders",
	10: "detectedAt",
	11: "status",
	12: "handlerName",
	13: "handleResult",
}

type AnomalyDetectionResp struct {
	Anomalies []*AnomalyInfo `thrift:"anomalies,1" frugal:"1,default,list<AnomalyInfo>" json:"anomalies"`
	Total     int64          `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Page      int32          `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize  int32          `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Message   string         `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success   bool           `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewAnomalyDetectionResp() *AnomalyDetectionResp {
	return &AnomalyDetectionResp{}
}

func (p *AnomalyDetectionResp) InitDefault() {
}

func (p *AnomalyDetectionResp) GetAnomalies() (v []*AnomalyInfo) {
	return p.Anomalies
}

func (p *AnomalyDetectionResp) GetTotal() (v int64) {
	return p.Total
}

func (p *AnomalyDetectionResp) GetPage() (v int32) {
	return p.Page
}

func (p *AnomalyDetectionResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *AnomalyDetectionResp) GetMessage() (v string) {
	return p.Message
}

func (p *AnomalyDetectionResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AnomalyDetectionResp) SetAnomalies(val []*AnomalyInfo) {
	p.Anomalies = val
}
func (p *AnomalyDetectionResp) SetTotal(val int64) {
	p.Total = val
}
func (p *AnomalyDetectionResp) SetPage(val int32) {
	p.Page = val
}
func (p *AnomalyDetectionResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *AnomalyDetectionResp) SetMessage(val string) {
	p.Message = val
}
func (p *AnomalyDetectionResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AnomalyDetectionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnomalyDetectionResp(%+v)", *p)
}

var fieldIDToName_AnomalyDetectionResp = map[int16]string{
	1: "anomalies",
	2: "total",
	3: "page",
	4: "pageSize",
	5: "message",
	6: "success",
}

type MonitorStatsReq struct {
	TimeRange *string `thrift:"timeRange,1,optional" frugal:"1,optional,string" json:"timeRange,omitempty"`
	StatsType *string `thrift:"statsType,2,optional" frugal:"2,optional,string" json:"statsType,omitempty"`
}

func NewMonitorStatsReq() *MonitorStatsReq {
	return &MonitorStatsReq{}
}

func (p *MonitorStatsReq) InitDefault() {
}

var MonitorStatsReq_TimeRange_DEFAULT string

func (p *MonitorStatsReq) GetTimeRange() (v string) {
	if !p.IsSetTimeRange() {
		return MonitorStatsReq_TimeRange_DEFAULT
	}
	return *p.TimeRange
}

var MonitorStatsReq_StatsType_DEFAULT string

func (p *MonitorStatsReq) GetStatsType() (v string) {
	if !p.IsSetStatsType() {
		return MonitorStatsReq_StatsType_DEFAULT
	}
	return *p.StatsType
}
func (p *MonitorStatsReq) SetTimeRange(val *string) {
	p.TimeRange = val
}
func (p *MonitorStatsReq) SetStatsType(val *string) {
	p.StatsType = val
}

func (p *MonitorStatsReq) IsSetTimeRange() bool {
	return p.TimeRange != nil
}

func (p *MonitorStatsReq) IsSetStatsType() bool {
	return p.StatsType != nil
}

func (p *MonitorStatsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MonitorStatsReq(%+v)", *p)
}

var fieldIDToName_MonitorStatsReq = map[int16]string{
	1: "timeRange",
	2: "statsType",
}

type MonitorStatsResp struct {
	TotalOrders       int64            `thrift:"totalOrders,1" frugal:"1,default,i64" json:"totalOrders"`
	TodayOrders       int64            `thrift:"todayOrders,2" frugal:"2,default,i64" json:"todayOrders"`
	PendingOrders     int64            `thrift:"pendingOrders,3" frugal:"3,default,i64" json:"pendingOrders"`
	CompletedOrders   int64            `thrift:"completedOrders,4" frugal:"4,default,i64" json:"completedOrders"`
	CancelledOrders   int64            `thrift:"cancelledOrders,5" frugal:"5,default,i64" json:"cancelledOrders"`
	TotalAuditLogs    int64            `thrift:"totalAuditLogs,6" frugal:"6,default,i64" json:"totalAuditLogs"`
	TodayAuditLogs    int64            `thrift:"todayAuditLogs,7" frugal:"7,default,i64" json:"todayAuditLogs"`
	TotalAnomalies    int64            `thrift:"totalAnomalies,8" frugal:"8,default,i64" json:"totalAnomalies"`
	PendingAnomalies  int64            `thrift:"pendingAnomalies,9" frugal:"9,default,i64" json:"pendingAnomalies"`
	HighRiskAnomalies int64            `thrift:"highRiskAnomalies,10" frugal:"10,default,i64" json:"highRiskAnomalies"`
	AvgResponseTime   float64          `thrift:"avgResponseTime,11" frugal:"11,default,double" json:"avgResponseTime"`
	ActionStats       map[string]int64 `thrift:"actionStats,12" frugal:"12,default,map<string:i64>" json:"actionStats"`
	AnomalyStats      map[string]int64 `thrift:"anomalyStats,13" frugal:"13,default,map<string:i64>" json:"anomalyStats"`
	Message           string           `thrift:"message,14" frugal:"14,default,string" json:"message"`
	Success           bool             `thrift:"success,15" frugal:"15,default,bool" json:"success"`
}

func NewMonitorStatsResp() *MonitorStatsResp {
	return &MonitorStatsResp{}
}

func (p *MonitorStatsResp) InitDefault() {
}

func (p *MonitorStatsResp) GetTotalOrders() (v int64) {
	return p.TotalOrders
}

func (p *MonitorStatsResp) GetTodayOrders() (v int64) {
	return p.TodayOrders
}

func (p *MonitorStatsResp) GetPendingOrders() (v int64) {
	return p.PendingOrders
}

func (p *MonitorStatsResp) GetCompletedOrders() (v int64) {
	return p.CompletedOrders
}

func (p *MonitorStatsResp) GetCancelledOrders() (v int64) {
	return p.CancelledOrders
}

func (p *MonitorStatsResp) GetTotalAuditLogs() (v int64) {
	return p.TotalAuditLogs
}

func (p *MonitorStatsResp) GetTodayAuditLogs() (v int64) {
	return p.TodayAuditLogs
}

func (p *MonitorStatsResp) GetTotalAnomalies() (v int64) {
	return p.TotalAnomalies
}

func (p *MonitorStatsResp) GetPendingAnomalies() (v int64) {
	return p.PendingAnomalies
}

func (p *MonitorStatsResp) GetHighRiskAnomalies() (v int64) {
	return p.HighRiskAnomalies
}

func (p *MonitorStatsResp) GetAvgResponseTime() (v float64) {
	return p.AvgResponseTime
}

func (p *MonitorStatsResp) GetActionStats() (v map[string]int64) {
	return p.ActionStats
}

func (p *MonitorStatsResp) GetAnomalyStats() (v map[string]int64) {
	return p.AnomalyStats
}

func (p *MonitorStatsResp) GetMessage() (v string) {
	return p.Message
}

func (p *MonitorStatsResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *MonitorStatsResp) SetTotalOrders(val int64) {
	p.TotalOrders = val
}
func (p *MonitorStatsResp) SetTodayOrders(val int64) {
	p.TodayOrders = val
}
func (p *MonitorStatsResp) SetPendingOrders(val int64) {
	p.PendingOrders = val
}
func (p *MonitorStatsResp) SetCompletedOrders(val int64) {
	p.CompletedOrders = val
}
func (p *MonitorStatsResp) SetCancelledOrders(val int64) {
	p.CancelledOrders = val
}
func (p *MonitorStatsResp) SetTotalAuditLogs(val int64) {
	p.TotalAuditLogs = val
}
func (p *MonitorStatsResp) SetTodayAuditLogs(val int64) {
	p.TodayAuditLogs = val
}
func (p *MonitorStatsResp) SetTotalAnomalies(val int64) {
	p.TotalAnomalies = val
}
func (p *MonitorStatsResp) SetPendingAnomalies(val int64) {
	p.PendingAnomalies = val
}
func (p *MonitorStatsResp) SetHighRiskAnomalies(val int64) {
	p.HighRiskAnomalies = val
}
func (p *MonitorStatsResp) SetAvgResponseTime(val float64) {
	p.AvgResponseTime = val
}
func (p *MonitorStatsResp) SetActionStats(val map[string]int64) {
	p.ActionStats = val
}
func (p *MonitorStatsResp) SetAnomalyStats(val map[string]int64) {
	p.AnomalyStats = val
}
func (p *MonitorStatsResp) SetMessage(val string) {
	p.Message = val
}
func (p *MonitorStatsResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *MonitorStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MonitorStatsResp(%+v)", *p)
}

var fieldIDToName_MonitorStatsResp = map[int16]string{
	1:  "totalOrders",
	2:  "todayOrders",
	3:  "pendingOrders",
	4:  "completedOrders",
	5:  "cancelledOrders",
	6:  "totalAuditLogs",
	7:  "todayAuditLogs",
	8:  "totalAnomalies",
	9:  "pendingAnomalies",
	10: "highRiskAnomalies",
	11: "avgResponseTime",
	12: "actionStats",
	13: "anomalyStats",
	14: "message",
	15: "success",
}

type AnomalyHandleReq struct {
	AnomalyId     int64   `thrift:"anomalyId,1" frugal:"1,default,i64" json:"anomalyId"`
	HandlerId     int64   `thrift:"handlerId,2" frugal:"2,default,i64" json:"handlerId"`
	HandlerName   string  `thrift:"handlerName,3" frugal:"3,default,string" json:"handlerName"`
	HandleAction  string  `thrift:"handleAction,4" frugal:"4,default,string" json:"handleAction"`
	HandleResult_ string  `thrift:"handleResult,5" frugal:"5,default,string" json:"handleResult"`
	Remark        *string `thrift:"remark,6,optional" frugal:"6,optional,string" json:"remark,omitempty"`
}

func NewAnomalyHandleReq() *AnomalyHandleReq {
	return &AnomalyHandleReq{}
}

func (p *AnomalyHandleReq) InitDefault() {
}

func (p *AnomalyHandleReq) GetAnomalyId() (v int64) {
	return p.AnomalyId
}

func (p *AnomalyHandleReq) GetHandlerId() (v int64) {
	return p.HandlerId
}

func (p *AnomalyHandleReq) GetHandlerName() (v string) {
	return p.HandlerName
}

func (p *AnomalyHandleReq) GetHandleAction() (v string) {
	return p.HandleAction
}

func (p *AnomalyHandleReq) GetHandleResult_() (v string) {
	return p.HandleResult_
}

var AnomalyHandleReq_Remark_DEFAULT string

func (p *AnomalyHandleReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return AnomalyHandleReq_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *AnomalyHandleReq) SetAnomalyId(val int64) {
	p.AnomalyId = val
}
func (p *AnomalyHandleReq) SetHandlerId(val int64) {
	p.HandlerId = val
}
func (p *AnomalyHandleReq) SetHandlerName(val string) {
	p.HandlerName = val
}
func (p *AnomalyHandleReq) SetHandleAction(val string) {
	p.HandleAction = val
}
func (p *AnomalyHandleReq) SetHandleResult_(val string) {
	p.HandleResult_ = val
}
func (p *AnomalyHandleReq) SetRemark(val *string) {
	p.Remark = val
}

func (p *AnomalyHandleReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *AnomalyHandleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnomalyHandleReq(%+v)", *p)
}

var fieldIDToName_AnomalyHandleReq = map[int16]string{
	1: "anomalyId",
	2: "handlerId",
	3: "handlerName",
	4: "handleAction",
	5: "handleResult",
	6: "remark",
}

type AnomalyHandleResp struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
	Success bool   `thrift:"success,2" frugal:"2,default,bool" json:"success"`
}

func NewAnomalyHandleResp() *AnomalyHandleResp {
	return &AnomalyHandleResp{}
}

func (p *AnomalyHandleResp) InitDefault() {
}

func (p *AnomalyHandleResp) GetMessage() (v string) {
	return p.Message
}

func (p *AnomalyHandleResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AnomalyHandleResp) SetMessage(val string) {
	p.Message = val
}
func (p *AnomalyHandleResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AnomalyHandleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnomalyHandleResp(%+v)", *p)
}

var fieldIDToName_AnomalyHandleResp = map[int16]string{
	1: "message",
	2: "success",
}

type AuditLogExportReq struct {
	OrderNo      *string `thrift:"orderNo,1,optional" frugal:"1,optional,string" json:"orderNo,omitempty"`
	Action       *string `thrift:"action,2,optional" frugal:"2,optional,string" json:"action,omitempty"`
	OperatorId   *int64  `thrift:"operatorId,3,optional" frugal:"3,optional,i64" json:"operatorId,omitempty"`
	StartTime    *string `thrift:"startTime,4,optional" frugal:"4,optional,string" json:"startTime,omitempty"`
	EndTime      *string `thrift:"endTime,5,optional" frugal:"5,optional,string" json:"endTime,omitempty"`
	ExportFormat string  `thrift:"exportFormat,6" frugal:"6,default,string" json:"exportFormat"`
}

func NewAuditLogExportReq() *AuditLogExportReq {
	return &AuditLogExportReq{}
}

func (p *AuditLogExportReq) InitDefault() {
}

var AuditLogExportReq_OrderNo_DEFAULT string

func (p *AuditLogExportReq) GetOrderNo() (v string) {
	if !p.IsSetOrderNo() {
		return AuditLogExportReq_OrderNo_DEFAULT
	}
	return *p.OrderNo
}

var AuditLogExportReq_Action_DEFAULT string

func (p *AuditLogExportReq) GetAction() (v string) {
	if !p.IsSetAction() {
		return AuditLogExportReq_Action_DEFAULT
	}
	return *p.Action
}

var AuditLogExportReq_OperatorId_DEFAULT int64

func (p *AuditLogExportReq) GetOperatorId() (v int64) {
	if !p.IsSetOperatorId() {
		return AuditLogExportReq_OperatorId_DEFAULT
	}
	return *p.OperatorId
}

var AuditLogExportReq_StartTime_DEFAULT string

func (p *AuditLogExportReq) GetStartTime() (v string) {
	if !p.IsSetStartTime() {
		return AuditLogExportReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var AuditLogExportReq_EndTime_DEFAULT string

func (p *AuditLogExportReq) GetEndTime() (v string) {
	if !p.IsSetEndTime() {
		return AuditLogExportReq_EndTime_DEFAULT
	}
	return *p.EndTime
}

func (p *AuditLogExportReq) GetExportFormat() (v string) {
	return p.ExportFormat
}
func (p *AuditLogExportReq) SetOrderNo(val *string) {
	p.OrderNo = val
}
func (p *AuditLogExportReq) SetAction(val *string) {
	p.Action = val
}
func (p *AuditLogExportReq) SetOperatorId(val *int64) {
	p.OperatorId = val
}
func (p *AuditLogExportReq) SetStartTime(val *string) {
	p.StartTime = val
}
func (p *AuditLogExportReq) SetEndTime(val *string) {
	p.EndTime = val
}
func (p *AuditLogExportReq) SetExportFormat(val string) {
	p.ExportFormat = val
}

func (p *AuditLogExportReq) IsSetOrderNo() bool {
	return p.OrderNo != nil
}

func (p *AuditLogExportReq) IsSetAction() bool {
	return p.Action != nil
}

func (p *AuditLogExportReq) IsSetOperatorId() bool {
	return p.OperatorId != nil
}

func (p *AuditLogExportReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *AuditLogExportReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *AuditLogExportReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogExportReq(%+v)", *p)
}

var fieldIDToName_AuditLogExportReq = map[int16]string{
	1: "orderNo",
	2: "action",
	3: "operatorId",
	4: "startTime",
	5: "endTime",
	6: "exportFormat",
}

type AuditLogExportResp struct {
	DownloadUrl string `thrift:"downloadUrl,1" frugal:"1,default,string" json:"downloadUrl"`
	FileName    string `thrift:"fileName,2" frugal:"2,default,string" json:"fileName"`
	RecordCount int64  `thrift:"recordCount,3" frugal:"3,default,i64" json:"recordCount"`
	Message     string `thrift:"message,4" frugal:"4,default,string" json:"message"`
	Success     bool   `thrift:"success,5" frugal:"5,default,bool" json:"success"`
}

func NewAuditLogExportResp() *AuditLogExportResp {
	return &AuditLogExportResp{}
}

func (p *AuditLogExportResp) InitDefault() {
}

func (p *AuditLogExportResp) GetDownloadUrl() (v string) {
	return p.DownloadUrl
}

func (p *AuditLogExportResp) GetFileName() (v string) {
	return p.FileName
}

func (p *AuditLogExportResp) GetRecordCount() (v int64) {
	return p.RecordCount
}

func (p *AuditLogExportResp) GetMessage() (v string) {
	return p.Message
}

func (p *AuditLogExportResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AuditLogExportResp) SetDownloadUrl(val string) {
	p.DownloadUrl = val
}
func (p *AuditLogExportResp) SetFileName(val string) {
	p.FileName = val
}
func (p *AuditLogExportResp) SetRecordCount(val int64) {
	p.RecordCount = val
}
func (p *AuditLogExportResp) SetMessage(val string) {
	p.Message = val
}
func (p *AuditLogExportResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AuditLogExportResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuditLogExportResp(%+v)", *p)
}

var fieldIDToName_AuditLogExportResp = map[int16]string{
	1: "downloadUrl",
	2: "fileName",
	3: "recordCount",
	4: "message",
	5: "success",
}

type OrderAuditService interface {
	AuditLogCreate(ctx context.Context, req *AuditLogCreateReq) (r *AuditLogCreateResp, err error)

	AuditLogQuery(ctx context.Context, req *AuditLogQueryReq) (r *AuditLogQueryResp, err error)

	AnomalyDetection(ctx context.Context, req *AnomalyDetectionReq) (r *AnomalyDetectionResp, err error)

	MonitorStats(ctx context.Context, req *MonitorStatsReq) (r *MonitorStatsResp, err error)

	AnomalyHandle(ctx context.Context, req *AnomalyHandleReq) (r *AnomalyHandleResp, err error)

	AuditLogExport(ctx context.Context, req *AuditLogExportReq) (r *AuditLogExportResp, err error)
}

type OrderAuditServiceAuditLogCreateArgs struct {
	Req *AuditLogCreateReq `thrift:"req,1" frugal:"1,default,AuditLogCreateReq" json:"req"`
}

func NewOrderAuditServiceAuditLogCreateArgs() *OrderAuditServiceAuditLogCreateArgs {
	return &OrderAuditServiceAuditLogCreateArgs{}
}

func (p *OrderAuditServiceAuditLogCreateArgs) InitDefault() {
}

var OrderAuditServiceAuditLogCreateArgs_Req_DEFAULT *AuditLogCreateReq

func (p *OrderAuditServiceAuditLogCreateArgs) GetReq() (v *AuditLogCreateReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceAuditLogCreateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceAuditLogCreateArgs) SetReq(val *AuditLogCreateReq) {
	p.Req = val
}

func (p *OrderAuditServiceAuditLogCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceAuditLogCreateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogCreateArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogCreateArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceAuditLogCreateResult struct {
	Success *AuditLogCreateResp `thrift:"success,0,optional" frugal:"0,optional,AuditLogCreateResp" json:"success,omitempty"`
}

func NewOrderAuditServiceAuditLogCreateResult() *OrderAuditServiceAuditLogCreateResult {
	return &OrderAuditServiceAuditLogCreateResult{}
}

func (p *OrderAuditServiceAuditLogCreateResult) InitDefault() {
}

var OrderAuditServiceAuditLogCreateResult_Success_DEFAULT *AuditLogCreateResp

func (p *OrderAuditServiceAuditLogCreateResult) GetSuccess() (v *AuditLogCreateResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceAuditLogCreateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceAuditLogCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuditLogCreateResp)
}

func (p *OrderAuditServiceAuditLogCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceAuditLogCreateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogCreateResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogCreateResult = map[int16]string{
	0: "success",
}

type OrderAuditServiceAuditLogQueryArgs struct {
	Req *AuditLogQueryReq `thrift:"req,1" frugal:"1,default,AuditLogQueryReq" json:"req"`
}

func NewOrderAuditServiceAuditLogQueryArgs() *OrderAuditServiceAuditLogQueryArgs {
	return &OrderAuditServiceAuditLogQueryArgs{}
}

func (p *OrderAuditServiceAuditLogQueryArgs) InitDefault() {
}

var OrderAuditServiceAuditLogQueryArgs_Req_DEFAULT *AuditLogQueryReq

func (p *OrderAuditServiceAuditLogQueryArgs) GetReq() (v *AuditLogQueryReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceAuditLogQueryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceAuditLogQueryArgs) SetReq(val *AuditLogQueryReq) {
	p.Req = val
}

func (p *OrderAuditServiceAuditLogQueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceAuditLogQueryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogQueryArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogQueryArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceAuditLogQueryResult struct {
	Success *AuditLogQueryResp `thrift:"success,0,optional" frugal:"0,optional,AuditLogQueryResp" json:"success,omitempty"`
}

func NewOrderAuditServiceAuditLogQueryResult() *OrderAuditServiceAuditLogQueryResult {
	return &OrderAuditServiceAuditLogQueryResult{}
}

func (p *OrderAuditServiceAuditLogQueryResult) InitDefault() {
}

var OrderAuditServiceAuditLogQueryResult_Success_DEFAULT *AuditLogQueryResp

func (p *OrderAuditServiceAuditLogQueryResult) GetSuccess() (v *AuditLogQueryResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceAuditLogQueryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceAuditLogQueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuditLogQueryResp)
}

func (p *OrderAuditServiceAuditLogQueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceAuditLogQueryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogQueryResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogQueryResult = map[int16]string{
	0: "success",
}

type OrderAuditServiceAnomalyDetectionArgs struct {
	Req *AnomalyDetectionReq `thrift:"req,1" frugal:"1,default,AnomalyDetectionReq" json:"req"`
}

func NewOrderAuditServiceAnomalyDetectionArgs() *OrderAuditServiceAnomalyDetectionArgs {
	return &OrderAuditServiceAnomalyDetectionArgs{}
}

func (p *OrderAuditServiceAnomalyDetectionArgs) InitDefault() {
}

var OrderAuditServiceAnomalyDetectionArgs_Req_DEFAULT *AnomalyDetectionReq

func (p *OrderAuditServiceAnomalyDetectionArgs) GetReq() (v *AnomalyDetectionReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceAnomalyDetectionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceAnomalyDetectionArgs) SetReq(val *AnomalyDetectionReq) {
	p.Req = val
}

func (p *OrderAuditServiceAnomalyDetectionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceAnomalyDetectionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAnomalyDetectionArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAnomalyDetectionArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceAnomalyDetectionResult struct {
	Success *AnomalyDetectionResp `thrift:"success,0,optional" frugal:"0,optional,AnomalyDetectionResp" json:"success,omitempty"`
}

func NewOrderAuditServiceAnomalyDetectionResult() *OrderAuditServiceAnomalyDetectionResult {
	return &OrderAuditServiceAnomalyDetectionResult{}
}

func (p *OrderAuditServiceAnomalyDetectionResult) InitDefault() {
}

var OrderAuditServiceAnomalyDetectionResult_Success_DEFAULT *AnomalyDetectionResp

func (p *OrderAuditServiceAnomalyDetectionResult) GetSuccess() (v *AnomalyDetectionResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceAnomalyDetectionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceAnomalyDetectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnomalyDetectionResp)
}

func (p *OrderAuditServiceAnomalyDetectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceAnomalyDetectionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAnomalyDetectionResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAnomalyDetectionResult = map[int16]string{
	0: "success",
}

type OrderAuditServiceMonitorStatsArgs struct {
	Req *MonitorStatsReq `thrift:"req,1" frugal:"1,default,MonitorStatsReq" json:"req"`
}

func NewOrderAuditServiceMonitorStatsArgs() *OrderAuditServiceMonitorStatsArgs {
	return &OrderAuditServiceMonitorStatsArgs{}
}

func (p *OrderAuditServiceMonitorStatsArgs) InitDefault() {
}

var OrderAuditServiceMonitorStatsArgs_Req_DEFAULT *MonitorStatsReq

func (p *OrderAuditServiceMonitorStatsArgs) GetReq() (v *MonitorStatsReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceMonitorStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceMonitorStatsArgs) SetReq(val *MonitorStatsReq) {
	p.Req = val
}

func (p *OrderAuditServiceMonitorStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceMonitorStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceMonitorStatsArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceMonitorStatsArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceMonitorStatsResult struct {
	Success *MonitorStatsResp `thrift:"success,0,optional" frugal:"0,optional,MonitorStatsResp" json:"success,omitempty"`
}

func NewOrderAuditServiceMonitorStatsResult() *OrderAuditServiceMonitorStatsResult {
	return &OrderAuditServiceMonitorStatsResult{}
}

func (p *OrderAuditServiceMonitorStatsResult) InitDefault() {
}

var OrderAuditServiceMonitorStatsResult_Success_DEFAULT *MonitorStatsResp

func (p *OrderAuditServiceMonitorStatsResult) GetSuccess() (v *MonitorStatsResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceMonitorStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceMonitorStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*MonitorStatsResp)
}

func (p *OrderAuditServiceMonitorStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceMonitorStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceMonitorStatsResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceMonitorStatsResult = map[int16]string{
	0: "success",
}

type OrderAuditServiceAnomalyHandleArgs struct {
	Req *AnomalyHandleReq `thrift:"req,1" frugal:"1,default,AnomalyHandleReq" json:"req"`
}

func NewOrderAuditServiceAnomalyHandleArgs() *OrderAuditServiceAnomalyHandleArgs {
	return &OrderAuditServiceAnomalyHandleArgs{}
}

func (p *OrderAuditServiceAnomalyHandleArgs) InitDefault() {
}

var OrderAuditServiceAnomalyHandleArgs_Req_DEFAULT *AnomalyHandleReq

func (p *OrderAuditServiceAnomalyHandleArgs) GetReq() (v *AnomalyHandleReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceAnomalyHandleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceAnomalyHandleArgs) SetReq(val *AnomalyHandleReq) {
	p.Req = val
}

func (p *OrderAuditServiceAnomalyHandleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceAnomalyHandleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAnomalyHandleArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAnomalyHandleArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceAnomalyHandleResult struct {
	Success *AnomalyHandleResp `thrift:"success,0,optional" frugal:"0,optional,AnomalyHandleResp" json:"success,omitempty"`
}

func NewOrderAuditServiceAnomalyHandleResult() *OrderAuditServiceAnomalyHandleResult {
	return &OrderAuditServiceAnomalyHandleResult{}
}

func (p *OrderAuditServiceAnomalyHandleResult) InitDefault() {
}

var OrderAuditServiceAnomalyHandleResult_Success_DEFAULT *AnomalyHandleResp

func (p *OrderAuditServiceAnomalyHandleResult) GetSuccess() (v *AnomalyHandleResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceAnomalyHandleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceAnomalyHandleResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnomalyHandleResp)
}

func (p *OrderAuditServiceAnomalyHandleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceAnomalyHandleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAnomalyHandleResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAnomalyHandleResult = map[int16]string{
	0: "success",
}

type OrderAuditServiceAuditLogExportArgs struct {
	Req *AuditLogExportReq `thrift:"req,1" frugal:"1,default,AuditLogExportReq" json:"req"`
}

func NewOrderAuditServiceAuditLogExportArgs() *OrderAuditServiceAuditLogExportArgs {
	return &OrderAuditServiceAuditLogExportArgs{}
}

func (p *OrderAuditServiceAuditLogExportArgs) InitDefault() {
}

var OrderAuditServiceAuditLogExportArgs_Req_DEFAULT *AuditLogExportReq

func (p *OrderAuditServiceAuditLogExportArgs) GetReq() (v *AuditLogExportReq) {
	if !p.IsSetReq() {
		return OrderAuditServiceAuditLogExportArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderAuditServiceAuditLogExportArgs) SetReq(val *AuditLogExportReq) {
	p.Req = val
}

func (p *OrderAuditServiceAuditLogExportArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderAuditServiceAuditLogExportArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogExportArgs(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogExportArgs = map[int16]string{
	1: "req",
}

type OrderAuditServiceAuditLogExportResult struct {
	Success *AuditLogExportResp `thrift:"success,0,optional" frugal:"0,optional,AuditLogExportResp" json:"success,omitempty"`
}

func NewOrderAuditServiceAuditLogExportResult() *OrderAuditServiceAuditLogExportResult {
	return &OrderAuditServiceAuditLogExportResult{}
}

func (p *OrderAuditServiceAuditLogExportResult) InitDefault() {
}

var OrderAuditServiceAuditLogExportResult_Success_DEFAULT *AuditLogExportResp

func (p *OrderAuditServiceAuditLogExportResult) GetSuccess() (v *AuditLogExportResp) {
	if !p.IsSetSuccess() {
		return OrderAuditServiceAuditLogExportResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderAuditServiceAuditLogExportResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuditLogExportResp)
}

func (p *OrderAuditServiceAuditLogExportResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderAuditServiceAuditLogExportResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderAuditServiceAuditLogExportResult(%+v)", *p)
}

var fieldIDToName_OrderAuditServiceAuditLogExportResult = map[int16]string{
	0: "success",
}
