// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package upload

import (
	"context"
	"fmt"
)

type ImageUploadReq struct {
	FileName   string  `thrift:"fileName,1" frugal:"1,default,string" json:"fileName"`
	FileData   []byte  `thrift:"fileData,2" frugal:"2,default,binary" json:"fileData"`
	FileSize   int64   `thrift:"fileSize,3" frugal:"3,default,i64" json:"fileSize"`
	FileType   string  `thrift:"fileType,4" frugal:"4,default,string" json:"fileType"`
	UploadType *string `thrift:"uploadType,5,optional" frugal:"5,optional,string" json:"uploadType,omitempty"`
}

func NewImageUploadReq() *ImageUploadReq {
	return &ImageUploadReq{}
}

func (p *ImageUploadReq) InitDefault() {
}

func (p *ImageUploadReq) GetFileName() (v string) {
	return p.FileName
}

func (p *ImageUploadReq) GetFileData() (v []byte) {
	return p.FileData
}

func (p *ImageUploadReq) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *ImageUploadReq) GetFileType() (v string) {
	return p.FileType
}

var ImageUploadReq_UploadType_DEFAULT string

func (p *ImageUploadReq) GetUploadType() (v string) {
	if !p.IsSetUploadType() {
		return ImageUploadReq_UploadType_DEFAULT
	}
	return *p.UploadType
}
func (p *ImageUploadReq) SetFileName(val string) {
	p.FileName = val
}
func (p *ImageUploadReq) SetFileData(val []byte) {
	p.FileData = val
}
func (p *ImageUploadReq) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *ImageUploadReq) SetFileType(val string) {
	p.FileType = val
}
func (p *ImageUploadReq) SetUploadType(val *string) {
	p.UploadType = val
}

func (p *ImageUploadReq) IsSetUploadType() bool {
	return p.UploadType != nil
}

func (p *ImageUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageUploadReq(%+v)", *p)
}

var fieldIDToName_ImageUploadReq = map[int16]string{
	1: "fileName",
	2: "fileData",
	3: "fileSize",
	4: "fileType",
	5: "uploadType",
}

type ImageUploadResp struct {
	FileURL  string `thrift:"fileURL,1" frugal:"1,default,string" json:"fileURL"`
	FileName string `thrift:"fileName,2" frugal:"2,default,string" json:"fileName"`
	FileSize int64  `thrift:"fileSize,3" frugal:"3,default,i64" json:"fileSize"`
	Message  string `thrift:"message,4" frugal:"4,default,string" json:"message"`
	Success  bool   `thrift:"success,5" frugal:"5,default,bool" json:"success"`
}

func NewImageUploadResp() *ImageUploadResp {
	return &ImageUploadResp{}
}

func (p *ImageUploadResp) InitDefault() {
}

func (p *ImageUploadResp) GetFileURL() (v string) {
	return p.FileURL
}

func (p *ImageUploadResp) GetFileName() (v string) {
	return p.FileName
}

func (p *ImageUploadResp) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *ImageUploadResp) GetMessage() (v string) {
	return p.Message
}

func (p *ImageUploadResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *ImageUploadResp) SetFileURL(val string) {
	p.FileURL = val
}
func (p *ImageUploadResp) SetFileName(val string) {
	p.FileName = val
}
func (p *ImageUploadResp) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *ImageUploadResp) SetMessage(val string) {
	p.Message = val
}
func (p *ImageUploadResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *ImageUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageUploadResp(%+v)", *p)
}

var fieldIDToName_ImageUploadResp = map[int16]string{
	1: "fileURL",
	2: "fileName",
	3: "fileSize",
	4: "message",
	5: "success",
}

type ImageDeleteReq struct {
	FileURL    string  `thrift:"fileURL,1" frugal:"1,default,string" json:"fileURL"`
	DeleteType *string `thrift:"deleteType,2,optional" frugal:"2,optional,string" json:"deleteType,omitempty"`
}

func NewImageDeleteReq() *ImageDeleteReq {
	return &ImageDeleteReq{}
}

func (p *ImageDeleteReq) InitDefault() {
}

func (p *ImageDeleteReq) GetFileURL() (v string) {
	return p.FileURL
}

var ImageDeleteReq_DeleteType_DEFAULT string

func (p *ImageDeleteReq) GetDeleteType() (v string) {
	if !p.IsSetDeleteType() {
		return ImageDeleteReq_DeleteType_DEFAULT
	}
	return *p.DeleteType
}
func (p *ImageDeleteReq) SetFileURL(val string) {
	p.FileURL = val
}
func (p *ImageDeleteReq) SetDeleteType(val *string) {
	p.DeleteType = val
}

func (p *ImageDeleteReq) IsSetDeleteType() bool {
	return p.DeleteType != nil
}

func (p *ImageDeleteReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageDeleteReq(%+v)", *p)
}

var fieldIDToName_ImageDeleteReq = map[int16]string{
	1: "fileURL",
	2: "deleteType",
}

type ImageDeleteResp struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
	Success bool   `thrift:"success,2" frugal:"2,default,bool" json:"success"`
}

func NewImageDeleteResp() *ImageDeleteResp {
	return &ImageDeleteResp{}
}

func (p *ImageDeleteResp) InitDefault() {
}

func (p *ImageDeleteResp) GetMessage() (v string) {
	return p.Message
}

func (p *ImageDeleteResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *ImageDeleteResp) SetMessage(val string) {
	p.Message = val
}
func (p *ImageDeleteResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *ImageDeleteResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageDeleteResp(%+v)", *p)
}

var fieldIDToName_ImageDeleteResp = map[int16]string{
	1: "message",
	2: "success",
}

type BatchImageUploadReq struct {
	Images []*ImageUploadReq `thrift:"images,1" frugal:"1,default,list<ImageUploadReq>" json:"images"`
}

func NewBatchImageUploadReq() *BatchImageUploadReq {
	return &BatchImageUploadReq{}
}

func (p *BatchImageUploadReq) InitDefault() {
}

func (p *BatchImageUploadReq) GetImages() (v []*ImageUploadReq) {
	return p.Images
}
func (p *BatchImageUploadReq) SetImages(val []*ImageUploadReq) {
	p.Images = val
}

func (p *BatchImageUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchImageUploadReq(%+v)", *p)
}

var fieldIDToName_BatchImageUploadReq = map[int16]string{
	1: "images",
}

type BatchUploadResult_ struct {
	FileName string `thrift:"fileName,1" frugal:"1,default,string" json:"fileName"`
	FileURL  string `thrift:"fileURL,2" frugal:"2,default,string" json:"fileURL"`
	Success  bool   `thrift:"success,3" frugal:"3,default,bool" json:"success"`
	Message  string `thrift:"message,4" frugal:"4,default,string" json:"message"`
}

func NewBatchUploadResult_() *BatchUploadResult_ {
	return &BatchUploadResult_{}
}

func (p *BatchUploadResult_) InitDefault() {
}

func (p *BatchUploadResult_) GetFileName() (v string) {
	return p.FileName
}

func (p *BatchUploadResult_) GetFileURL() (v string) {
	return p.FileURL
}

func (p *BatchUploadResult_) GetSuccess() (v bool) {
	return p.Success
}

func (p *BatchUploadResult_) GetMessage() (v string) {
	return p.Message
}
func (p *BatchUploadResult_) SetFileName(val string) {
	p.FileName = val
}
func (p *BatchUploadResult_) SetFileURL(val string) {
	p.FileURL = val
}
func (p *BatchUploadResult_) SetSuccess(val bool) {
	p.Success = val
}
func (p *BatchUploadResult_) SetMessage(val string) {
	p.Message = val
}

func (p *BatchUploadResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchUploadResult_(%+v)", *p)
}

var fieldIDToName_BatchUploadResult_ = map[int16]string{
	1: "fileName",
	2: "fileURL",
	3: "success",
	4: "message",
}

type BatchImageUploadResp struct {
	Results      []*BatchUploadResult_ `thrift:"results,1" frugal:"1,default,list<BatchUploadResult_>" json:"results"`
	SuccessCount int32                 `thrift:"successCount,2" frugal:"2,default,i32" json:"successCount"`
	FailCount    int32                 `thrift:"failCount,3" frugal:"3,default,i32" json:"failCount"`
	Message      string                `thrift:"message,4" frugal:"4,default,string" json:"message"`
	Success      bool                  `thrift:"success,5" frugal:"5,default,bool" json:"success"`
}

func NewBatchImageUploadResp() *BatchImageUploadResp {
	return &BatchImageUploadResp{}
}

func (p *BatchImageUploadResp) InitDefault() {
}

func (p *BatchImageUploadResp) GetResults() (v []*BatchUploadResult_) {
	return p.Results
}

func (p *BatchImageUploadResp) GetSuccessCount() (v int32) {
	return p.SuccessCount
}

func (p *BatchImageUploadResp) GetFailCount() (v int32) {
	return p.FailCount
}

func (p *BatchImageUploadResp) GetMessage() (v string) {
	return p.Message
}

func (p *BatchImageUploadResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *BatchImageUploadResp) SetResults(val []*BatchUploadResult_) {
	p.Results = val
}
func (p *BatchImageUploadResp) SetSuccessCount(val int32) {
	p.SuccessCount = val
}
func (p *BatchImageUploadResp) SetFailCount(val int32) {
	p.FailCount = val
}
func (p *BatchImageUploadResp) SetMessage(val string) {
	p.Message = val
}
func (p *BatchImageUploadResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *BatchImageUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchImageUploadResp(%+v)", *p)
}

var fieldIDToName_BatchImageUploadResp = map[int16]string{
	1: "results",
	2: "successCount",
	3: "failCount",
	4: "message",
	5: "success",
}

type ImageInfoReq struct {
	FileURL string `thrift:"fileURL,1" frugal:"1,default,string" json:"fileURL"`
}

func NewImageInfoReq() *ImageInfoReq {
	return &ImageInfoReq{}
}

func (p *ImageInfoReq) InitDefault() {
}

func (p *ImageInfoReq) GetFileURL() (v string) {
	return p.FileURL
}
func (p *ImageInfoReq) SetFileURL(val string) {
	p.FileURL = val
}

func (p *ImageInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageInfoReq(%+v)", *p)
}

var fieldIDToName_ImageInfoReq = map[int16]string{
	1: "fileURL",
}

type ImageInfoResp struct {
	FileName   string `thrift:"fileName,1" frugal:"1,default,string" json:"fileName"`
	FileSize   int64  `thrift:"fileSize,2" frugal:"2,default,i64" json:"fileSize"`
	FileType   string `thrift:"fileType,3" frugal:"3,default,string" json:"fileType"`
	UploadTime string `thrift:"uploadTime,4" frugal:"4,default,string" json:"uploadTime"`
	Message    string `thrift:"message,5" frugal:"5,default,string" json:"message"`
	Success    bool   `thrift:"success,6" frugal:"6,default,bool" json:"success"`
}

func NewImageInfoResp() *ImageInfoResp {
	return &ImageInfoResp{}
}

func (p *ImageInfoResp) InitDefault() {
}

func (p *ImageInfoResp) GetFileName() (v string) {
	return p.FileName
}

func (p *ImageInfoResp) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *ImageInfoResp) GetFileType() (v string) {
	return p.FileType
}

func (p *ImageInfoResp) GetUploadTime() (v string) {
	return p.UploadTime
}

func (p *ImageInfoResp) GetMessage() (v string) {
	return p.Message
}

func (p *ImageInfoResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *ImageInfoResp) SetFileName(val string) {
	p.FileName = val
}
func (p *ImageInfoResp) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *ImageInfoResp) SetFileType(val string) {
	p.FileType = val
}
func (p *ImageInfoResp) SetUploadTime(val string) {
	p.UploadTime = val
}
func (p *ImageInfoResp) SetMessage(val string) {
	p.Message = val
}
func (p *ImageInfoResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *ImageInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ImageInfoResp(%+v)", *p)
}

var fieldIDToName_ImageInfoResp = map[int16]string{
	1: "fileName",
	2: "fileSize",
	3: "fileType",
	4: "uploadTime",
	5: "message",
	6: "success",
}

type UploadService interface {
	ImageUpload(ctx context.Context, req *ImageUploadReq) (r *ImageUploadResp, err error)

	ImageDelete(ctx context.Context, req *ImageDeleteReq) (r *ImageDeleteResp, err error)

	BatchImageUpload(ctx context.Context, req *BatchImageUploadReq) (r *BatchImageUploadResp, err error)

	ImageInfo(ctx context.Context, req *ImageInfoReq) (r *ImageInfoResp, err error)
}

type UploadServiceImageUploadArgs struct {
	Req *ImageUploadReq `thrift:"req,1" frugal:"1,default,ImageUploadReq" json:"req"`
}

func NewUploadServiceImageUploadArgs() *UploadServiceImageUploadArgs {
	return &UploadServiceImageUploadArgs{}
}

func (p *UploadServiceImageUploadArgs) InitDefault() {
}

var UploadServiceImageUploadArgs_Req_DEFAULT *ImageUploadReq

func (p *UploadServiceImageUploadArgs) GetReq() (v *ImageUploadReq) {
	if !p.IsSetReq() {
		return UploadServiceImageUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UploadServiceImageUploadArgs) SetReq(val *ImageUploadReq) {
	p.Req = val
}

func (p *UploadServiceImageUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UploadServiceImageUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageUploadArgs(%+v)", *p)
}

var fieldIDToName_UploadServiceImageUploadArgs = map[int16]string{
	1: "req",
}

type UploadServiceImageUploadResult struct {
	Success *ImageUploadResp `thrift:"success,0,optional" frugal:"0,optional,ImageUploadResp" json:"success,omitempty"`
}

func NewUploadServiceImageUploadResult() *UploadServiceImageUploadResult {
	return &UploadServiceImageUploadResult{}
}

func (p *UploadServiceImageUploadResult) InitDefault() {
}

var UploadServiceImageUploadResult_Success_DEFAULT *ImageUploadResp

func (p *UploadServiceImageUploadResult) GetSuccess() (v *ImageUploadResp) {
	if !p.IsSetSuccess() {
		return UploadServiceImageUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UploadServiceImageUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*ImageUploadResp)
}

func (p *UploadServiceImageUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UploadServiceImageUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageUploadResult(%+v)", *p)
}

var fieldIDToName_UploadServiceImageUploadResult = map[int16]string{
	0: "success",
}

type UploadServiceImageDeleteArgs struct {
	Req *ImageDeleteReq `thrift:"req,1" frugal:"1,default,ImageDeleteReq" json:"req"`
}

func NewUploadServiceImageDeleteArgs() *UploadServiceImageDeleteArgs {
	return &UploadServiceImageDeleteArgs{}
}

func (p *UploadServiceImageDeleteArgs) InitDefault() {
}

var UploadServiceImageDeleteArgs_Req_DEFAULT *ImageDeleteReq

func (p *UploadServiceImageDeleteArgs) GetReq() (v *ImageDeleteReq) {
	if !p.IsSetReq() {
		return UploadServiceImageDeleteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UploadServiceImageDeleteArgs) SetReq(val *ImageDeleteReq) {
	p.Req = val
}

func (p *UploadServiceImageDeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UploadServiceImageDeleteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageDeleteArgs(%+v)", *p)
}

var fieldIDToName_UploadServiceImageDeleteArgs = map[int16]string{
	1: "req",
}

type UploadServiceImageDeleteResult struct {
	Success *ImageDeleteResp `thrift:"success,0,optional" frugal:"0,optional,ImageDeleteResp" json:"success,omitempty"`
}

func NewUploadServiceImageDeleteResult() *UploadServiceImageDeleteResult {
	return &UploadServiceImageDeleteResult{}
}

func (p *UploadServiceImageDeleteResult) InitDefault() {
}

var UploadServiceImageDeleteResult_Success_DEFAULT *ImageDeleteResp

func (p *UploadServiceImageDeleteResult) GetSuccess() (v *ImageDeleteResp) {
	if !p.IsSetSuccess() {
		return UploadServiceImageDeleteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UploadServiceImageDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*ImageDeleteResp)
}

func (p *UploadServiceImageDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UploadServiceImageDeleteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageDeleteResult(%+v)", *p)
}

var fieldIDToName_UploadServiceImageDeleteResult = map[int16]string{
	0: "success",
}

type UploadServiceBatchImageUploadArgs struct {
	Req *BatchImageUploadReq `thrift:"req,1" frugal:"1,default,BatchImageUploadReq" json:"req"`
}

func NewUploadServiceBatchImageUploadArgs() *UploadServiceBatchImageUploadArgs {
	return &UploadServiceBatchImageUploadArgs{}
}

func (p *UploadServiceBatchImageUploadArgs) InitDefault() {
}

var UploadServiceBatchImageUploadArgs_Req_DEFAULT *BatchImageUploadReq

func (p *UploadServiceBatchImageUploadArgs) GetReq() (v *BatchImageUploadReq) {
	if !p.IsSetReq() {
		return UploadServiceBatchImageUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UploadServiceBatchImageUploadArgs) SetReq(val *BatchImageUploadReq) {
	p.Req = val
}

func (p *UploadServiceBatchImageUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UploadServiceBatchImageUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceBatchImageUploadArgs(%+v)", *p)
}

var fieldIDToName_UploadServiceBatchImageUploadArgs = map[int16]string{
	1: "req",
}

type UploadServiceBatchImageUploadResult struct {
	Success *BatchImageUploadResp `thrift:"success,0,optional" frugal:"0,optional,BatchImageUploadResp" json:"success,omitempty"`
}

func NewUploadServiceBatchImageUploadResult() *UploadServiceBatchImageUploadResult {
	return &UploadServiceBatchImageUploadResult{}
}

func (p *UploadServiceBatchImageUploadResult) InitDefault() {
}

var UploadServiceBatchImageUploadResult_Success_DEFAULT *BatchImageUploadResp

func (p *UploadServiceBatchImageUploadResult) GetSuccess() (v *BatchImageUploadResp) {
	if !p.IsSetSuccess() {
		return UploadServiceBatchImageUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UploadServiceBatchImageUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchImageUploadResp)
}

func (p *UploadServiceBatchImageUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UploadServiceBatchImageUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceBatchImageUploadResult(%+v)", *p)
}

var fieldIDToName_UploadServiceBatchImageUploadResult = map[int16]string{
	0: "success",
}

type UploadServiceImageInfoArgs struct {
	Req *ImageInfoReq `thrift:"req,1" frugal:"1,default,ImageInfoReq" json:"req"`
}

func NewUploadServiceImageInfoArgs() *UploadServiceImageInfoArgs {
	return &UploadServiceImageInfoArgs{}
}

func (p *UploadServiceImageInfoArgs) InitDefault() {
}

var UploadServiceImageInfoArgs_Req_DEFAULT *ImageInfoReq

func (p *UploadServiceImageInfoArgs) GetReq() (v *ImageInfoReq) {
	if !p.IsSetReq() {
		return UploadServiceImageInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UploadServiceImageInfoArgs) SetReq(val *ImageInfoReq) {
	p.Req = val
}

func (p *UploadServiceImageInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UploadServiceImageInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageInfoArgs(%+v)", *p)
}

var fieldIDToName_UploadServiceImageInfoArgs = map[int16]string{
	1: "req",
}

type UploadServiceImageInfoResult struct {
	Success *ImageInfoResp `thrift:"success,0,optional" frugal:"0,optional,ImageInfoResp" json:"success,omitempty"`
}

func NewUploadServiceImageInfoResult() *UploadServiceImageInfoResult {
	return &UploadServiceImageInfoResult{}
}

func (p *UploadServiceImageInfoResult) InitDefault() {
}

var UploadServiceImageInfoResult_Success_DEFAULT *ImageInfoResp

func (p *UploadServiceImageInfoResult) GetSuccess() (v *ImageInfoResp) {
	if !p.IsSetSuccess() {
		return UploadServiceImageInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UploadServiceImageInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*ImageInfoResp)
}

func (p *UploadServiceImageInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UploadServiceImageInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadServiceImageInfoResult(%+v)", *p)
}

var fieldIDToName_UploadServiceImageInfoResult = map[int16]string{
	0: "success",
}
