// Code generated by Kitex v0.15.4. DO NOT EDIT.

package refundservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	refund "group/kitex_gen/car/refund"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RefundApply(ctx context.Context, req *refund.RefundApplyReq, callOptions ...callopt.Option) (r *refund.RefundApplyResp, err error)
	RefundAudit(ctx context.Context, req *refund.RefundAuditReq, callOptions ...callopt.Option) (r *refund.RefundAuditResp, err error)
	BatchRefund(ctx context.Context, req *refund.BatchRefundReq, callOptions ...callopt.Option) (r *refund.BatchRefundResp, err error)
	RefundStatusQuery(ctx context.Context, req *refund.RefundStatusQueryReq, callOptions ...callopt.Option) (r *refund.RefundStatusQueryResp, err error)
	RefundRecordQuery(ctx context.Context, req *refund.RefundRecordQueryReq, callOptions ...callopt.Option) (r *refund.RefundRecordQueryResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRefundServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRefundServiceClient struct {
	*kClient
}

func (p *kRefundServiceClient) RefundApply(ctx context.Context, req *refund.RefundApplyReq, callOptions ...callopt.Option) (r *refund.RefundApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundApply(ctx, req)
}

func (p *kRefundServiceClient) RefundAudit(ctx context.Context, req *refund.RefundAuditReq, callOptions ...callopt.Option) (r *refund.RefundAuditResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundAudit(ctx, req)
}

func (p *kRefundServiceClient) BatchRefund(ctx context.Context, req *refund.BatchRefundReq, callOptions ...callopt.Option) (r *refund.BatchRefundResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchRefund(ctx, req)
}

func (p *kRefundServiceClient) RefundStatusQuery(ctx context.Context, req *refund.RefundStatusQueryReq, callOptions ...callopt.Option) (r *refund.RefundStatusQueryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundStatusQuery(ctx, req)
}

func (p *kRefundServiceClient) RefundRecordQuery(ctx context.Context, req *refund.RefundRecordQueryReq, callOptions ...callopt.Option) (r *refund.RefundRecordQueryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundRecordQuery(ctx, req)
}
