// Code generated by Kitex v0.15.4. DO NOT EDIT.

package starstationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	starstation "group/kitex_gen/car/starstation"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetStarStation": kitex.NewMethodInfo(
		getStarStationHandler,
		newStarStationServiceGetStarStationArgs,
		newStarStationServiceGetStarStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateStarStation": kitex.NewMethodInfo(
		createStarStationHandler,
		newStarStationServiceCreateStarStationArgs,
		newStarStationServiceCreateStarStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveDuplicateStops": kitex.NewMethodInfo(
		removeDuplicateStopsHandler,
		newStarStationServiceRemoveDuplicateStopsArgs,
		newStarStationServiceRemoveDuplicateStopsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StarStationList": kitex.NewMethodInfo(
		starStationListHandler,
		newStarStationServiceStarStationListArgs,
		newStarStationServiceStarStationListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	starStationServiceServiceInfo                = NewServiceInfo()
	starStationServiceServiceInfoForClient       = NewServiceInfoForClient()
	starStationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return starStationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return starStationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return starStationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StarStationService"
	handlerType := (*starstation.StarStationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "starstation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getStarStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*starstation.StarStationServiceGetStarStationArgs)
	realResult := result.(*starstation.StarStationServiceGetStarStationResult)
	success, err := handler.(starstation.StarStationService).GetStarStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceGetStarStationArgs() interface{} {
	return starstation.NewStarStationServiceGetStarStationArgs()
}

func newStarStationServiceGetStarStationResult() interface{} {
	return starstation.NewStarStationServiceGetStarStationResult()
}

func createStarStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*starstation.StarStationServiceCreateStarStationArgs)
	realResult := result.(*starstation.StarStationServiceCreateStarStationResult)
	success, err := handler.(starstation.StarStationService).CreateStarStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceCreateStarStationArgs() interface{} {
	return starstation.NewStarStationServiceCreateStarStationArgs()
}

func newStarStationServiceCreateStarStationResult() interface{} {
	return starstation.NewStarStationServiceCreateStarStationResult()
}

func removeDuplicateStopsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*starstation.StarStationServiceRemoveDuplicateStopsArgs)
	realResult := result.(*starstation.StarStationServiceRemoveDuplicateStopsResult)
	success, err := handler.(starstation.StarStationService).RemoveDuplicateStops(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceRemoveDuplicateStopsArgs() interface{} {
	return starstation.NewStarStationServiceRemoveDuplicateStopsArgs()
}

func newStarStationServiceRemoveDuplicateStopsResult() interface{} {
	return starstation.NewStarStationServiceRemoveDuplicateStopsResult()
}

func starStationListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*starstation.StarStationServiceStarStationListArgs)
	realResult := result.(*starstation.StarStationServiceStarStationListResult)
	success, err := handler.(starstation.StarStationService).StarStationList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceStarStationListArgs() interface{} {
	return starstation.NewStarStationServiceStarStationListArgs()
}

func newStarStationServiceStarStationListResult() interface{} {
	return starstation.NewStarStationServiceStarStationListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetStarStation(ctx context.Context, req *starstation.StarStationReq) (r *starstation.StarStationResp, err error) {
	var _args starstation.StarStationServiceGetStarStationArgs
	_args.Req = req
	var _result starstation.StarStationServiceGetStarStationResult
	if err = p.c.Call(ctx, "GetStarStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateStarStation(ctx context.Context, req *starstation.CreateStarStationReq) (r *starstation.CreateStarStationResp, err error) {
	var _args starstation.StarStationServiceCreateStarStationArgs
	_args.Req = req
	var _result starstation.StarStationServiceCreateStarStationResult
	if err = p.c.Call(ctx, "CreateStarStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveDuplicateStops(ctx context.Context, req *starstation.RemoveDuplicateStopsReq) (r *starstation.RemoveDuplicateStopsResp, err error) {
	var _args starstation.StarStationServiceRemoveDuplicateStopsArgs
	_args.Req = req
	var _result starstation.StarStationServiceRemoveDuplicateStopsResult
	if err = p.c.Call(ctx, "RemoveDuplicateStops", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StarStationList(ctx context.Context, req *starstation.StarStationListReq) (r *starstation.StarStationListResp, err error) {
	var _args starstation.StarStationServiceStarStationListArgs
	_args.Req = req
	var _result starstation.StarStationServiceStarStationListResult
	if err = p.c.Call(ctx, "StarStationList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
