// Code generated by Kitex v0.15.4. DO NOT EDIT.
package starservice

import (
	"context"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	starstation "group/kitex_gen/car/starstation"
)

var serviceMethods = map[string]kitex.MethodInfo{
	"GetStarStation": kitex.NewMethodInfo(
		getStarStationHandler,
		newStarStationServiceGetStarStationArgs,
		newStarStationServiceGetStarStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	starStationServiceInfo                = NewServiceInfo()
	starStationServiceInfoForClient       = NewServiceInfoForClient()
	starStationServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

func serviceInfo() *kitex.ServiceInfo {
	return starStationServiceInfo
}

func serviceInfoForClient() *kitex.ServiceInfo {
	return starStationServiceInfoForClient
}

func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return starStationServiceInfoForStreamClient
}

func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}

func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StarStationService"
	handlerType := (*starstation.StarStationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "starstation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getStarStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*starstation.StarStationServiceGetStarStationArgs)
	realResult := result.(*starstation.StarStationServiceGetStarStationResult)
	success, err := handler.(starstation.StarStationService).GetStarStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newStarStationServiceGetStarStationArgs() interface{} {
	return starstation.NewStarStationServiceGetStarStationArgs()
}

func newStarStationServiceGetStarStationResult() interface{} {
	return starstation.NewStarStationServiceGetStarStationResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetStarStation(ctx context.Context, req *starstation.StarStationReq) (r *starstation.StarStationResp, err error) {
	var _args starstation.StarStationServiceGetStarStationArgs
	_args.Req = req
	var _result starstation.StarStationServiceGetStarStationResult
	if err = p.c.Call(ctx, "GetStarStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
