// Code generated by Kitex v0.15.4. DO NOT EDIT.

package ordermanageservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	order_manage "group/kitex_gen/car/order_manage"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"OrderCreate": kitex.NewMethodInfo(
		orderCreateHandler,
		newOrderManageServiceOrderCreateArgs,
		newOrderManageServiceOrderCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OrderPaymentStatus": kitex.NewMethodInfo(
		orderPaymentStatusHandler,
		newOrderManageServiceOrderPaymentStatusArgs,
		newOrderManageServiceOrderPaymentStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OrderQuery": kitex.NewMethodInfo(
		orderQueryHandler,
		newOrderManageServiceOrderQueryArgs,
		newOrderManageServiceOrderQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OrderDetail": kitex.NewMethodInfo(
		orderDetailHandler,
		newOrderManageServiceOrderDetailArgs,
		newOrderManageServiceOrderDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OrderStatusUpdate": kitex.NewMethodInfo(
		orderStatusUpdateHandler,
		newOrderManageServiceOrderStatusUpdateArgs,
		newOrderManageServiceOrderStatusUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderManageServiceServiceInfo                = NewServiceInfo()
	orderManageServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderManageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderManageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderManageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderManageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderManageService"
	handlerType := (*order_manage.OrderManageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order_manage",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func orderCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order_manage.OrderManageServiceOrderCreateArgs)
	realResult := result.(*order_manage.OrderManageServiceOrderCreateResult)
	success, err := handler.(order_manage.OrderManageService).OrderCreate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderManageServiceOrderCreateArgs() interface{} {
	return order_manage.NewOrderManageServiceOrderCreateArgs()
}

func newOrderManageServiceOrderCreateResult() interface{} {
	return order_manage.NewOrderManageServiceOrderCreateResult()
}

func orderPaymentStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order_manage.OrderManageServiceOrderPaymentStatusArgs)
	realResult := result.(*order_manage.OrderManageServiceOrderPaymentStatusResult)
	success, err := handler.(order_manage.OrderManageService).OrderPaymentStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderManageServiceOrderPaymentStatusArgs() interface{} {
	return order_manage.NewOrderManageServiceOrderPaymentStatusArgs()
}

func newOrderManageServiceOrderPaymentStatusResult() interface{} {
	return order_manage.NewOrderManageServiceOrderPaymentStatusResult()
}

func orderQueryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order_manage.OrderManageServiceOrderQueryArgs)
	realResult := result.(*order_manage.OrderManageServiceOrderQueryResult)
	success, err := handler.(order_manage.OrderManageService).OrderQuery(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderManageServiceOrderQueryArgs() interface{} {
	return order_manage.NewOrderManageServiceOrderQueryArgs()
}

func newOrderManageServiceOrderQueryResult() interface{} {
	return order_manage.NewOrderManageServiceOrderQueryResult()
}

func orderDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order_manage.OrderManageServiceOrderDetailArgs)
	realResult := result.(*order_manage.OrderManageServiceOrderDetailResult)
	success, err := handler.(order_manage.OrderManageService).OrderDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderManageServiceOrderDetailArgs() interface{} {
	return order_manage.NewOrderManageServiceOrderDetailArgs()
}

func newOrderManageServiceOrderDetailResult() interface{} {
	return order_manage.NewOrderManageServiceOrderDetailResult()
}

func orderStatusUpdateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order_manage.OrderManageServiceOrderStatusUpdateArgs)
	realResult := result.(*order_manage.OrderManageServiceOrderStatusUpdateResult)
	success, err := handler.(order_manage.OrderManageService).OrderStatusUpdate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderManageServiceOrderStatusUpdateArgs() interface{} {
	return order_manage.NewOrderManageServiceOrderStatusUpdateArgs()
}

func newOrderManageServiceOrderStatusUpdateResult() interface{} {
	return order_manage.NewOrderManageServiceOrderStatusUpdateResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) OrderCreate(ctx context.Context, req *order_manage.OrderCreateReq) (r *order_manage.OrderCreateResp, err error) {
	var _args order_manage.OrderManageServiceOrderCreateArgs
	_args.Req = req
	var _result order_manage.OrderManageServiceOrderCreateResult
	if err = p.c.Call(ctx, "OrderCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OrderPaymentStatus(ctx context.Context, req *order_manage.OrderPaymentStatusReq) (r *order_manage.OrderPaymentStatusResp, err error) {
	var _args order_manage.OrderManageServiceOrderPaymentStatusArgs
	_args.Req = req
	var _result order_manage.OrderManageServiceOrderPaymentStatusResult
	if err = p.c.Call(ctx, "OrderPaymentStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OrderQuery(ctx context.Context, req *order_manage.OrderQueryReq) (r *order_manage.OrderQueryResp, err error) {
	var _args order_manage.OrderManageServiceOrderQueryArgs
	_args.Req = req
	var _result order_manage.OrderManageServiceOrderQueryResult
	if err = p.c.Call(ctx, "OrderQuery", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OrderDetail(ctx context.Context, req *order_manage.OrderDetailReq) (r *order_manage.OrderDetailResp, err error) {
	var _args order_manage.OrderManageServiceOrderDetailArgs
	_args.Req = req
	var _result order_manage.OrderManageServiceOrderDetailResult
	if err = p.c.Call(ctx, "OrderDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OrderStatusUpdate(ctx context.Context, req *order_manage.OrderStatusUpdateReq) (r *order_manage.OrderStatusUpdateResp, err error) {
	var _args order_manage.OrderManageServiceOrderStatusUpdateArgs
	_args.Req = req
	var _result order_manage.OrderManageServiceOrderStatusUpdateResult
	if err = p.c.Call(ctx, "OrderStatusUpdate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
