// Code generated by Kitex v0.15.4. DO NOT EDIT.

package passengerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	passenger "group/kitex_gen/car/passenger"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PassengerDetail(ctx context.Context, req *passenger.PassengerDetailReq, callOptions ...callopt.Option) (r *passenger.PassengerDetailResp, err error)
	PassengerRegister(ctx context.Context, req *passenger.PassengerRegisterReq, callOptions ...callopt.Option) (r *passenger.PassengerRegisterResp, err error)
	PassengerVerify(ctx context.Context, req *passenger.PassengerVerifyReq, callOptions ...callopt.Option) (r *passenger.PassengerVerifyResp, err error)
	SendVerifyCode(ctx context.Context, req *passenger.SendVerifyCodeReq, callOptions ...callopt.Option) (r *passenger.SendVerifyCodeResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPassengerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPassengerServiceClient struct {
	*kClient
}

func (p *kPassengerServiceClient) PassengerDetail(ctx context.Context, req *passenger.PassengerDetailReq, callOptions ...callopt.Option) (r *passenger.PassengerDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PassengerDetail(ctx, req)
}

func (p *kPassengerServiceClient) PassengerRegister(ctx context.Context, req *passenger.PassengerRegisterReq, callOptions ...callopt.Option) (r *passenger.PassengerRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PassengerRegister(ctx, req)
}

func (p *kPassengerServiceClient) PassengerVerify(ctx context.Context, req *passenger.PassengerVerifyReq, callOptions ...callopt.Option) (r *passenger.PassengerVerifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PassengerVerify(ctx, req)
}

func (p *kPassengerServiceClient) SendVerifyCode(ctx context.Context, req *passenger.SendVerifyCodeReq, callOptions ...callopt.Option) (r *passenger.SendVerifyCodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendVerifyCode(ctx, req)
}
