// Code generated by Kitex v0.15.4. DO NOT EDIT.

package starstationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	idl "group/kitex_gen/idl"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetStarStation": kitex.NewMethodInfo(
		getStarStationHandler,
		newStarStationServiceGetStarStationArgs,
		newStarStationServiceGetStarStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateStarStation": kitex.NewMethodInfo(
		createStarStationHandler,
		newStarStationServiceCreateStarStationArgs,
		newStarStationServiceCreateStarStationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveDuplicateStops": kitex.NewMethodInfo(
		removeDuplicateStopsHandler,
		newStarStationServiceRemoveDuplicateStopsArgs,
		newStarStationServiceRemoveDuplicateStopsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	starStationServiceServiceInfo                = NewServiceInfo()
	starStationServiceServiceInfoForClient       = NewServiceInfoForClient()
	starStationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return starStationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return starStationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return starStationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StarStationService"
	handlerType := (*idl.StarStationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "idl",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getStarStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idl.StarStationServiceGetStarStationArgs)
	realResult := result.(*idl.StarStationServiceGetStarStationResult)
	success, err := handler.(idl.StarStationService).GetStarStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceGetStarStationArgs() interface{} {
	return idl.NewStarStationServiceGetStarStationArgs()
}

func newStarStationServiceGetStarStationResult() interface{} {
	return idl.NewStarStationServiceGetStarStationResult()
}

func createStarStationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idl.StarStationServiceCreateStarStationArgs)
	realResult := result.(*idl.StarStationServiceCreateStarStationResult)
	success, err := handler.(idl.StarStationService).CreateStarStation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceCreateStarStationArgs() interface{} {
	return idl.NewStarStationServiceCreateStarStationArgs()
}

func newStarStationServiceCreateStarStationResult() interface{} {
	return idl.NewStarStationServiceCreateStarStationResult()
}

func removeDuplicateStopsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*idl.StarStationServiceRemoveDuplicateStopsArgs)
	realResult := result.(*idl.StarStationServiceRemoveDuplicateStopsResult)
	success, err := handler.(idl.StarStationService).RemoveDuplicateStops(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStarStationServiceRemoveDuplicateStopsArgs() interface{} {
	return idl.NewStarStationServiceRemoveDuplicateStopsArgs()
}

func newStarStationServiceRemoveDuplicateStopsResult() interface{} {
	return idl.NewStarStationServiceRemoveDuplicateStopsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetStarStation(ctx context.Context, req *idl.StarStationReq) (r *idl.StarStationResp, err error) {
	var _args idl.StarStationServiceGetStarStationArgs
	_args.Req = req
	var _result idl.StarStationServiceGetStarStationResult
	if err = p.c.Call(ctx, "GetStarStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateStarStation(ctx context.Context, req *idl.CreateStarStationReq) (r *idl.CreateStarStationResp, err error) {
	var _args idl.StarStationServiceCreateStarStationArgs
	_args.Req = req
	var _result idl.StarStationServiceCreateStarStationResult
	if err = p.c.Call(ctx, "CreateStarStation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveDuplicateStops(ctx context.Context, req *idl.RemoveDuplicateStopsReq) (r *idl.RemoveDuplicateStopsResp, err error) {
	var _args idl.StarStationServiceRemoveDuplicateStopsArgs
	_args.Req = req
	var _result idl.StarStationServiceRemoveDuplicateStopsResult
	if err = p.c.Call(ctx, "RemoveDuplicateStops", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
